### ISSUE TITLE
ESLint: no-var-name-same-as-state-property does not handle function/method args

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#1012]
[Mitosis Fiddle](https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNroDRwC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjA5UwVFQDcAKHHoAHpFhw2JAIbIm8EsgB2AYxjdNcALIBPAMIVIm9JpgAKMOTCoAlInFw42iJtTxfSmHQ4AF4UDGxcWwR3DzgodFRLDAAuOAByTVUmNLwYj1QlADd0ACUEpPRbeMTvFLhfKGBNAHNXaNjYrx94OiUoELgq8tr0VIam1pCAPjcOjviYZCgDaoqJOaJJDY0dPW84XoAvIZqfUfqYRpa2vLmFpZXhs9uPQi25%2F0COVZGBn7P1rFCLlXs4JDF7stBrcADwsYCFKYvOAACXQTCYEFhPHhiJiYPEhCAA%3D%3D%3D)

```tsx
import { useStore, } from "@builder.io/mitosis";

export default function MyComponent(props) {
  const state = useStore({
    response: 'null',
    // should error
    saveResponse(response: string) {
      // should error
      const bar = (response: string) => {
        return response;
      }
  
      // should error
      function baz(response: string) {
        return response
      }

      state.response = response;
    },
  });

  return (
    <div>
      Hello
    </div>
  );
}
```

We need to make sure that argument names (whether for methods, functions or const anonymous functions) are also caught by the lint rule.

**Comment by samijaber** [comment]
cc @sahilmob

**Comment by sahilmob** [comment]
Please assign to me @samijaber
