### ISSUE TITLE
React: Caught errror when i using props.slot with <Show>

### ISSUE THREAD

**Issue by findlay-best-wishes** [BuilderIO/mitosis#1031]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbwFBzgZQBYQO5IL5wBmUEIcA5AAIBGArsADYAmAplAHTAQD0IwMEAM7BB5JEhYAPSLDitCAQ1oN4hWgDsAxjC7q4ABQiQAbmwAUYEmEEBKRONRQWMWlD1mUqOAB4mwYwB8nl4%2BmDhw2Bgs6gC8CJZGguyCDBAwAMIQ6jDRMHgB8VZJKWmZ2bl43txh2EEhVX6Bnjb4SEA%3D&inputTab=FYZwHkA%3D

### Expected Behaviour

Compile successfully.

### Actual Behaviour

Caught error.

**Comment by samijaber** [comment]
Thanks for reporting. I think we can fix this by modifying this logic:

https://github.com/BuilderIO/mitosis/blob/84645d4ee333996716c1a9ac8e8625b283ade624/packages/core/src/generators/react/helpers.ts#L24

to import and use this helper: https://github.com/BuilderIO/mitosis/blob/84645d4ee333996716c1a9ac8e8625b283ade624/packages/core/src/parsers/svelte/helpers/children.ts#L6

i.e. `filterChildren(json).length !== 1`

**Comment by moaoa** [comment]
it compiles successfully for me

here is the react output: 

import * as React from "react";

function Popover(props) {
  return <div>{props.slot ? <>{props.slot}</> : null}</div>;
}

export default Popover;

**Comment by kingzez** [comment]
Maybe this fixes it by the way  https://github.com/BuilderIO/mitosis/pull/1123

**Comment by samijaber** [comment]
True, thanks!
