### ISSUE TITLE
React:The scope of variety lost when i used dynamic component within <For >.

### ISSUE THREAD

**Issue by findlay-best-wishes** [BuilderIO/mitosis#1036]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgMWgGjgZQBYQO5wC%2BcAZlBCHAEQACARgK7AA2AJgKZQB0wEA9CGAwIAZ2AiqAbgBQ09gA9IsOBxIBDBs3gkGAOwDGMXrrgBZAJ4BhCpF3tdMABRhyYEQEpE0uHG9wo7DAMUCaOfj4APKzAAG4AfOE%2BcAAS7MzMEImRqFBw7Gr62AC8CC4QblwFRhC6IoQJSY2IjlXGnkVxcGFNTVGxDT29OPhweNj2Ja01PPo19VmDkVO6MzVwfAOLkXzDeJtbESJgarpxCMtcMAowhBF8Ryf7PXfR8Qs%2B7oQLdzn7L%2F1%2BdwyQhAA%3D%3D%3D&inputTab=FYZwHkA%3D

### Expected Behaviour

transform as the following,
```
import * as React from "react";

export default function MyComponent(props) {
  return (
    <div>
      Hello
      {props.actions?.map((action) => (
        <div>
          {action.icon ? (
            <>
              <action.icon />
            </>
          ) : null}

          <span>{action.text}</span>
        </div>
      ))}
    </div>
  );
}
```

### Actual Behaviour

The `action.icon` been raised to the top level of function.

**Comment by samijaber** [comment]
This is the code that makes this happen: https://github.com/BuilderIO/mitosis/blob/fd301d9d695bbe52973b9782dd5fcfc938ac877a/packages/core/src/helpers/process-tag-references.ts#L6-L31


I think we can safely delete this code entirely and stop doing this. Don't think it's needed at all!

**Comment by kingzez** [comment]
> This is the code that makes this happen:
> 
> https://github.com/BuilderIO/mitosis/blob/fd301d9d695bbe52973b9782dd5fcfc938ac877a/packages/core/src/helpers/process-tag-references.ts#L10
> 
> I think we can safely delete this code entirely and stop doing this. Don't think it's needed at all!

delete this, this test case won't pass
https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/__tests__/data/blocks/builder-render-block.raw.tsx#L42-L44


`<tagName() >`  caused SyntaxError

```jsx
  <tagName()  {...state.properties} style={state.css}>
```

```log
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/__tests__/context.test.ts > Context > Use and set context in complex components
SyntaxError: Identifier expected. (109:9)
  107 |
  108 |
> 109 | <tagName()  {...(properties())}  style={css()}>
      |         ^
  110 |
  111 | <BlockStyles  block={useBlock()}  />
  112 |
 ❯ Ve ../../node_modules/prettier/parser-typescript.js:1:15607
 ❯ vz ../../node_modules/prettier/parser-typescript.js:280:5919
 ❯ Object.yz [as parse] ../../node_modules/prettier/parser-typescript.js:280:6242
 ❯ Object.m [as parse] ../../node_modules/prettier/standalone.js:40:1354
 ❯ S ../../node_modules/prettier/standalone.js:41:15055
 ❯ D ../../node_modules/prettier/standalone.js:45:576
 ❯ ../../node_modules/prettier/standalone.js:116:7304
 ❯ Proxy.format ../../node_modules/prettier/standalone.js:116:7395
 ❯ src/generators/react/generator.ts:184:14
    182|     if (options.prettier !== false) {
    183|       try {
    184|         str = format(str, {
       |              ^
    185|           parser: 'typescript',
    186|           plugins: [
 ❯ src/__tests__/context.test.ts:35:46

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "codeFrame": "  107 |
  108 |
> 109 | <tagName()  {...(properties())}  style={css()}>
      |         ^
  110 |
  111 | <BlockStyles  block={useBlock()}  />
  112 |",
  "loc": {
    "start": {
      "column": 9,
      "line": 109,
    },
  },
}
```

**Comment by samijaber** [comment]
Ah, thanks for checking @kingzez. That makes sense. I will need to think through an alternative solution then...

**Comment by moaoa** [comment]
Hey @samijaber how can we solve this one?

**Comment by moaoa** [comment]
hey @samijaber  when I used the condition `el.name.includes('.') to el.name.includes('.') && el.name.includes('(') && el.name.includes(')')` no element was matched, is there another way for us to detect function names?
