### ISSUE TITLE
Qwik compilation issue

### ISSUE THREAD

**Issue by astraldev** [BuilderIO/mitosis#1047]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [X] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=I4dwlg1kA%3D%3D%3D&code=JYWwDg9gTgLgBAbwFBzgGQIYCMCmAbABSgjAGckBfOAM2JDgCIA6AehgE8wdSGBuJUJFiIUcAOY4YREqQCiADwDGOMDEo06jJq20sArjGB5SLCTAC0YYmXM4lKmHwHho8ZKgBWEYADsAwngYpKTc6rQQ9Mw6rAZGJl6%2B5oqBwdxOgq4iqMlBIeRU4ZGsOak8%2FEh2QvAAJjjUGHp48NR6PoqGED7o2PgAFFYyAFzduITWpACUWXBQknpQXb2iqAA8gaPLqHAlpAByGCA4ALwIvb1TRwB8m1twCf4peUu3LyP4TD4HOAA0Ny873CYWCCPz%2BtwGZCYOzBcAmE3OFD%2BCG0TDM0jICmUqn642%2BjB2DDxDEUAAsjNVZj5CYwSTAQHgAGLQBgTRGvajQE4Q0hMWn0plQNkva63BDcqFkvAUnA%2BIWrFjrfAi2EUIA%3D%3D%3D

### Expected Behaviour

Should compile the *for* attribute to *for* attribute and not htmlFor in qwik

### Actual Behaviour

Compiles for attribute to htmlFor which is a non existent property for label element in qwik

**Comment by samijaber** [comment]
Just need to remove this line! https://github.com/BuilderIO/mitosis/blob/4f04d025896fc48b59b47da8ebf7a702a06da4df/packages/core/src/generators/qwik/src-generator.ts#L353

**Comment by astraldev** [comment]
Has this been resolved?
