### ISSUE TITLE
Transformed imports contain incorrect file extension for context 

### ISSUE THREAD

**Issue by kingzez** [BuilderIO/mitosis#1056]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgZQBYQO4Bo4FcDOApgMIQB2MhAHvAL5wBmUEIcA5AAIBGuwANgBNCUAHTAIAehDAYEfMHxsA3AChQkWHABCuGLLKkK1eExbsREnnvIiAxuUo0RfGYTYqVEgFReVcL3CACAzQwADmwGSAiAx%2BATFwVvp2DsbOriIw%2BHExEh7esf5BMFAAhmT4DNAghALRBXEJNvZGThlwWQVWcOrQ8CIAVviM%2FIRwcAAG3Zo61gbJNIzMrABEFg1kSc0w%2FfhLY3H46LiCcPhFwGBw23DGhGXiZNke1BrwEZRQDMW2I9P6AArMMCDBB%2BODFPRQYBWQj4AD8AC4wWQAJ6qUaOGAIk5nMihNFwFxkADWWNOkNx%2BIgYFuABkIkSAJJkAByhAwABVilwsVwIBA%2BIRSqpaE8qC84EJPkcTLgyLYYPdtLp9AAKMCA%2FCI37kAFU%2FAASkQoKapzg8qocAAvHgiIYMSrtbNNvrQVBCDBcFAyHAVaDRgAeAB8ftGcH9aEwIdDcAwqFuloQ6r1qWJIuj0cIfCICf9%2BDApUQIiLSaBInBZ2h%2BFogcTGvSxlo%2FokedKgbT6eD6dD%2FuKUfTCCLIhL%2BDLEKhuhh7a7o2AAgT5rEAin0%2BYAstSzWSz70dQboYCeHKaJy67MGKUFC7oPdaptPpTNZHK5cFh7AA%2Blw%2BKUiWw4IjZZKETVCeoadtOoy1smGIgQGEjFGB0ZNhGGAIWGEhgfqwoqEAA

### Expected Behaviour

```
/**
 * 【origin】
 * 
 * button.context.lite.ts
 * 
 */

/** 
 * 【transformed】
 * 
 * button.context.ts 
 * 
 * but import .js file  `import ButtonContext from "./button.context.js"`
 * should strip .js extension
 */
```

### source
```js
import { Show, useContext } from '@builder.io/mitosis';
import ButtonContext from './button.context.lite'
```

### output
```js
import ButtonContext from "./button.context";
```

### output
```js
import ButtonContext from "./button.context.js";
```

### Additional Information

Similar to  https://github.com/BuilderIO/mitosis/issues/991

**Comment by samijaber** [comment]
Why do you want to strip the `.js` extension? as explained in https://github.com/BuilderIO/mitosis/issues/809#issuecomment-1297287607, having an explicit `.js` extension is recommended for ESM support. If you have a TS file, then you can still write `.js` and Typescript will handle that correctly. It will point to the TS file instead.

There is no downside for having explicit extensions, and it's actually better for imports to have explicit extensions

**Comment by kingzez** [comment]
>  If you have a TS file, then you can still write .js and Typescript will handle that correctly. It will point to the TS file instead.

I have a TS file, but not works at vue2+vite project,  you can look this Reproduction case
 https://github.com/kingzez/context-extensions

**Comment by samijaber** [comment]
That's more of a vite bug


if I update your dependencies, the error goes away: https://github.com/samijaber/context-extensions/commit/d21bbe67bc1db5ee169004f5c634958aa88e6d23

Most probably this bug which was fixed: https://github.com/vitejs/vite/issues/3040


Going to close this issue since adding `.js` extension should not be an issue as per the ESM spec, but feel free to re-open if something else comes up.
