### ISSUE TITLE
How to compile to Typescript instead of JavaScript with QWIK

### ISSUE THREAD

**Issue by Nedimko123** [BuilderIO/mitosis#1058]
If you open up Mitosis Fiddle you have the options to compile to typescript or javascript with Qwik, but how to do it inside a CLI with @builder.io/mitosis, right? I've been searching it in the src code like this: https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/generators/qwik/component.ts where   output?: 'ts' | 'cjs' | 'mjs'; should be set to ts, right?

I've been trying it like this inside mitosis.config.js:

const seedrandom = require('seedrandom');
const rng = seedrandom('vue-sdk-seed');

const getSeededId = () => {
  const rngVal = rng();
  return Number(String(rngVal).split('.')[1]).toString(36);
};

module.exports = {
  files: 'src/**',
  isTypeScript: true,
  targets: ['vue3', 'qwik', 'webcomponent'],
  options: {
    qwik:{ 
      isTypeScript: true,
      output: 'ts',
    },
    isTypeScript:true,
    vue: {
      cssNamespace: getSeededId,
    },
  },
};

The question is how do you do it?

**Comment by samijaber** [comment]
Your config is wrong. It's `typescript: true`, not `isTypeScript`. Also, we don't have an `output` config. The file you're looking at is an internal one whose options are not the ones you edit in `mitosis.config.js`.

Use the `MitosisConfig` type as suggested here: https://github.com/BuilderIO/mitosis#setup-mitosisconfigjs

This will help you make sure you are using the correct config properties.

**Comment by Nedimko123** [comment]
`typescript: true,` worked, thanks 👍
