### ISSUE TITLE
Compilation fails due to no newline in the Show tag

### ISSUE THREAD

**Issue by kingzez** [BuilderIO/mitosis#1081]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [x] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgZQBYQO5wL5wGZQQhwBEAAgEYCuwANgCYCmUAdMBAPQjAwQDOwPiQDcAKFGMAHpFhwmeAIZVa8PFQB2AYxjt1cALIBPAMJFI6xupgAKMITB8AlIlFw4ruFEYwqUPdY83AB56YAA3AD5AuA4OOAxoAGto4LRMeNRLAF4EOwgHFh0YWkZsKLcKitz7PkKeEuwUuCCONIwo6Ni4dQh4BKhEgC44CkZNJT5GOAg8eKgFMDgAfhWmoLaM7Or82qKGiO2CvdKWtojKt2iW0MiPRzFsIA%3D%3D

### Expected Behaviour

`<Show>` tag subitems must have line breaks to compile successfully. It should be compatible with unwrapped writing

```jsx
import { Show } from "@builder.io/mitosis";

export default function MyComponent(props) {
  
  return (
    <div>
      {/* work */}
      <Show when={props.title}>
        {props.title}
      </Show>

      {/* not work: because of wrap ??? */}
      <Show when={props.title}>{props.title}</Show>      
    </div>
  );
}
```

### Actual Behaviour

```log
SyntaxError: ',' expected. (26:7) (at ca3a5a57.eb20e802993fda71.js:1:13346)
  24 |
  25 | {props.title ? (
> 26 | {props.title}
     |       ^
  27 | ) : null}
  28 |
  29 | </div>
    at r (ca3a5a57.eb20e802993fda71.js:1:13346)
    at qr (ca3a5a57.eb20e802993fda71.js:1:3441394)
    at Object.Wr [as parse] (ca3a5a57.eb20e802993fda71.js:1:3441704)
    at Object.p [as parse] (c4ec0132.ff59c1ab7db9c0a2.js:1:102962)
    at E (c4ec0132.ff59c1ab7db9c0a2.js:1:117888)
    at b (c4ec0132.ff59c1ab7db9c0a2.js:1:120470)
    at c4ec0132.ff59c1ab7db9c0a2.js:1:432364
    at format (c4ec0132.ff59c1ab7db9c0a2.js:1:432449)
    at 574.46be52cca95735d1.js:1:197958
    at 574.46be52cca95735d1.js:1:380910
    at s (main-79e130091ee21132.js:1:86890)
    at Generator._invoke (main-79e130091ee21132.js:1:86678)
    at forEach.e.<computed> [as next] (main-79e130091ee21132.js:1:87313)
    at r (218.40c6b86280210e15.js:2008:3756359)
    at s (218.40c6b86280210e15.js:2008:3756562)
```

**Comment by samijaber** [comment]
I don't think this is an issue in every generator. It is per-generator most likely, based on how each generator generates the children of `Show`.

In the case of React outputs:

https://github.com/BuilderIO/mitosis/blob/e6d4d0d18a9e2fecd4a2c32d6a48d9a10a93477c/packages/core/src/generators/react/helpers.ts#L24

This check should instead be something like:

```
json.children.length !== 1 && !isRootTextNode(json)
```

to also add fragments when there's 1 text node

**Comment by kingzez** [comment]
Yeah, It's not every generator, I forgot choose generator. It just happened in React generator.
