### ISSUE TITLE
Qwik : Generator should output API's supported in the RC version of Qwik

### ISSUE THREAD

**Issue by akshatgarg12** [BuilderIO/mitosis#1087]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [X] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=I4dwlg1kA%3D%3D%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN0A0cAxlOnugMIQB2%2BAHjEWlbQ03LQLITJ1wBfOADMoEEHABEAAQBGyYABsAJuigA6YBAD0IYDAipgqSQG4AUOfT1IsErVTwAcjhCs61%2BAF4SZCtQ9GAAoAchpXdABaYjZPEIBKS2tbeFVhHGRFeGE%2BYhgtGjguAE9qcFp0OiCwMTBUeMRzOHsaRzhwtwD2OB8WLs8gl07YxkTm7l4qoIavAD5G5uaY1ohFdHVFCABzUIALdEVNhKbBMbgyGGQoQqCTuAAeXYBGWYAJA8377WfZk%2FiLARAA%3D

### Expected Behaviour

- [ ] `createContext` should be generated as `createContextId` in qwik
- [ ]  `onMount` to `useVisibleTask$` instead of  `useClientEffect$`

_will add more as we encounter them_

### Actual Behaviour

Code generated is for previous versions of Qwik. 
These are breaking changes when upgrading to `Qwik version : 0.100.0`

### Additional Information

Qwik RC has released , so we expect gradual changes in Qwik API moving forward.

**Comment by manucorporat** [comment]
onMount() should be useTask$()
