### ISSUE TITLE
onInit async

### ISSUE THREAD

**Issue by Nedimko123** [BuilderIO/mitosis#1098]
Why does this not get marked with **_async_** modifier when it compiles to Qwik:
`onInit(async () => {
    const url = new URL(
      'https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json'
    );
    try {
      const res = await fetch(url, {
        headers: {
          'User-Agent': 'Motism',
          accept: 'application/json',
        },
      });
      const data = await res.json();
      state.gridOptions.rowData = data;
    } catch (error) {
      console.log(error);
    }
  });`

**Comment by samijaber** [comment]
None of the Mitosis hooks can have their inner function `async`. It is a similar situation to React's `useEffect`: https://devtrium.com/posts/async-functions-useeffect

The fix is the same as what the article suggests.

Similar to #1014
