### ISSUE TITLE
Control flow not working in Liquid

### ISSUE THREAD

**Issue by SupaSibs** [BuilderIO/mitosis#1105]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=DYSwjgriAmQ%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN0A0cmAFhAO5EBi0cAvnAGZQQhwBEAAgEbLAA2AE3RQAdMAgB6EMBgRUwVOwDcAKFXoAHpFhxhjHMn7xGyAHYBjGBLNwAsgE8Awq0hn0ZmAAowLMKgBKRFU4OAsIM1R4AG0zHBBCOAwYADl49ABdOABeFAxsPHQvdmx0ADd0dgC1ELgodBhkKFsvWtCAHkFgMoA%2BNtC4dtIKOHISD2yEAEYAains7IAmBnR%2BDEn2nvawHu4cKHbJHcOeuj6Bgc3tnsYICEPjyXOLwclh8meL9pooOHQcCwkSbRKYERYZM4ILyaABccDMyBA3BEQWyPUGOwQmjoD1Ohx%2Bn1eXV6tWqqjoQA%3D%3D&inputTab=FYZwHkA%3D

### Expected Behaviour

I expect liquid to generate a div with a conditional statement:
```
{% if 1 + 1 ==  2 %}
  foo
{% else %}
bar
{% endif %}
```
 followed by a loop:
```\
{% for x in [1,2] %}
  {{ x }}
{% endfor %}
```

### Actual Behaviour

It simply generates an empty div element  with no functionality.

**Comment by samijaber** [comment]
The logic that handles `Show` and `For` in the Liquid generator is here:

https://github.com/BuilderIO/mitosis/blob/26a4f4ffdaef0f0001038ed5adbb7f0669a832e8/packages/core/src/generators/liquid.ts#L69-L92

I assume the `isValidLiquidBinding` early return is what's causing the issues. I would look into this logic and see what needs to change:

https://github.com/BuilderIO/mitosis/blob/26a4f4ffdaef0f0001038ed5adbb7f0669a832e8/packages/core/src/generators/liquid.ts#L26

(I am not familiar with Liquid at all, hence not being able to give moe specific help)

**Comment by samijaber** [comment]
> Was alrezdy looking there, but I don't really wanna do anything till i actually find some sort of solution. Is there a way to build Mitosis from a custom branch in a repository? I forked Mitosis to test with things like these but i don't know how to build anything from ./packages.

Yeah, you can build the entire repo by running `yarn ci:build`, then go to any individual `packages` subfolder and run `yarn snapudpate` inside of `packages/core` to update snapshot tests once you've made changes
