### ISSUE TITLE
Preserve or generate the return types of state methods

### ISSUE THREAD

**Issue by kingzez** [BuilderIO/mitosis#1112]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=PTAEAsBdIBwZwFwgOYEtLgK4CMB0BjAewFtgAhTVAGwBMBTAJwEkB5YY9QuVOYbKwtnYBDVADtgMYfgDWw5HV5EGdYHAb5gAfS2RFkODuA1hkYXwGylhKpmJi4uBsIDuuAwA8AUF9TEYhAyQoADeoJhwdADKkIF0ADSgAGKBoAC%2BoABmDCSgAOQAAtiUtIy4qITsnNxweQDcPpAAnjB0oADCNnZioAC8oV6goERieqMIoMJiTQ1DIKAAKiwAIiwTTP5UdMR0o6AYPKAu4LugcJgwAUFZqTRNYsIc%2BB1RUaBUUzRwg0eoNBgAfgmYjs2EYDTSDS8dA8V2C4j0DEy0janVs9gACjl4AMhkR0Q4gR0uvYANoAXShczAS1W602212wQOcCOJx650ugWCmVu90eqGe7Ve70%2B3yGcCk%2BDoRJBxDBDFmoHmtLWoA2MC2Oz2LLZp05cJuDFAdweTxebw%2BYi%2BPzgZlkaO6cAAgpAiXkzPw6JA8qAAD75YiCah0X0BvJiOgAN0Y9R%2BKpWao1WqZ%2B3Ah2O%2Bouht5xtNAqFIqtNqGKhjDEijvscAA6uyYtIZHQaETsIQbHQphCfDDDfRkZgqDzMGJ8JAKj0q2IABQwbGIYkErGEeAASlxw0IDmCdtMbX6EWisRU05CPyGCkgU7g09XEynFI3Q1L3swDB6c5XjnxTv9AYpSpDGk8TnqAl4AOKYNAjBRKgABedC3sCoKME%2Bz4qJAb49M0rSEJkoCfvAuCSiifS9P0EYoQwvoAgR87EVKbR%2BgGAAMoATAATCxgHpCBz5gd6NZ%2FBg07iPQHjIfKjDrme%2FF4ludqbgSrL9Luei4Je163jxL6Ye%2BoDTj%2B1akmJMLkqAABkFlKU6JnWmZuAuMJ4DrsxoAAIwsWxYBGQ4uBbGIyAYDxwGgZpJJiO0cC1s5on2RJoBygqMmgfJ242dWfRnGY6nhcp2mpZu6XIFBiKwQhWVqXQGnepB0EMOViGrjpRWKec2CQM4Y5Cf84BZdOJX1Y1oAAFQGb5jgBUFfUALQeau64%2BRFk27NNLUYVhoAAAb4MIVD4NOAAkIRVTVkA9SJpkeKuaQAKSgHNx3tZ10jnc5aQwNdW0hXx6TNT4umbdOoEADw0KgUaFfgHzRb0ABExTUPQDAzRNcNQ7DISyXJQzg5KHxNBMeSZFsHh5L9OMkzCyyoCoY4TkTvnk4VQx7agyBiEwejEAueR2hh%2BDgMzONDFQ4h0AAEnQ7NQETYiBMQe3CyLhQ7ODwgGYrHgzU5vUTAAnIbn2rnkEzYyLWSkzTdPjluRM5C4ys46FFuq82qAa9OWs685EwAGwAMz68bptoZTVu03Q9N2%2FkDszWWjCRE7ckuynaSgQAfIVIMpManaC70ISEd%2By1pFnFshIZEWJFd669BnBks8%2BYMQ8MMNwPDiOlCjvlw8MmNhFTHjgQ7RPub6aRl03%2FEhL5BBbmMkAZCEV3pxbQwg8YEPlyLN3Z8Auc7xvW9Rjv%2F3p0AA%3D

### Expected Behaviour

> What we currently preserve is the argument types, and all types inside of the body. We don't preserve or generate the return types of state methods yet.

raw file : https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/__tests__/data/blocks/columns.raw.tsx#L25

```tsx
const state = useStore({
  getColumns(): Column[] {
    return props.columns || [];
  },
  getGutterSize(): number {
    return typeof props.space === 'number' ? props.space || 0 : 20;
  },
```

snapshot: https://github.com/BuilderIO/mitosis/pull/1085/files#diff-5c26547ec6bd2e4158291b871805f8465adcd4f2ffdd69227d4f028e643737a7L3770

```js
methods: {
  getColumns() { // here should has type Column[]
    return this.columns || [];
  },
  getGutterSize() { // here should has type number
    return typeof this.space === \\"number\\" ? this.space || 0 : 20;
  },
```

_Originally posted by @kingzez in https://github.com/BuilderIO/mitosis/issues/909#issuecomment-1503766963_
            

### Actual Behaviour

We don't preserve or generate the return types of state methods yet.

**Comment by samijaber** [comment]
## Step 1 - store return type information

We already do something similar here in another part of the parser: https://github.com/BuilderIO/mitosis/blob/9ec59b0f05e7abb46f82dd9532e2a75ae0a5a3de/packages/core/src/parsers/jsx/function-parser.ts#L182-L185


We will need to add similar logic for our `method` parsers:

https://github.com/BuilderIO/mitosis/blob/9ec59b0f05e7abb46f82dd9532e2a75ae0a5a3de/packages/core/src/parsers/jsx/state.ts#L118-L128

https://github.com/BuilderIO/mitosis/blob/9ec59b0f05e7abb46f82dd9532e2a75ae0a5a3de/packages/core/src/parsers/jsx/state.ts#L144-L151



## Step 2 - output return types in each generator

This will be different for each generator. In the case of React, we generate the state methods here:

https://github.com/BuilderIO/mitosis/blob/9ec59b0f05e7abb46f82dd9532e2a75ae0a5a3de/packages/core/src/generators/react/state.ts#L32-L63

Edit the `method` case do inject the `typeParameter` in the right place if it exists
