### ISSUE TITLE
Feature Request: Global TypeScript option in Mitosis Config

### ISSUE THREAD

**Issue by matthewsimo** [BuilderIO/mitosis#1114]
Currently you have to define `typescript: true`  inside `options` per target, but it would be nice if the config supported a global `typescript: true` flag that would apply to all relevant targets.

**Comment by samijaber** [comment]
Steps to do this:


1- add `commonOptions: { typescript: boolean }` to this type: https://github.com/BuilderIO/mitosis/blob/26a4f4ffdaef0f0001038ed5adbb7f0669a832e8/packages/core/src/types/config.ts#L17-L18


2- add a check of `commonOptions.typescript` here: https://github.com/BuilderIO/mitosis/blob/26a4f4ffdaef0f0001038ed5adbb7f0669a832e8/packages/cli/src/build/helpers/options.ts#L13

```
return options.options[target]?.typescript ? options.options[target].typescript : options.commonOptions?.typescript
```

and here: https://github.com/BuilderIO/mitosis/blob/26a4f4ffdaef0f0001038ed5adbb7f0669a832e8/packages/cli/src/build/build.ts#L104-L105

```
targetsOptions.filter((option) => option.typescript || options.commonOptions?.typescript).length
```

**Comment by ohkimur** [comment]
@matthewsimo I very much like this idea. I also thought of making a PR with that.
