### ISSUE TITLE
useStore doesn't produce required output for react

### ISSUE THREAD

**Issue by astraldev** [BuilderIO/mitosis#1119]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [X] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN0A0KG206cAvnAGZQQhwBEAAgEbLAA2AJulAHTAIAehDAYEVMFSMA3ACh56AB6RYcYADt8UajgDG5AHI4AbgEl8DBPLh24%2BZTABccVDChaA5gvtx9OJycrAYA1q4AFJBSMEKargDamsggrHxEyal8ALoAlHAAvAB8cDiaAJ4KFIoqavBaOnqGcABqfLEBnCamACJ4OIi2%2FhDa6NquNn4SYK7dluggCdlDdqwQMBIgs2bzi8t21dVKqtDwvHrInPDUyJr6sSNwALLlAML0kJpjMFF0YKiuNqwYCdbp9XD5SbDTTuNy4fCFYhYCRQdARKF2aYAfXECwBcDAf1Q%2FH0I3w2n40wIKzgwmEcFegWCYVQNOxnWZ%2BlC%2BMJEH%2BJLJ30pfP4IBwYAiEVxIFQ%2BWKGisxI5IS5uWpfjWG02WOVLNcvP5pNGFM1m1F4sl0tlhRKVpJTJVoTVNLpDIdYQ0ml4yho0DgIAgrC45F4Ui8mhpAaDnHQWPZ7q5OK9KlcAAZ1fYo8Gsab6DqE6Ek960xm7K7GUFHZ7vb6oP7A8G4KHgOGaaHQtj45WwkWU3B0230KgO3yc%2BttbrE1pi%2F2MxRcgohqiYMgoJo4BEaQAeS5FGl2BDuPDoYVgHGK80SqVWIjAbjKOUlTd%2BPxbzjAfcv0LocoFBB35RqhfF8Rled8uT%2FCJH0GYDgKNWFJ1CREj3wU9827LlUAST9YLhY9RQbGM41HRDe2UHCX2yCIEnTPDUKzIiu05QtpxUPJfFw%2BwUJPBjYyYx0yIAakEjjOLgZdV3XRDRNgiggNgvcxK3VAwDKIp%2FysSkVBgCgt2EFS1IovT30Ul9clyeS7D03chgXeQKCAA

### Expected Behaviour

I expected to see something like this for the output 

```
...
const [top_callbacks, setTop_callbacks] = useState(() =>
    props.content.top.map((items) => items.callback)
  );
const [mobile_top_callback_index, setMobile_top_callback_index] = useState(
    () => 0
  );
...
return (
   {data.map(() => <li onClick={ const callback =  top_callbacks[mobile_top_callback_index]; setMobile_top_callback_index(mobile_top_callback_index+1); return callback())} > <span>{item.text}</span> </li>}
 )
```

### Actual Behaviour

I  see something like this at the output 

```
...
const [top_callbacks, setTop_callbacks] = useState(() =>
    props.content.top.map((items) => items.callback)
  );
const [mobile_top_callback_index, setMobile_top_callback_index] = useState(
    () => 0
  );
...
return (
   {data.map(() => <li onClick={ const callback =  top_callbacks[mobile_top_callback_index]; mobile_top_callback_index+1; return callback())} > <span>{item.text}</span> </li>}
 )
```

### Additional Information

This method only works well for qwik output.

**Comment by astraldev** [comment]
This was resolved by changing the increment statement from `state.mobile_top_callback_index++` to `state.mobile_top_callback_index = state.mobile_top_callback_index + 1`

**Comment by samijaber** [comment]
Yeah, we are likely missing some logic to handle increment statements like `state.foo++` (or even `state.foo += 1`) in the JSX parser
