### ISSUE TITLE
 Props with type Object/Array must use a factory function to return the default value in vue

### ISSUE THREAD

**Issue by PengBoUESTC** [BuilderIO/mitosis#1121]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgZQBYQO5wL5wGZQQhwDkAAgEYCuwANgCYCmUAdMBAPQjAwQDOwPiQDcAKFGMAHpFhxgAOxjM8AQwDGjOAEkQKgOaMACoTB9EouHDW0VfPgH4AXHD4woCvWMuh9jZ6%2Fd5TwsXYAAvRgd%2FNw8vOBswgE8nOAoICFpGFXk41EZgPVQYFPkqEApmOIxgehhUErKKqDiVWhgAFSli6MDgywp1AGs9Qip5emRwxhSA2JCBtWHR8cN%2BHnZ5GZiguL4oNT5GbpdtvrhbMEY1GAAlFRh2BvLKkLVUOnooRk3nbMS4vA8ADCEEU32OaQyWRyomw4ikMngTFUVDa%2BDG1w22l0BgAFGATHxnDpfMYIKYAJTmSxfGBUKDyOC4kKWAA89GAADcrHYALwIJCQAQPUHOEhfGwPTmMEg4bAAPhZljgrLAwGu9MYiuVOpVoD0St18QgKg5QV5ACIEokLYbda0YPyCeS%2BCwHZ1JDA4UadSp3CoALSETJOwlutoe%2BD2UgEyLg%2B4bWXOMbIhSMejen2WA58fkIO1G8nqHiJMUARhIABoC7q3NlhRsxUW1CW4AAGFgAJjMWUOAYUAYgVBgVZrOqF61FpBUFD4GWHMurWZ1eQKRXLbbbAFJR8vldVaqgN9vd3u4LwwGK22BJKe95k8DArze7z7sJms65EiGBWPlRAKAAKyuGBVgbKdnVMFgFiWIdxkmCI4AAHyQ0gNDBKBXyzADgOuAAxHhnHxMMYJGOCJimc4zD%2BKkULQiBpUwpdl3fP9rFsXMEBIdi7H7HEZTgABqJlINdHizGjWVZWE0SWHEuAxRICkPx9PY1FDF02H4lSjQ4Dg4HaAB5AARQznBARgQAgSjQTkfi4Fs6xgHBP81MOR0EFktyjh03UBAiTivKmPhfMsDhtR9Vk53pDQXH2ZAjg0qDvK9OBwrtVkODVDUvg

### Expected Behaviour

 Props with type Object/Array must use a factory function to return the default value.

### Actual Behaviour

 Props with type Object/Array convert as Object/Array

**Comment by PengBoUESTC** [comment]
![截屏2023-04-14 下午2 19 06](https://user-images.githubusercontent.com/57180744/231959057-a4861931-1ba3-4add-bf2e-8dfe9a2644d0.png)

**Comment by samijaber** [comment]
I don't fully understand, the playground link you provided shows the basic example.

`Expected Behaviour` and `Actual Behaviour` should point to specific lines of code. Can you share what the exact code output you currently get is, and how you want to see that changed?

**Comment by kingzez** [comment]
duplicate https://github.com/BuilderIO/mitosis/issues/1120
