### ISSUE TITLE
CSS pseudo selectors and classes like `:hover` or `:active` without `&` are compiled with unnecessary whitespace

### ISSUE THREAD

**Issue by ohkimur** [BuilderIO/mitosis#1125]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNrrgXzgDMoIQ4AiAAQCNlgAbAE3SgDpgIB6EYHVYKgoBuAFCj0AD0iw4LIgENkDeEWQA7AMYxO6uAFkAngGEykdenUwAFGFJhUASkSi4cTRHWp43hTDwAvCgY2LjWCK5ucOoKIOgAXJTY6ABu6BSR+I5ibpFQ6DDIUHrWkW4APEzAKQB8ZVHlwOpgyDD1Ue6oqAEIER397hAM0IkU+UwUADTt/RTxABYQaVBzLgMDNAqaANYA5qQaTIkA5OPHMx34FwRX63ApCgzI6D2+/mwxcbfrnsbzCupdi8ENZUpYYM4AjVEHA3ugPrFAnAwVY2DAFFAgTA2A8nnh8N8Olw6gMABLoBjDGYIOEIr4AQjgAEl3AC4FANHAmnAAEroLYwSZwABqzyFmCGwCYQugcAAMsAAI70Jj0+rlLhVWqRbKifBAA%3D

### Expected Behaviour

When using pseudo selectors or classes like `:hover` or `:active` the compiler should not add unnecessary whitespace. When using the `&` symbol, like in `&:hover` this doesn't happen.

When using the `styled-components` or `emotion` syntax, for example, the compiled CSS in js from `twin.macro`, the compiled CSS is not working properly because of the additional whitespace.

NOTE: I discovered this first when tried to compile to `react` with `styled jsx`, it `style-tag`.

For the following input:

```tsx
import { useStore } from "@builder.io/mitosis";

export default function MyComponent(props) {
  const state = useStore({
    name: "Steve"
  });
  
  return (
    <div>
      <input
        css={{
          color: "red",
          ":hover": {
            background: 'red'
          }
        }}
        value={state.name}
        onChange={(event) => { state.name = event.target.value }}
      />
      Hello
      {state.name}! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}```

we should get the following output:

```tsx
import * as React from "react";
import { useState } from "react";

function MyComponent(props: any) {
  const [name, setName] = useState(() => "Steve");

  return (
    <>
      <div>
        <input
          className="input"
          value={name}
          onChange={(event) => {
            setName(event.target.value);
          }}
        />
        Hello
        {name}! I can run in React, Vue, Solid, or Liquid!
      </div>
      <style jsx>{`
        .input {
          color: red;
        }
        .input:hover {
          background: red;
        }
      `}</style>
    </>
  );
}

export default MyComponent;
```

### Actual Behaviour

When using pseudo selectors or classes like `:hover` or `:active` the compiler adds unnecessary whitespace.

For the following input:
```tsx
import { useStore } from "@builder.io/mitosis";

export default function MyComponent(props) {
  const state = useStore({
    name: "Steve"
  });
  
  return (
    <div>
      <input
        css={{
          color: "red",
          ":hover": {
            background: 'red'
          }
        }}
        value={state.name}
        onChange={(event) => { state.name = event.target.value }}
      />
      Hello
      {state.name}! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}```

we get the following output:

```tsx
import * as React from "react";
import { useState } from "react";

function MyComponent(props: any) {
  const [name, setName] = useState(() => "Steve");

  return (
    <>
      <div>
        <input
          className="input"
          value={name}
          onChange={(event) => {
            setName(event.target.value);
          }}
        />
        Hello
        {name}! I can run in React, Vue, Solid, or Liquid!
      </div>
      <style jsx>{`
        .input {
          color: red;
        }
        .input :hover {
          background: red;
        }
      `}</style>
    </>
  );
}

export default MyComponent;
```

**Comment by samijaber** [comment]
You'll wanna add some logic here:

https://github.com/BuilderIO/mitosis/blob/6af5bd00c9056ee019a30d7062ffcb2c34cc3435/packages/core/src/helpers/styles/collect-css.ts#L100-L102


But the whitespace is required for nested selectors, so make sure it's not lost for those cases
