### ISSUE TITLE
Imports are not placed at the top of the file when TypeScript interface is present for `vue`

### ISSUE THREAD

**Issue by ohkimur** [BuilderIO/mitosis#1127]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&inputTab=FYZwHkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNrrgXzgDMoIQ4AiAAQCNlgAbAE3SgDpgIB6EYHVYKgoBuAFChIsOABV0qeCTJwA5DDkxlo8QDs1UIgEMAxngCyATwDCZSNvS6ACqTCpEouHCMALRkyj2ALjgDbXNRfC10AA9JeBZDZAYFZG0jGE5tOAtrcAg7XQAKMGdUIOybPPsYJwgXAEo3DyM8+Th5AzU4AF4UDGxcAoR3DzhtAxB0IIpsdAA3dAoAGmGmiAZoIOV/Jk0PfDqxD2H/GGQoTIKVuAAeJmBZgD4rj2vgbTBkGGeRo1RULoQQxGwJ+aw2lG2S2+ewiIJGswMDGQ6AB7TUbDGE1hcLgeUsXhCAHMUQgCnMqg0ug9EG0YB10BjxngeuTdGw6VBiTA2AikXh8NjgVwnnCABLoBjrb4INEMzHofAAQjgAElPCE4FAUnA3nAAEroYwwRZwABqyJNmDWwCYJugcAAMsAAI70JiK6XFWqoNjeXz+bSCm5cO6PYYHcJAA%3D%3D

### Expected Behaviour

When an import and an interface are present, like in the following example:
```tsx
import { useStore } from "@builder.io/mitosis";
import Test from './test.lite'

interface MyComponentProps {
  children: any
}

export default function MyComponent(props: MyComponentProps) {
  const state = useStore({
    name: "Steve",
    color: 'red'
  });
  
  return (
    <div>
      <input
        css={{
          color: "red",
        }}
        value={state.name}
        onChange={(event) => { state.name = event.target.value }}
      />
      Hello
      {state.name}! I can run in React, Vue, Solid, or Liquid!
      {props. children}
    </div>
  );
}
```
for the vue target, the compiler should place the imports at the top of the file, like in the following output example:

```tsx
<template>
  <div>
    <input class="input" :value="name" @input="name = $event.target.value" />
    Hello
    {{ name }}! I can run in React, Vue, Solid, or Liquid!
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import Test from "test";

interface MyComponentProps {
  children: any;
}

const props = defineProps<MyComponentProps>();
const name = ref("Steve");
const color = ref("red");
</script>

<style scoped>
.input {
  color: red;
}
</style>
```

### Actual Behaviour

When an import and an interface are present, like in the following example:
```tsx
import { useStore } from "@builder.io/mitosis";
import Test from './test.lite'

interface MyComponentProps {
  children: any
}

export default function MyComponent(props: MyComponentProps) {
  const state = useStore({
    name: "Steve",
    color: 'red'
  });
  
  return (
    <div>
      <input
        css={{
          color: "red",
        }}
        value={state.name}
        onChange={(event) => { state.name = event.target.value }}
      />
      Hello
      {state.name}! I can run in React, Vue, Solid, or Liquid!
      {props. children}
    </div>
  );
}
```
for the vue target, the compiler should place the imports at the top of the file, but it doesn't, like in the following example:

```tsx
<template>
  <div>
    <input class="input" :value="name" @input="name = $event.target.value" />
    Hello
    {{ name }}! I can run in React, Vue, Solid, or Liquid!
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
interface MyComponentProps {
  children: any;
}

import Test from "test";

const props = defineProps<MyComponentProps>();
const name = ref("Steve");
const color = ref("red");
</script>

<style scoped>
.input {
  color: red;
}
</style>
```

**Comment by samijaber** [comment]
https://github.com/BuilderIO/mitosis/blob/6af5bd00c9056ee019a30d7062ffcb2c34cc3435/packages/core/src/generators/vue/vue.ts#L223-L232


The order of items added is:

- `vue` library imports
- types information
- all other imports (sibling components and others)

You can move the `component.types` line below `renderPreComponent` to address this

**Comment by ohkimur** [comment]
@samijaber That sounds great. After I searched through the repo I intuited the problem is around here, but I wasn't sure. I'll make a PR with a fix for this.

**New Idea:** I think at the moment it's a bit harder to check the output of the compiler during development without using the fiddle locally. I saw that the `twin.macro` repo has a `sandbox` with an `in.tsx` file where people can try to put their code and build an `out.tsx` file very fast. This is very useful because it makes it very easy to test if the changes to the compiler are doing what you wanted very fast. Do you think something like this is worth doing? If yes, I'll make an issue and a PR for that.

**Comment by samijaber** [comment]
@ohkimur interesting idea, please create a separate issue/discussion and we can talk about it there!
