### ISSUE TITLE
Request to open sponsor~

### ISSUE THREAD

**Issue by 0x219** [BuilderIO/mitosis#116]
I hope this project will continue...

**Comment by steve8708** [comment]
Hey @0x219 - really appreciate the request! Right now Mitosis is backed by Builder.io - one great way to ensure we continue to thrive and support this project is to look into using Builder.io :D 

From what I can tell, most company backed projects don't take open sponsorship (e.g. React, Angular, Next.js, etc) vs independent projects often do (Vue, Webpack, etc)

It may be best for us to follow suit, unless one day it were to happen that Builder.io would or could no longer back the project (very unlikely but hey anything is possible) then I'd happily open it up for sponsorship.

Happy to keep this open for discussion though

**Comment by 0x219** [comment]
thanks~ 💓
