### ISSUE TITLE
Conditionals not supported?

### ISSUE THREAD

**Issue by mindplay-dk** [BuilderIO/mitosis#117]
Any plans to support [conditional expressions with JSX](https://jsx-lite.builder.io/?outputTab=json&code=import+%7B+useState+%7D+from+%22react%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+%5Bname%2C+setName%5D+%3D+useState%28%22Steve%22%29%3B%0A++const+%5BshowName%2C+setShowName%5D+%3D+useState%28true%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%7BshowName%0A++++++++%3F+%3Cinput%0A++++++++++++css%3D%7B%7B%0A++++++++++++++color%3A+%22red%22%2C%0A++++++++++++%7D%7D%0A++++++++++++value%3D%7Bname%7D%0A++++++++++++onChange%3D%7B%28event%29+%3D%3E+setName%28event.target.value%29%7D%0A++++++++++%2F%3E%0A++++++++%3A+%3Cspan%3EName+editor+disabled%3C%2Fspan%3E%0A++++++%7D%0A++++++Hello%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D)?

![image](https://user-images.githubusercontent.com/103348/127617565-91912006-6fed-4559-ac4e-533e1dfa14fe.png)

This is fairly idiomatic - not just to React, but to JSX with most frameworks and libraries.

It looks like you do support [loops](https://jsx-lite.builder.io/?outputTab=json&code=import+%7B+useState+%7D+from+%22react%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+%5Btodos%2C+setTodos%5D+%3D+useState%28%5B%22laundry%22%2C%22cleaning%22%2C%22shaving+%28for+once%29%22%5D%29%3B%0A%0A++return+%28%0A++++%3Cul%3E%0A++++++%7Btodos.map%28todo+%3D%3E+%3Cli%3E%7Btodo%7D%3C%2Fli%3E%29%7D%0A++++%3C%2Ful%3E%0A++%29%3B%0A%7D) so I was a bit surprised you don't see to support conditionals - it seems like loops would be more difficult to implement, so maybe this is just a bug?

Either way, loops and conditionals are both pretty essential to building any UI, I think. 🙂

**Comment by steve8708** [comment]
Ah! thanks for catching @mindplay-dk! Right now there are two ways to do conditions, ternaries are coming up on my todo list

In the meantime, you can use the facade `<Show />` component, like

```tsx
import { Show } from '@builder.io/mitosis'

<Show when={showName}><input ... /></Show>
<Show when={!showName}>Name editor disabled/Show>
```

or `&&` boolean operator

```tsx
import { Show } from '@builder.io/mitosis'

{showName && <input ... />}
{!showName && <>Name editor disabled</>}
```

Def agree that ternary needs support, will keep this open until added shortly

**Comment by steve8708** [comment]
Implemented locally, will be merged soon

<img width="1459" alt="Screen Shot 2021-09-06 at 12 54 05 PM" src="https://user-images.githubusercontent.com/844291/132257259-43735a6a-c35c-4374-8da9-a9d36bce9f09.png">

**Comment by steve8708** [comment]
Beta support added, if you hit any issues lmk and happy to look into
