### ISSUE TITLE
@builder.io/mitosis-cli is not in the npm registry, or you have no permission to fetch it.

### ISSUE THREAD

**Issue by YogliB** [BuilderIO/mitosis#118]
I couldn't find `@builder.io/mitosis-cli` on npm, what am I doing wrong?

**Comment by steve8708** [comment]
Thanks for catching @YogliB ! Just published the latest version https://www.npmjs.com/package/@builder.io/mitosis-cli

we are a mid a lot of updates so there is a chance something is broken, so worst case you can always use the prior name which is documented over [here](https://www.npmjs.com/package/@jsx-lite/cli)
