### ISSUE TITLE
mitosis fiddle/CLI/local-dev not available in any way

### ISSUE THREAD

**Issue by tompere** [BuilderIO/mitosis#119]
I'd really like to play with mitosis, but can't find a way to make it work...

1. [interactive fiddle](https://mitosis.builder.io/) is down for the past week.
2. CLI is not working, getting:
```shell
 $ mitosis compile --to=vue my-file.lite.jsx
```
results in:
```
Error: Cannot find module 'prettier/parser-html'
```
3. and the last resort - cloning the project and attempting to install, bootstrap and build fail on different reasons (missing files, `file://..` deps that do not exists, etc.).

any plans on making one of the above options available for external users (and potential fans 😉 )?

**Comment by steve8708** [comment]
Ah, thanks for catching @tompere ! Had to do a ton of find and replace + refactoring when changing the name to Mitosis - let me look into your issues, and in the meantime using the old names should work

[jsx-lite.builder.io](jsx-lite.builder.io) for the fiddle

```bash
npm install -g @jsx-lite/cli

jsx-lite compile compile --to=vue my-file.lite.jsx
```

Will leave this open until the issues you mention with the new names are fixed!

**Comment by steve8708** [comment]
ok - just updated the mitosis CLI

if you update to the latest 

```
npm install -g @builder.io/mitosis-cli@latest
``` 

your command sholud work as expected

```
mitosis compile --to=vue my-file.lite.jsx
```

**Comment by steve8708** [comment]
also just updated the appropriate DNS record to support mitosis.builder.io for the fiddle as expected - should be live within the next couple hours!

closing out for now, but if anything is still not working here lmk and feel free to reopen

**Comment by tompere** [comment]
awesome! thanks
