### ISSUE TITLE
How do I run this project on my local machine? 

### ISSUE THREAD

**Issue by aramay** [BuilderIO/mitosis#121]
When I try `yarn install` in root path - It throughs an error

`error Package "" refers to a non-existing file '"/xxx/xxx/Documents/codesmith-ptri3/core"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Package "eslint-plugin-mitosis" refers to a non-existing file '"/xxx/xxx/Documents/codesmith-ptri3/eslint-plugin"'.
    at MessageError.ExtendableBuiltin (/xxx/xxx/.nvm/versions/node/v14.15.3/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/xxx/xxx/.nvm/versions/node/v14.15.3/lib/node_modules/yarn/lib/cli.js:750:123)
    at FileResolver.<anonymous> (/xxx/xxx/.nvm/versions/node/v14.15.3/lib/node_modules/yarn/lib/cli.js:50230:15)
    at Generator.next (<anonymous>)
    at step (/xxx/xxx/.nvm/versions/node/v14.15.3/lib/node_modules/yarn/lib/cli.js:310:30)
    at /xxx/xxx/.nvm/versions/node/v14.15.3/lib/node_modules/yarn/lib/cli.js:321:13`

ENV:
yarn -v: 1.22.10
MacOS Big Sur

Please let me know if there is more info I can provide to troubleshoot. TY

**Comment by steve8708** [comment]
hey @aramay - we use npm for this repo instead of yarn, does `npm install` from the root work as expeted?

**Comment by aramay** [comment]
@steve8708 - Yes, `npm install` works but it fails on `npm run build`

`@builder.io/mitosis-cli: [4:15:28 PM] Projects in this build:
@builder.io/mitosis-cli:     * ../core/tsconfig.json
@builder.io/mitosis-cli:     * tsconfig.json
@builder.io/mitosis-cli: [4:15:28 PM] Project '../core/tsconfig.json' is out of date because output file '../core/dist/src/flow.js' does not exist
@builder.io/mitosis-cli: [4:15:28 PM] Building project '/xxx/xxx/codesmith-ptri3/mitosis/packages/core/tsconfig.json'...
@builder.io/mitosis-fiddle: Creating an optimized production build...
@builder.io/mitosis: src/generators/qwik.ts(54,21): error TS2322: Type 'NodePath<Node> | null' is not assignable to type 'NodePath<any>'.
@builder.io/mitosis:   Type 'null' is not assignable to type 'NodePath<any>'.
@builder.io/mitosis: src/generators/qwik.ts(84,21): error TS2322: Type 'NodePath<Node> | null' is not assignable to type 'NodePath<any>'.
@builder.io/mitosis:   Type 'null' is not assignable to type 'NodePath<any>'.
@builder.io/mitosis: src/generators/html.ts(350,21): error TS2322: Type 'NodePath<Node> | null' is not assignable to type 'NodePath<any>'.
@builder.io/mitosis:   Type 'null' is not assignable to type 'NodePath<any>'.
@builder.io/mitosis: src/jsx-types.ts(14,10): error TS2300: Duplicate identifier 'Element'.
@builder.io/mitosis: src/jsx-types.ts(33,10): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
@builder.io/mitosis: npm ERR! code ELIFECYCLE
@builder.io/mitosis: npm ERR! errno 1
@builder.io/mitosis: npm ERR! @builder.io/mitosis@0.0.44-21 build: `tsc --build`
@builder.io/mitosis: npm ERR! Exit status 1
@builder.io/mitosis: npm ERR!
@builder.io/mitosis: npm ERR! Failed at the @builder.io/mitosis@0.0.44-21 build script.
@builder.io/mitosis: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@builder.io/mitosis: npm ERR! A complete log of this run can be found in:
@builder.io/mitosis: npm ERR!     /xxx/xxx.npm/_logs/2021-08-10T23_15_34_852Z-debug.log
lerna ERR! npm run build exited 1 in '@builder.io/mitosis'
lerna ERR! npm run build stdout:

> @builder.io/mitosis@0.0.44-21 build /xxx/xxxDocuments/codesmith-ptri3/mitosis/packages/core
> tsc --build`

**Comment by aramay** [comment]
@steve8708 Hello 👋 

Any update on this?

**Comment by aramay** [comment]
Hey @steve8708 - I wanted to startup fiddle `env` on my local machine. If I run `npm run build` inside `packages/core` will that let me bring up the ENV?

**Comment by aramay** [comment]
npm install fails in `packages/core`
```
eslint-plugin: No matching version found for eslint-plugin@0.0.2.
npm WARN old lockfile     at module.exports (/xxx/xxx.nvm/versions/node/v14.15.3/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /xxx/xxx.nvm/versions/node/v14.15.3/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/xxx/xxx.nvm/versions/node/v14.15.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:681:9)
npm WARN old lockfile  Could not fetch metadata for eslint-plugin@0.0.2 eslint-plugin: No matching version found for eslint-plugin@0.0.2.
npm WARN old lockfile     at module.exports (/xxx/xxx.nvm/versions/node/v14.15.3/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /xxx/xxx.nvm/versions/node/v14.15.3/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/xxx/xxx.nvm/versions/node/v14.15.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:681:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '0.0.2',
npm WARN old lockfile   versions: [ '1.0.1' ],
npm WARN old lockfile   distTags: { latest: '1.0.1' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
```

At this point `npm run build` will not work either
```
src/jsx-types.ts:14:10 - error TS2300: Duplicate identifier 'Element'.

14     type Element =
            ~~~~~~~

  ../../node_modules/@types/react/index.d.ts:3046:19
    3046         interface Element extends React.ReactElement<any, any> { }
                           ~~~~~~~
    'Element' was also declared here.

src/jsx-types.ts:33:10 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

33     type LibraryManagedAttributes<Component, Props> = Props;
            ~~~~~~~~~~~~~~~~~~~~~~~~

  ../../node_modules/@types/react/index.d.ts:3055:14
    3055         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.


Found 2 errors.
```

**Comment by steve8708** [comment]
I see - let me break down the steps for you to run the fiddle. Note - you'll want to pull the latest code, I just pushed some changes that should fix some confusion

```bash
npm install

cd packages/core
npm install
npm run build

cd ../... # back to root folder
cd packages/fiddle
npm install
npm start # runs the fiddle locally
```

we will have some better docs and commands for local development soon, but let me know if this works as expected on the latest code ^

**Comment by aramay** [comment]
hey @steve8708 - pulled latest changes. However It fails when I run `npm run build` inside `packages/core`

```
core [main] :> npm run build

> @builder.io/mitosis@0.0.44-21 build
> tsc --build

src/jsx-types.ts:14:10 - error TS2300: Duplicate identifier 'Element'.

14     type Element =
            ~~~~~~~

  ../../node_modules/@types/react/index.d.ts:3048:19
    3048         interface Element extends React.ReactElement<any, any> { }
                           ~~~~~~~
    'Element' was also declared here.

src/jsx-types.ts:33:10 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

33     type LibraryManagedAttributes<Component, Props> = Props;
            ~~~~~~~~~~~~~~~~~~~~~~~~

  ../../node_modules/@types/react/index.d.ts:3057:14
    3057         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.


Found 2 errors.

```

**Comment by enidovasku** [comment]
hey @aramay I followed all the steps suggested by @steve8708 and could run the project flawlessly. Could you try a fresh close of the project?

ENV:
MacOS Big Sur
Node v16.4.0

**Comment by aramay** [comment]
@enidovasku - I'll give this another try.

**Comment by aramay** [comment]
@steve8708 / @enidovasku 
Ok. I've fiddle `ENV` up and running on local machine 🎉

I think the issue was, I was using node version `v14.17.6` and `package.json` has `"node": "12",` in it. That was causing issues. 

Thanks for following up, i'll keep you posted.
