### ISSUE TITLE
I want to get the default slots or props.children, how do I do that?

### ISSUE THREAD

**Issue by wabi-habi** [BuilderIO/mitosis#1233]
### I am interested in helping provide a feature!

Yes

### Which generators are impacted?

- [x] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### What problem does this feature solve?

Example: Let's say the `Space` component iterates over all the elements of the incoming `slots.default()` or `props.children` and wraps a `div` around the outer layer, how do I implement this?

```jsx
import { Slot } from '@builder.io/mitosis'

export default function MySpace(props) {
  return (
    <div class="space">
      <Slot />
    </div>
  )
}
```

```jsx
<MySpace>
  <div>1</div>
  <div>2</div>
</MySpace>
```

The following results are desired

```html
<div class="space">
  <div class="sapce-item">
    <div>1</div>
  </div>
  <div class="sapce-item">
    <div>2</div>
  </div>
</div>
```

### What does the proposed API look like?

You can get the slot elements and then iterate over each element to process it individually

**Comment by kingzez** [comment]
Duplicated https://github.com/BuilderIO/mitosis/issues/945

**Comment by wabi-habi** [comment]
Another issue is that I may need to get the slots to make a determination

Examples:

`vue`

```vue
<div v-if="$slots.xxx">xxx</div>
```

`react`

```jsx
{props.xxx &&  <div >xxx</div>}
```

**Comment by samijaber** [comment]
like @kingzez mentioned, we do not plan on implementing a `Children` API like React's.

As for the 2nd question, you can currently do that like this: https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgZQBYQO5wL5wGZQQhwBEAAgEYCuwANgCYCmUAdMBAPQjAwQDOwPiQDcAKFGMAHpFhwmeAIZVa8PFQB2AYxjt1cALIBPAMJFI6xupgAKMITB8AlIlFw4URjCpQ91127gAHjRMOAxUSwBeBDsIBxZNVDp6D3VsAD5%2FAKD6YAA3dIAJRlpaCECOXIKsoI4QjEy3RzFsIA%3D%3D

It unfortunately doesn't consistently work across all frameworks, because they do not all have a way to access the value of their slots (Qwik doesn't for example). But it does work for Vue, React, Svelte, and many others.

**Comment by wabi-habi** [comment]
> https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgZQBYQO5wL5wGZQQhwBEAAgEYCuwANgCYCmUAdMBAPQjAwQDOwPiQDcAKFGMAHpFhwmeAIZVa8PFQB2AYxjt1cALIBPAMJFI6xupgAKMITB8AlIlFw4URjCpQ91127gAHjRMOAxUSwBeBDsIBxZNVDp6D3VsAD5%2FAKD6YAA3dIAJRlpaCECOXIKsoI4QjEy3RzFsIA%3D%3D

Ok, thanks, but the link you gave can't be accessed!

**Comment by wabi-habi** [comment]
> like @kingzez mentioned, we do not plan on implementing a `Children` API like React's.
> 
> As for the 2nd question, you can currently do that like this: https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgZQBYQO5wL5wGZQQhwBEAAgEYCuwANgCYCmUAdMBAPQjAwQDOwPiQDcAKFGMAHpFhwmeAIZVa8PFQB2AYxjt1cALIBPAMJFI6xupgAKMITB8AlIlFw4URjCpQ91127gAHjRMOAxUSwBeBDsIBxZNVDp6D3VsAD5%2FAKD6YAA3dIAJRlpaCECOXIKsoI4QjEy3RzFsIA%3D%3D
> 
> It unfortunately doesn't consistently work across all frameworks, because they do not all have a way to access the value of their slots (Qwik doesn't for example). But it does work for Vue, React, Svelte, and many others.

OK, it did, and that's really cool!

**Comment by wabi-habi** [comment]
> like @kingzez mentioned, we do not plan on implementing a `Children` API like React's.
> 
> As for the 2nd question, you can currently do that like this: https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgZQBYQO5wL5wGZQQhwBEAAgEYCuwANgCYCmUAdMBAPQjAwQDOwPiQDcAKFGMAHpFhwmeAIZVa8PFQB2AYxjt1cALIBPAMJFI6xupgAKMITB8AlIlFw4URjCpQ91127gAHjRMOAxUSwBeBDsIBxZNVDp6D3VsAD5%2FAKD6YAA3dIAJRlpaCECOXIKsoI4QjEy3RzFsIA%3D%3D
> 
> It unfortunately doesn't consistently work across all frameworks, because they do not all have a way to access the value of their slots (Qwik doesn't for example). But it does work for Vue, React, Svelte, and many others.

ok, it really did, that's really cool, thanks!
