### ISSUE TITLE
Will the Show component support vue-like v-if v-else-if v-else in the future?

### ISSUE THREAD

**Issue by wabi-habi** [BuilderIO/mitosis#1235]
### I am interested in helping provide a feature!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### What problem does this feature solve?

Will the `Show` component support vue-like `v-if` `v-else-if` `v-else` in the future?`

### What does the proposed API look like?

```jsx
<Show if={xxx}>
</Show>

<Show elseIf={xxx}>
</Show>

<Show else>
</Show>
```

**Comment by wabi-habi** [comment]
> No current plans for this, but it could be interesting to implement! React, Vue, Qwik, Svelte would work out of the box. Would need to thin through the ones that don't (like Solid, whose `<Show>` only has a `when` and `fallback`.

Is this good to realize? I'd like to try.

**Comment by wabi-habi** [comment]
> No current plans for this, but it could be interesting to implement! React, Vue, Qwik, Svelte would work out of the box. Would need to thin through the ones that don't (like Solid, whose `<Show>` only has a `when` and `fallback`.

OK, it's great, if there's anything I can do, I'll help!

**Comment by dpchamps** [comment]
Hello 👋 I'd be interested in implementing this. I'm currently writing a custom mitosis parser. I assumed that something like the following would compile (lots of props snipped):

```json
{
  "@type": "@builder.io/mitosis/node",
  "name": "Show",
  "meta": {
    "else": {
      "@type": "@builder.io/mitosis/node",
      "name": "Show",
      "meta": {
        "else": {
          "@type": "@builder.io/mitosis/node",
          "name": "Else",
        }
      },
      "scope": {},
      "children": [],
      "bindings": {
        "when": {
          "code": "false",
          "type": "single"
        }
      },
      "properties": {}
    }
  },
  "scope": {},
  "children": [
    {
      "@type": "@builder.io/mitosis/node",
     
      "bindings": {}
      },
      "properties": {}
    }
  ],
  "bindings": {
    "when": {
      "code": "label",
      "type": "single"
    }
  },
  "properties": {}
}
```

The code that gets generated is very close to being correct:

```jsx
{label ? (
  <>{label}</>
) : {false ? (
  <p> hello </p>
) : <><Else  /></>}}
```

What considerations would we have to make? I'm happy to work on this feature.
