### ISSUE TITLE
Problems with vue onUpdated event

### ISSUE THREAD

**Issue by wabi-habi** [BuilderIO/mitosis#1236]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

Additional information is available in full code

### Expected Behaviour

`mitosis`

<img width="378" alt="image" src="https://github.com/BuilderIO/mitosis/assets/99811051/3c28413c-70f5-4d60-8745-d878e3f49518">

`vue`

<img width="528" alt="image" src="https://github.com/BuilderIO/mitosis/assets/99811051/33c4424a-6f05-4d6c-a7d0-4e3b04e625bf">

### Actual Behaviour

`vue`

<img width="396" alt="image" src="https://github.com/BuilderIO/mitosis/assets/99811051/b01c4abe-d5c8-4b69-ac11-ab5c5e91a971">

### Additional Information

Full Code:

```jsx
import { onUpdate, useStore } from '@builder.io/mitosis'

export default function MyComponent(props) {
  const state = useStore({
    scale: 1
  })

  onUpdate(() => {
    if (!props.src && !props.icon) return

    state.scale = Math.random() * 10
  })

  return <div>{state.scale}</div>
}
```

**Comment by samijaber** [comment]
@wabi-habi thanks for filing. We're missing the `{` and `}` braces in this line:

https://github.com/BuilderIO/mitosis/blob/811e71936f27c5908d89b4d5fb4d78863ffa03f0/packages/core/src/generators/vue/compositionApi.ts#L135

If you wanna contribute a fix that'd be awesome! 🙏🏽

- make the fix
- run `yarn snapupdate` in `packages/core` to update snapshots
- run `yarn fm:prettier` in the root of the codebase to format your changes

**Comment by wabi-habi** [comment]
This is really necessary, as many components are completely unwieldy without jsx functionality
