### ISSUE TITLE
props not outputted with componentJson

### ISSUE THREAD

**Issue by Manborough** [BuilderIO/mitosis#124]
Currently component props don't appear to be outputting in the component json.
So a component like this with explicit props.

```js
export default function Home (title, body) {
  return ( 
     <div>
          <h1>{title}</h1>
          <div>{body}</div>
     </div>
)
```
Isn't returned in this.

```js
{
  '@type': '@jsx-lite/component',
  imports: [],
  meta: {},
  state: {},
  children: [
    {
      '@type': '@jsx-lite/node',
      name: 'html',
      meta: {},
      properties: {},
      bindings: {},
      children: [Array]
    }
  ],
  hooks: {},
  context: { get: {}, set: {} },
  name: 'Home',
  subComponents: []
} 
```

At least as far as I have found.

**Comment by steve8708** [comment]
Hey @Manborough  - as of right now we don't parse the props in any special way. We do though require you to use the conventional name `props` for the component arguments at this time

```tsx
export default function Home (props) {
  return ( 
     <div>
          <h1>{props.title}</h1>
          <div>{props.body}</div>
     </div>
  )
}
```

they won't show up on the component JSON as we don't know at compile time necessarily what props exist (currently), but we can parse out which are used by finding JS expressions using `props.*`

e.g. you can see that we list out what props are used in the Vue output [here](https://mitosis.builder.io/?outputTab=vue&code=export+default+function+Home+%28props%29+%7B%0A++return+%28+%0A+++++%3Cdiv%3E%0A++++++++++%3Ch1%3E%7Bprops.title%7D%3C%2Fh1%3E%0A++++++++++%3Cdiv%3E%7Bprops.body%7D%3C%2Fdiv%3E%0A+++++%3C%2Fdiv%3E%0A++%29%0A%7D) (`props: ["title", "body"]`), which is extracted from finding the references to `props.title` and `props.body` in the JSX bindings of the component

![image](https://user-images.githubusercontent.com/844291/129757139-0a8c234a-e997-47cf-b617-c8c1794706e2.png)

**Comment by Manborough** [comment]
Thanks for the reply @steve8708 

I bought it up because I was adapting Mitosis for use with Go's jet template engine and I wanted to list the props in the component that is being outputted and you need to know them all by name.

```html
{{ block Home( newItemName=newItemName ) }}

<html>
  <head>
    <script type="module" src="http://0.0.0.0:4000/@vite/client"></script>

    <script
      type="module"
      src="http://0.0.0.0:4000/javascript/index.js"
    ></script>

    <title></title>
  </head>

  <body>
    <h1 class="bg-green-500">Hello</h1>

    {{ yield content }} {{newItemName}}
  </body>
</html>

{{end}}
```

For now i've worked around it by using state instead of props, though I suppose I could feed in a struct on the Go end and call it props.

**Comment by steve8708** [comment]
@Manborough very cool! Also in case helpful [this function](https://github.com/BuilderIO/mitosis/blob/react-native-stuff/packages/core/src/helpers/get-props.ts#L10:L10) can extract the props used from the tree (as a `Set` of strings representing their names)

You can see how we use it e.g. for [Vue](https://github.com/BuilderIO/jsx-lite/blob/react-native-stuff/packages/core/src/generators/vue.ts#L297:L297) and [Svelte](https://github.com/BuilderIO/mitosis/blob/react-native-stuff/packages/core/src/generators/svelte.ts#L215:L215) outputs

I don't think we currently export that function from the @builder.io/mitosis package root but easily could
