### ISSUE TITLE
How to import by name

### ISSUE THREAD

**Issue by wabi-habi** [BuilderIO/mitosis#1252]
### I am interested in helping provide a feature!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### What problem does this feature solve?

`mitosis`

```jsx
import test from `test-${target}`
```

`vue`

```jsx
import test from 'test-vue'
```

`react`

```jsx
import test from 'test-react'
```

### What does the proposed API look like?

Is this feature supported? I'm just kind of guessing as well!

**Comment by samijaber** [comment]
Not sure what this feature is meant to be, but no, nothing like that is supported.

Each output should be stored in its own npm package, with its own `package.json`. That is the right way to publish the outputs: as separate packages. Here is an example app:

- https://github.com/BuilderIO/mitosis/tree/d0f2f0c2bb0476a7165a2202791e2b2545c20d94/e2e/e2e-app
- output package.json`s are here:
  - vue: https://github.com/BuilderIO/mitosis/blob/d0f2f0c2bb0476a7165a2202791e2b2545c20d94/e2e/e2e-app/output/vue/package.json
  - qwik: https://github.com/BuilderIO/mitosis/blob/d0f2f0c2bb0476a7165a2202791e2b2545c20d94/e2e/e2e-app/output/qwik/package.json
- and then they are imported here:
  -  qwik: https://github.com/BuilderIO/mitosis/blob/d0f2f0c2bb0476a7165a2202791e2b2545c20d94/e2e/e2e-qwikcity/src/routes/%5B...index%5D/index.tsx#L3
  - vue: https://github.com/BuilderIO/mitosis/blob/d0f2f0c2bb0476a7165a2202791e2b2545c20d94/e2e/e2e-vue3/src/App.vue#L2
