### ISSUE TITLE
The `typescript` of `commonOptions` does not work with `vue`

### ISSUE THREAD

**Issue by ayangweb** [BuilderIO/mitosis#1257]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [x] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

No link

### Expected Behaviour

```js
commonOptions: {
  typescript: true,
},
options: {
  vue2: { api: 'composition' },
  vue3: { api: 'composition' },
},
```

### Actual Behaviour

```js
commonOptions: {
  typescript: true,
},
options: {
  vue2: { api: 'composition', typescript: true },
  vue3: { api: 'composition', typescript: true },
},
```

The latest version works with `react`, `solid`, `preact`, etc., but not for `vue`!

**Comment by ayangweb** [comment]
After testing, `Svelte` doesn't work either!

**Comment by samijaber** [comment]
I am not able to reproduce when I test this on the latest version of mitosis. If I set:

```
commonOptions: {
    typescript: true,
  }
```

in my `mitosis.config.js`, then that applies to al generators. It is worth noting that targets can _override_ this on a per-target basis:

```
commonOptions: {
    typescript: true,
  },
options: {
  vue2: { typescript: false }
}
```

in this case, vue2 will override it and have `typescript === false`.
