### ISSUE TITLE
Wrong mapping of `change` and `input` events for `HTMLInputElement` for vue

### ISSUE THREAD

**Issue by ohkimur** [BuilderIO/mitosis#1263]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFAT0AD0iw4bEjmRN4JZADsAxjG6a4AWQCeAYQqRN6TTAAUYcmFQBKRBLhxtETangBtTRwQdAAaOAwYADkg9ABdOABeFAxsPHRbKmx0ADd0KmdJdzgodBhkKANbIo8AHhZgbIA%2Bao84GuBNMGQYFtbPVFQEhARevs8IJmgALmoSlioQ0Y9CQiW4bJwmZHQhwODVsdbvAElO7qHbHOsYVwTG8NLo4Mvcmw5cKABzUo4NrfRnAdDnBvKYABY4TTfC5XGy3e4RJ7pWEwd44L4%2FP7bQGjHjNQ4ACXQTEmAEI4MdPJDilo4B04AAldA4XRhABq2zCmAmwBYYWgcAAMsAAI6MFiklo1Hj1JpFAoSQhAA

### Expected Behaviour

When both `onInput` and `onChange` events are present on HTMLInputElement, they should be both properly mapped to their counterparts on `vue`, respectively `input` and `change`.

This input:
```tsx
import { useState } from "@builder.io/mitosis";

export default function MyComponent(props) {
  const [name, setName] = useState("Steve");

  return (
    <div>
      <input
        css={{
          color: "red",
        }}
        value={name}
        onInput={(event) => setName(event.target.value)}
        onChange={(event) => setName(event.target.value)}
      />
      Hello! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}
```

should be compiled to:

```tsx
<template>
  <div>
    <input
      class="input"
      :value="name"
      @input="name = $event.target.value"
      @change="name = $event.target.value"
    />
    Hello! I can run in React, Vue, Solid, or Liquid!
  </div>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "my-component",

  data() {
    return { name: "Steve" };
  },
});
</script>

<style scoped>
.input {
  color: red;
}
</style>
```

### Actual Behaviour

This input:
```tsx
import { useState } from "@builder.io/mitosis";

export default function MyComponent(props) {
  const [name, setName] = useState("Steve");

  return (
    <div>
      <input
        css={{
          color: "red",
        }}
        value={name}
        onInput={(event) => setName(event.target.value)}
        onChange={(event) => setName(event.target.value)}
      />
      Hello! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}
```

compiles to:

```tsx
<template>
  <div>
    <input
      class="input"
      :value="name"
      @input="name = $event.target.value"
      @input="name = $event.target.value"
    />
    Hello! I can run in React, Vue, Solid, or Liquid!
  </div>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "my-component",

  data() {
    return { name: "Steve" };
  },
});
</script>

<style scoped>
.input {
  color: red;
}
</style>
```

### Additional Information

<img width="1275" alt="image" src="https://github.com/BuilderIO/mitosis/assets/22911281/c813f58a-1ec2-44b3-8809-460be6ab8d52">

**Comment by steve8708** [comment]
interested in contributing @ohkimur ? would love a PR to fix this

**Comment by steve8708** [comment]
just saw you opened one, lgtm! Sami is currently away on parental leave for a few weeks, if this isn't urgent will let him merge and publish when he is back
