### ISSUE TITLE
SolidJS: mitosis compiles the attribute "for" to "htmlFor"

### ISSUE THREAD

**Issue by kauderk** [BuilderIO/mitosis#1319]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [X] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=M4ewNglgJkA%3D&code=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnALICeAwhALaR7B4wAUYUEYAzgFxwA3nGIIBPGFGJ4A5nAC%2BASiEAoOHCjAY6KOQA8mVACNgmOMmgBeQQHJDJzDfkA%2BW%2FdNO9AeneZnAbhV5FSA

### Expected Behaviour

the "for" attribute shouldn't compile to "htmlFor"

### Actual Behaviour

 I know it's a small issue but I guess mitosis has to adapt to all the frameworks changes
https://github.com/solidjs/solid/releases/tag/v1.4.0#:~:text=className%2C%20htmlFor%20deprecated

### Additional Information

Maybe mitosis should accept version targets

**Comment by samijaber** [comment]
Just gotta remove this mapping!

https://github.com/BuilderIO/mitosis/blob/e862056eca675887bd975bf5696c61666d0f3532/packages/core/src/generators/solid/blocks.ts#L13

**Comment by JerryWu1234** [comment]
let me try this
