### ISSUE TITLE
Support for custom generators / targets

### ISSUE THREAD

**Issue by commax89** [BuilderIO/mitosis#1322]
### I am interested in helping provide a feature!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### What problem does this feature solve?

Some projects may need to customize, rewrite or write generators from scratch in order to achieve some specific business requirements that are not compatible with current coding standards.

### What does the proposed API look like?

From an initial high level investigation it should be possibile to load custom targets directly from the config file, in the cli package it should be enough to merge the current targets with the ones from the options. This should also enable generator replacements.

**Comment by samijaber** [comment]
I'm open to adding this! How to do so:

- Add a `generators` dictionary prop to the `MitosisConfig`:
https://github.com/BuilderIO/mitosis/blob/e862056eca675887bd975bf5696c61666d0f3532/packages/core/src/types/config.ts#L19

- Update this call to take into account `options.generators`, by checking for `options.generators[target]` before relying on the default generators:
https://github.com/BuilderIO/mitosis/blob/e862056eca675887bd975bf5696c61666d0f3532/packages/cli/src/build/build.ts#L278

**Comment by JerryWu1234** [comment]
I will do it
