### ISSUE TITLE
Sveltosis doesn't work on Fiddle

### ISSUE THREAD

**Issue by effulgentsia** [BuilderIO/mitosis#1327]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io

### Expected Behaviour

On https://mitosis.builder.io/, I expect to click on the Sveltosis tab for the Input, choose a template, such as TextExpressions (or any other one), then click on the React (or any other) tab for the Output, and see the Svelte code in the left pane transformed into React code in the right pane.

### Actual Behaviour

The output pane shows only the transformation of whatever was last entered in the input pane when the Mitosis JSX tab was last selected. It seems to ignore the fact that the Sveltosis tab is selected.

**Comment by samijaber** [comment]
Fixed in #1419
