### ISSUE TITLE
Not Compiling yo other stack 

### ISSUE THREAD

**Issue by yhoungdev** [BuilderIO/mitosis#141]
#### It doesn't compile the code to other frameworks/ languages when I try to edit mine

**Comment by steve8708** [comment]
hey @yhoungdev - could you elaborate on your issue, such as what steps you took and how to reproduce?

**Comment by markhughes** [comment]
@yhoungdev could you put your code into a github repo for us to see? This way we can understand the issue and help :)

**Comment by samijaber** [comment]
Closing as there is no reproduction step. Please create a new issue if this re-surfaces
