### ISSUE TITLE
variable is ignored when compiled into other framework

### ISSUE THREAD

**Issue by SmallStoneSK** [BuilderIO/mitosis#145]
Hi, I tried a simple demo as following, but I found the declaration of variable `title` is ignored.

![image](https://user-images.githubusercontent.com/17713870/144345319-40ad2df9-a2a3-43ae-a6cc-2af384cc314c.png)

**Comment by mtoksen** [comment]
@SmallStoneSK It seems to me that the reason why the `title` variable is ignored is that you didn't set it as a state in Mitosis. It works fine for me when I do it like this:
![image](https://user-images.githubusercontent.com/58517050/145169563-d592b617-a74f-4d1c-b8d0-83d117a5ecf0.png)

**Comment by SmallStoneSK** [comment]
@mtoksen 

Yes, but I think it's not good to set all variables as states. If you create a state, it will be kept in memory until the component instance unmounts.

**Comment by steve8708** [comment]
@mtoksen is correct - in order to have parity across frameworks state is required, as not every framework is functional like react (e.g. there is no comparable construct of a variable in the render pipeline for Angular, SolidJS, Vue SFC, etc). you can have variables within functions and getters of course though

**Comment by steve8708** [comment]
what we really need here is more eslint rules to warn that this will be ignored, and link to more documentation

on the todo list :)

**Comment by PatrickJS** [comment]
I think this should be supported. I think the goal is better just to have anyone familiar with react api to easily create components for every framework

**Comment by samijaber** [comment]
Closing this issue, given that we have no plans in the short/medium-term to provide a way to set variables in the render body.

There is an ESLint rule now warning you against doing this: https://github.com/BuilderIO/mitosis/blob/main/packages/eslint-plugin/docs/rules/no-var-declaration-or-assignment-in-component.md

**Comment by PatrickJS** [comment]
So we've worked around this. If you use useRef its basically the same thing. For anyone wondering

**Comment by KevinEdry** [comment]
> So we've worked around this. If you use useRef its basically the same thing. For anyone wondering

can you give an example?
