### ISSUE TITLE
Hook onUnMount is ignored

### ISSUE THREAD

**Issue by i-kostyakov** [BuilderIO/mitosis#146]
Hi all!
It's a very interesting project.

And I found a bug. [onUnMount](https://github.com/BuilderIO/mitosis/blob/main/docs/overview.md#onunmount) hook is ignored by code.

[Example](https://mitosis.builder.io/?outputTab=vue&code=import+%7B+useState%2C+onMount%2C+onUnMount+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+state+%3D+useState%28%7B+name%3A+%22Steve%22+%7D%29%3B%0A%0A++onMount%28%28%29+%3D%3E+%7B%0A++++console.log%28%22EHEHHE%21%22%29%3B%0A++%7D%29%3B%0A++onUnMount%28%28%29+%3D%3E+%7B%0A++++console.log%28%22ret%21%22%29%3B%0A++%7D%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3Cinput%0A++++++++value%3D%7Bstate.name%7D%0A++++++++onChange%3D%7B%28event%29+%3D%3E+%28state.name+%3D+event.target.value%29%7D%0A++++++++css%3D%7B%7B%0A++++++++++color%3A+%22red%22%2C%0A++++++++%7D%7D%0A++++++%2F%3E%0A++++++%3Cspan%3EHello%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%3C%2Fspan%3E%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D%0A)

**Comment by Ghostpaid** [comment]
Can I get more information on this

**Comment by i-kostyakov** [comment]
> Can I get more information on this

Yes, of course! What you need?
In linked example we can see onMount and onUnMount on the left side and only mounted (for vue) on the right side.

for others output frameworks result the same 

I singled out that on the picture
![image](https://user-images.githubusercontent.com/35257530/145035517-c6888e78-d6a2-448f-abb2-c846240cde44.png)
