### ISSUE TITLE
Wrong mapping of change and input events for HTMLInputElement

### ISSUE THREAD

**Issue by bastiW** [BuilderIO/mitosis#1484]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [X] Stencil
- [X] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/playground/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFAT0AD0iw4bEjmRN4JZADsAxjG6a4AWQCeAYQqRN6TTAAUYcmFQBKRBLhxtETangBtTRwQdAAaOAwYADkg9ABdOABeFAxsPHRbKmx0ADd0KmdJdzgodBhkKANbIo8AHhZgbIA%2Bao84GuBNMGQYFtbPVFQEhARevs8IJmgALmoSlioQ0Y9CQiW4bJwmZHQhwODVsdbvAElO7qHbHOsYVwTG8NLo4Mvcmw5cKABzUo4NrfRnAdDnBvKYABY4TTfC5XGy3e4RJ7pWEwd44L4%2FP7bQGjHjNQ4ACXQTEmAEI4MdPJDilo4B04AAldA4XRhABq2zCmAmwBYYWgcAAMsAAI6MFiklo1Hj1JpFAoSQhAA

### Expected Behaviour

When both onInput and onChange events are present on HTMLInputElement, they should be both properly mapped to the correct change event

### Actual Behaviour

is always compiled to the input event.

### Additional Information

Follow up of https://github.com/BuilderIO/mitosis/issues/1263

- On solid I am not sure if they have a change event
- Web components & HTML not tested because they have no playground

**Comment by JerryWu1234** [comment]
I'll check this problem

**Comment by JerryWu1234** [comment]
![image](https://github.com/user-attachments/assets/faa2acae-235e-4773-a91f-63ba99b237b4)

@bastiW Could you tell me more about this？ I‘n not totally understand

**Comment by bastiW** [comment]
The mapping from onChange to (change) does not happen with angular, stencil and svelte. 

Currently: onChange maps to (input) 
Should: onChange maps to (change)

![image](https://github.com/user-attachments/assets/8d4fadd9-c4f3-421f-9a5a-6a29abe59b53)

**Comment by nmerget** [comment]
@bastiW 

Are you sure that `svelte` has the same issue?

I don't have any experiance with svelete but I think [onChange](https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/generators/svelte/svelte.ts#L121-L128) will be a special case.

Web components and lit are affected as well.
