### ISSUE TITLE
HTML Output for JSX doesn't render text

### ISSUE THREAD

**Issue by jackmaders** [BuilderIO/mitosis#1496]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [X] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

No HTML output Available

### Expected Behaviour

HTML output files should correctly handle changing state from JSX.

Create a JSX component with some state from `useState`, and render it into the markdown. Build the component into an HTML file and load the file on a browser. The value of the state should be visible on the page and updated with the state.

Example component from starter project
```jsx
import { useStore } from "@builder.io/mitosis";

export default function Greet() {
  const state = useStore({
    name: "",
  });

  return (
    <div>
      <input
        value={state.name}
        onChange={(event) => (state.name = event.target.value)}
        placeholder="Your name"
      />
      <div>Hello, {state.name}!</div>
    </div>
  );
}
```

### Actual Behaviour

The value from useState is not rendered on the page. The value is used in other places within the HTML (e.g. used to set the CSS of an element), but will not display as text in the HTML.

### Additional Information

From a brief play around with the output file, it seems like an issue with the `renderTextNode` function.

The function is:
- creating a new element for the text node
- mounting it after the old element
- deleting the next sibling of the old element (which is the new element)

If you update the function from `nodesToDestroy.push(el.nextSibling);` to `nodesToDestroy.push(textNode.nextSibling);`, everything seems to update correctly.

**Comment by samijaber** [comment]
@jackmaders sounds like you have a good idea of what the fix is: PRs welcome!
