### ISSUE TITLE
Children prop is broken on Angular

### ISSUE THREAD

**Issue by seasheepjoe** [BuilderIO/mitosis#1580]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/playground/?code=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnALICeAwhALaR7B4wAUYUEYAzgJRwA3gCg4cKMBjoo5NqLFwAPAmIA3AHzyFSgGLQ4wVAQAWAXkGduPAHQnimBBLwBfTdrGC2dhwBo4xPCQQAVN1ODl3BWU1dUFvBGdFAHoVDS0FPmd0sWS9KDcolJj5PgBuYWcgA%3D%3D

### Expected Behaviour

With this simple code, it should render the same as the React component.

### Actual Behaviour

However, in an angular test-app, the compiler fails to compile because the children prop is undefined.

### Additional Information

The screenshot below shows the compilation error.
<img width="722" alt="Screenshot 2024-10-03 at 13 03 41" src="https://github.com/user-attachments/assets/6a6ddd72-f1c8-4059-9e8b-6a705d341282">
Maybe I am using the children prop wrong ?

**Comment by samijaber** [comment]
`props.children` is indeed a special prop. You can only use it by rendering it like `<div>{props.children}</div>`. Many frameworks are unable to manipulate the prop and iterate on it.

We should improve our docs to mention this, but it is _not_ possible to iterate over the `children` dynamically like you are trying to do in your example.

**Comment by seasheepjoe** [comment]
Oh ok I see, thanks for the quick reply. I would love to contribute to the docs :D

**Comment by samijaber** [comment]
Go for it! You can add a note here: https://mitosis.builder.io/docs/components/#children

https://github.com/BuilderIO/mitosis/blob/main/packages/docs/src/routes/docs/components/index.mdx#children

**Comment by seasheepjoe** [comment]
Hi! I made a PR to include the note in the docs 😄
https://github.com/BuilderIO/mitosis/pull/1600
