### ISSUE TITLE
Example with correct TS lib

### ISSUE THREAD

**Issue by Tymek** [BuilderIO/mitosis#162]
How to configure TS? When creating `<div css={{}} />` I get an error:
`Type '{ children: Element[]; css: { padding: string; }; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Property 'css' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.`

I tried for example importing this with no effect:
```ts
/// <reference types="@builder.io/mitosis/dist/src/jsx-types" />
```

Maybe I'm missing something. Thx in advance 😅

**Comment by steve8708** [comment]
hey @Tymek - can you paste your full code file example? it looks like those are the react typings (or similar), so if the imports anything from react those may override the mitosis ones

**Comment by Tymek** [comment]
https://codesandbox.io/s/blissful-paper-4busx?file=/src/testfile.tsx

(wait couple of seconds until TS loads, 
![image](https://user-images.githubusercontent.com/2625371/150569297-c0e1ce3e-e869-425e-838d-36724697f596.png)
)

**Comment by steve8708** [comment]
Super helpful reproduction, thanks for sharing!

If you remove anything react related from that project, it works as expected: https://codesandbox.io/s/young-rgb-ql03s?file=/src/testfile.tsx

![image](https://user-images.githubusercontent.com/844291/150570060-b768326f-7284-4c92-acaa-d14b347ee7ec.png)

**Comment by Tymek** [comment]
oh, ok! I get it. `"compilerOptions" > "jsx": "preserve"` 👍🏻
