### ISSUE TITLE
Mitosis Quickstart button does not work with react-native button

### ISSUE THREAD

**Issue by NickersWeb** [BuilderIO/mitosis#1646]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [X] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/playground/?code=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnAMLoDOMEAtgELox14AUAlHAN4BQcOFGAx0UcgB4ARizZwyFTMQIBrALw8ucNQD44BMtQiZgAOkwQA5uwBEMYLRucAvjoCCCBBID0M1mR0Abj5nPiA%3D

### Expected Behaviour

That react-native output should have no bugs for a simple Mitosis button.

### Actual Behaviour

Following this guide: [https://mitosis.builder.io/docs/quickstart/](https://mitosis.builder.io/docs/quickstart/).

react-native output does not match the related playground link. 

Instead, it creates the following: 

```
import {
  FlatList,
  ScrollView,
  View,
  StyleSheet,
  Image,
  Text,
  Pressable,
  TextInput,
  TouchableOpacity,
  Button,
  Linking,
} from "react-native";

function CustomButton(props: any) {
  return (
    <Button onPress={(event) => console.log("test")}>
      <Text>Add</Text>
    </Button>
  );
}

export default CustomButton;
```
It should use `Pressable` instead.

### Additional Information

```
/**
 * @type {import('@builder.io/mitosis').MitosisConfig}
 */
module.exports = {
  files: "src/**",
  targets: ["react", "reactNative"],
  dest: "packages",
  commonOptions: {
    typescript: true,
  },
  options: {
    react: {
      stylesType: "style-tag",
    },
    reactNative: {},
    svelte: {},
    qwik: {},
  },
};

```

**Comment by samijaber** [comment]
This was due to the playground using an outdated version of mitosis. it now has been updated to match the latest published npm package of mitosis, which does use `<Button>` instead of `Pressable`.
