### ISSUE TITLE
Fragment 'key' attribute is not used in react output

### ISSUE THREAD

**Issue by lukjab71** [BuilderIO/mitosis#1648]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [X] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/playground/?code=JYWwDg9gTgLgBAbzgMWgGhVAhgcxAUwDt4BfOAMyghDgHIABAIwFdgAbAE3ygDpgIA9CGAwIAZ2BjaAbgBQsgMYRCY%2BDHyq4AXjgBtAERZ9GfY2Nx9C%2FQF05s%2FAA9IsOF3JZmbeOWaEFMfkI4ACEsCQVUKGRsPCIYAAoASkRZODgofBhmKCD41LS4AB4OYAA3AD58gqLIuHwsBQALLQRdWixaDFpGTroFWmsSSurqhHiIMADlZK1yuDyRkcLo3AJiOABrfABPFoADLe2AWgASBAmpwhI9oarFgsKxMCxCcvPJwJJCgSeX4fu0t8VrFiP9FokSHdAQJIpUoTVoHUGs0EOpVLcAWMLoEMMBCFwHDM5gsATUYmt4IcWniCRjSWl3pdIfSgeS4mCRhD4UDoBzviUKvlEnISEA%3D%3D%3D

### Expected Behaviour

As per docs:

``The Fragment component accepts the key prop, which is typically used when the Fragment is the direct child of a For loop component.``

However this has no effect on the output code. I would expect that using key in Fragment would result in following output in react: 

`<Fragment key={yourKey}>
 ....
</Fragment>`, otherwise, what's the point of using key in the mitosis jsx? 

### Actual Behaviour

Mitosis either drops the fragment completely from output or outputs fragment in short syntax, which does not give us possibility to use the key attribute:

`      {test?.map((option, index) => (
        <>{option}</>
      ))}`

**Comment by samijaber** [comment]
This is an issue with our playground not using the latest version of mitosis. I just updated it to the latest version and the output for react is now:

```tsx
import * as React from "react";

const test = ["a", "b", "c"];

function BasicForFragment(props) {
  return (
    <div>
      {["a", "b", "c"]?.map((option) => (
        <React.Fragment key={`key-${option}`}>
          <span>{option}</span>
        </React.Fragment>
      ))}
      {test?.map((option, index) => (
        <React.Fragment key={index}>{option}</React.Fragment>
      ))}
    </div>
  );
}

export default BasicForFragment;
```
