### ISSUE TITLE
Eslint rules

### ISSUE THREAD

**Issue by steve8708** [BuilderIO/mitosis#174]
Mitosis needs a decent amount of constraints given the amount of targets it needs to support. This can make for a very clunky DX if you don't get real time feedback on what is allowed vs not

We have started on an eslint plugin [here](https://github.com/BuilderIO/mitosis/tree/main/packages/eslint-plugin) but it could use a lot more checks in it

**Comment by sahilmob** [comment]
Is there any reference for those rules, so we know what to implement?

**Comment by steve8708** [comment]
@sahilmob ah yes, two things! 

This is a great place to start: https://github.com/BuilderIO/mitosis/blob/main/docs/overview.md#gotchas-and-limitations

I also share a bunch of random stuff in here, I hope it is helpful: https://www.loom.com/share/78fe319ab592433aa637d1963e35eff3

**Comment by sahilmob** [comment]
@steve8708 Thanks for the excellent explaination. It looks exciting and challenging at the same time. I'll start implementing them one by one.

**Comment by sahilmob** [comment]
Part 1 just got merged yesterday, and I'm currently working on part2.

**Comment by samijaber** [comment]
@sahilmob are there any other eslint rules on your list to get in? If not, I'm happy to close this issue as you've created an amazing amount already :)

**Comment by sahilmob** [comment]
@samijaber I think that I've covered all the cases that Steve provided, so feel free to close this issue. 🚀 🚀 🚀

**Comment by samijaber** [comment]
Closed by #180  and #218
