### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by steve8708** [BuilderIO/mitosis#176]
More docs around how to get started, the mental model to have, workflows, and constraints to be mindful of will go a long way to helping people adopt and use this project

**Comment by dcerniglia** [comment]
I would like to help with docs.

**Comment by samijaber** [comment]
@dcerniglia If you are still interested, here is a sub-task of the Docs issue we have that we need to work on: #228

**Comment by samijaber** [comment]
Docs are in better shape now, can close this and open specific tickets for missing docs later
