### ISSUE TITLE
Missing "index" in React output when using "For"

### ISSUE THREAD

**Issue by edolix** [BuilderIO/mitosis#181]
Hey there! This project looks _amazing_ ❤️ !

Trying it out i see that the React output with `For` is missing the `index` argument. See [this test Fiddle](https://mitosis.builder.io/?outputTab=react&code=import+%7B+useState%2C+For+%7D+from+%27%40builder.io%2Fmitosis%27%0A%0Aexport+default+function+List%28%29+%7B%0A++const+state+%3D+useState%28%7B%0A++++myArray%3A+%5B1%2C+2%2C+3%5D%2C%0A++++list%3A+%5B%27hello%27%2C+%27world%27%5D%2C%0A++%7D%29%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3CFor+each%3D%7Bstate.myArray%7D%3E%0A++++++++%7B%28theArrayItem%2C+index%29+%3D%3E+%3Cdiv+key%3D%7Bindex%7D%3E%7BtheArrayItem%7D%3C%2Fdiv%3E%7D%0A++++++%3C%2FFor%3E%0A++++%3C%2Fdiv%3E%0A++%29%0A%7D%0A).

Note: this is for testing purposes only, i know that using `key={index}` is a bad idea but it's enough to see the issue.

> Input

```ts
import { useState, For } from '@builder.io/mitosis'

export default function List() {
  const state = useState({
    myArray: [1, 2, 3],
    list: ['hello', 'world'],
  })

  return (
    <div>
      <For each={state.myArray}>
        {(theArrayItem, index) => <div key={index}>{theArrayItem}</div>}
      </For>
    </div>
  )
}
```

> React Output

```ts
import { useState } from "react";

export default function List(props) {
  const [myArray, setMyArray] = useState(() => [1, 2, 3]);

  const [list, setList] = useState(() => ["hello", "world"]);

  return (
    <div>
      {myArray?.map((theArrayItem) => (
        <div key={index}>{theArrayItem}</div>
      ))}
    </div>
  );
}

```

**Comment by samijaber** [comment]
@edolix Thanks for raising this issue! We have noticed this bug internally as well. I appreciate the simple test-case, that makes it easier to reproduce. 👍🏽 

A PR contribution to fix this issue would be welcome if you're feeling up for it!
