### ISSUE TITLE
Are there any plans for `lite.tsx`?

### ISSUE THREAD

**Issue by sramam** [BuilderIO/mitosis#182]
The project looks really promising. 
Wondering if there are plans for `lite.tsx`?

**Comment by samijaber** [comment]
@sramam I don't fully understand your question. Mitosis is under active development at the moment. What do you mean by "plans for `lite.tsx`"?

**Comment by sramam** [comment]
I didn't choose my words carefully. 
Thanks for taking the time to respond despite my failings.

There are two issues that would be really cool to have:
1. types for the props and state.
2. ability to add code within the component (with the implicit assumption that they maintain the purity of the parent component)

The code segment below demonstrates both these and is not valid JSXLite today.
```
import { useState } from "@builder.io/mitosis";

type Props = {
  name: String;
}
export default function MyComponent(props: Props) {
  const [name, setName] = useState(props.name);

  const delay = (fn) => setTimeout(fn, 1000);

  return (
    <div>
      <input
        css={{
          color: "red",
        }}
        value={name}
        onChange={(event) => delay(() => setName(event.target.value))}
      />
      Hello! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}
```

I understand that you likely can't support arbitrary code in the component. 
But something like local variables, local functions and other hooks might transpose across frameworks?

Or am I only putting my foot further into my mouth?!

**Comment by steve8708** [comment]
hey @sramam - you can have local functions, you can do [this](https://mitosis.builder.io/?outputTab=vue&code=import+%7B+useState+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+%5Bname%2C+setName%5D+%3D+useState%28%22%22%29%3B%0A%0A++function+delay%28fn%29+%7B%0A++++setTimeout%28fn%2C+1000%29%3B%0A++%7D%0A%0A++function+getName%28%29+%7B%0A++++return+name+%7C%7C+props.name%3B%0A++%7D%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3Cinput%0A++++++++css%3D%7B%7B%0A++++++++++color%3A+%22red%22%2C%0A++++++++%7D%7D%0A++++++++value%3D%7BgetName%28%29%7D%0A++++++++onChange%3D%7B%28event%29+%3D%3E+delay%28%28%29+%3D%3E+setName%28event.target.value%29%29%7D%0A++++++%2F%3E%0A++++++Hello%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D):

```tsx
import { useState } from "@builder.io/mitosis";


export default function MyComponent(props) {
  const [name, setName] = useState("");

  function delay(fn) {
    setTimeout(fn, 1000);
  }

  function getName() {
    return name || props.name;
  }

  return (
    <div>
      <input
        css={{
          color: "red",
        }}
        value={getName()}
        onChange={(event) => delay(() => setName(event.target.value))}
      />
      Hello! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}
```

Note that you also, at this time, can't set state defaults via props. We may be able to add support for this ultimately though

**Comment by sramam** [comment]
ah. I missed that on the first blush. Thank you.
Any plans for adding types?

**Comment by steve8708** [comment]
ah ya sorry [types are all good](https://mitosis.builder.io/?outputTab=vue&code=import+%7B+useState+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Atype+Props+%3D+%7B%0A++name%3A+String%3B%0A%7D%0A%0Aexport+default+function+MyComponent%28props%3A+Props%29+%7B%0A++const+%5Bname%2C+setName%5D+%3D+useState%28%22%22%29%3B%0A%0A++function+delay%28fn%29+%7B%0A++++setTimeout%28fn%2C+1000%29%3B%0A++%7D%0A%0A++function+getName%28%29+%7B%0A++++return+name+%7C%7C+props.name%3B%0A++%7D%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3Cinput%0A++++++++css%3D%7B%7B%0A++++++++++color%3A+%22red%22%2C%0A++++++++%7D%7D%0A++++++++value%3D%7BgetName%28%29%7D%0A++++++++onChange%3D%7B%28event%29+%3D%3E+delay%28%28%29+%3D%3E+setName%28event.target.value%29%29%7D%0A++++++%2F%3E%0A++++++Hello%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D)! 

```tsx
import { useState } from "@builder.io/mitosis";

type Props = {
  name: String;
}

export default function MyComponent(props: Props) {
  const [name, setName] = useState("");

  function delay(fn) {
    setTimeout(fn, 1000);
  }

  function getName() {
    return name || props.name;
  }

  return (
    <div>
      <input
        css={{
          color: "red",
        }}
        value={getName()}
        onChange={(event) => delay(() => setName(event.target.value))}
      />
      Hello! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}
```

**Comment by steve8708** [comment]
also our fault for lack of docs :D - is on our roadmap to flesh out more

**Comment by sramam** [comment]
Oh wow! that is so cool!

The red squigglies on the left side threw me off and I didn't think it through. 
The transpilation output is js, so should not have expected types there. 

Will be exploring using mitosis (a bit too excitedly for my own good!)

Nice work!

**Comment by steve8708** [comment]
Great to hear @sramam !

**Comment by steve8708** [comment]
Also, if you are interested in contributing, this could be a great contribution to make! https://github.com/BuilderIO/mitosis/issues/183#issue-1149596537
