### ISSUE TITLE
Fix the fiddle to support Typescript types

### ISSUE THREAD

**Issue by steve8708** [BuilderIO/mitosis#183]
We support TSX, yet the Fiddle puts little red squiggles on the fiddle code editor suggesting types are not supported. It may be as simple as specifying the language as "TSX" instead of "JSX" for the code editor

**Comment by steve8708** [comment]
Looking at the code, it seems we are passing `language="typescript"` to [Monaco](https://github.com/BuilderIO/mitosis/blob/main/packages/fiddle/src/components/CodeEditor.tsx#L138), but perhaps the highlights are coming from eslint, it appears we are [not telling eslint that this is typescript](https://github.com/BuilderIO/mitosis/blob/main/packages/fiddle/src/components/CodeEditor.tsx#L68-L73) but perhaps should

**Comment by sramam** [comment]
two questions: 

## `yarn start` errors:
```
git clone https://github.com/BuilderIO/mitosis
yarn install
cd packages/fiddle
yarn start
```
Throws this error on the console 

```
Failed to compile.

/private/tmp/mitosis/node_modules/@ampproject/remapping/dist/remapping.mjs
Can't import the named export 'TraceMap' from non EcmaScript module (only default export is available)
```

And I am seeing pref_hooks and process not found errors in the console.

## Is this the piece of code to modify?
I actually haven't configured a monaco editor before - wondering if [this is the right place](https://github.com/sramam/mitosis/blob/main/packages/fiddle/src/components/CodeEditor.tsx#L39) to make a change:

**Comment by steve8708** [comment]
awesome. apologies for us having poor docs on how to get started. try this:

```
git clone https://github.com/BuilderIO/mitosis
npm install
cd packages/fiddle
npm install
npm start
```

re: is that the code to modify, definitely worth a try!

**Comment by sramam** [comment]
Ah. 

Sorry - I'm full of complaints today - Another [thing to fix then](https://github.com/BuilderIO/mitosis/blob/main/package.json#L9)

**Comment by steve8708** [comment]
ha! great catch. would be great to include deleting that in a PR

**Comment by sramam** [comment]
```
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
❯ pwd
/private/tmp/mitosis
❯ npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @builder.io/mitosis-cli@0.0.11
npm ERR! Found: parse5@3.0.3
npm ERR! node_modules/parse5
npm ERR!   parse5@"^3.0.3" from @builder.io/mitosis-cli@0.0.11
npm ERR!   packages/cli
npm ERR!     @builder.io/mitosis-cli@0.0.11
npm ERR!     node_modules/@builder.io/mitosis-cli
npm ERR!       workspace packages/cli from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer parse5@"^2.1.0" from vue-template-validator@1.1.5
npm ERR! node_modules/vue-template-validator
npm ERR!   vue-template-validator@"^1.1.5" from @builder.io/mitosis-cli@0.0.11
npm ERR!   packages/cli
npm ERR!     @builder.io/mitosis-cli@0.0.11
npm ERR!     node_modules/@builder.io/mitosis-cli
npm ERR!       workspace packages/cli from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/sramam/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sramam/.npm/_logs/2022-02-24T21_01_59_582Z-debug.log
```

**Comment by sramam** [comment]
```
❯ npm -v
7.19.1
❯ node -v
v16.5.0
```

**Comment by steve8708** [comment]
ah we should add an nvmrc file and versions stuff. thanks for baring with us as we make these improvements. I currently use

```
➜ npm -v
6.14.15
➜ node -v
v14.17.6
```

can you try with those?

**Comment by samijaber** [comment]
Ah, duplicated this in #529. Closing in favor of the new one
