### ISSUE TITLE
Mitosis refs do not work when you compile to Vue

### ISSUE THREAD

**Issue by JLarky** [BuilderIO/mitosis#186]
I tried to run your "Methods and Refs" example code on playground [the link](https://mitosis.builder.io/?outputTab=vue&code=import+%7B+useState%2C+useRef+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+%5Bname%2C+setName%5D+%3D+useState%28%22Steve%22%29%3B%0A%0A++function+onBlur%28%29+%7B%0A++++%2F%2F+Maintain+focus%0A++++inputRef.current.focus%28%29%3B%0A++%7D%0A%0A++function+lowerCaseName%28%29+%7B%0A++++return+name.toLowerCase%28%29%3B%0A++%7D%0A%0A++const+inputRef+%3D+useRef%28%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%7Bprops.showInput+%26%26+%28%0A++++++++%3C%3E%0A++++++++++%3Cinput%0A++++++++++++ref%3D%7BinputRef%7D%0A++++++++++++css%3D%7B%7B%0A++++++++++++++color%3A+%22red%22%2C%0A++++++++++++%7D%7D%0A++++++++++++value%3D%7Bname%7D%0A++++++++++++onBlur%3D%7B%28event%29+%3D%3E+onBlur%28%29%7D%0A++++++++++++onChange%3D%7B%28event%29+%3D%3E+setName%28event.target.value%29%7D%0A++++++++++%2F%3E%0A++++++++%3C%2F%3E%0A++++++%29%7D%0A++++++Hello%0A++++++%7BlowerCaseName%28%29%7D%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D) and compiled it to Vue. The problem is that refs in Vue don't have `".current"` :) but if I change to be just `inputRef.focus();` it works [the link](https://mitosis.builder.io/?outputTab=vue&code=import+%7B+useState%2C+useRef+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+%5Bname%2C+setName%5D+%3D+useState%28%22Steve%22%29%3B%0A%0A++function+onBlur%28%29+%7B%0A++++%2F%2F+Maintain+focus%0A++++inputRef.focus%28%29%3B%0A++%7D%0A%0A++function+lowerCaseName%28%29+%7B%0A++++return+name.toLowerCase%28%29%3B%0A++%7D%0A%0A++const+inputRef+%3D+useRef%28%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%7Bprops.showInput+%26%26+%28%0A++++++++%3C%3E%0A++++++++++%3Cinput%0A++++++++++++ref%3D%7BinputRef%7D%0A++++++++++++css%3D%7B%7B%0A++++++++++++++color%3A+%22red%22%2C%0A++++++++++++%7D%7D%0A++++++++++++value%3D%7Bname%7D%0A++++++++++++onBlur%3D%7B%28event%29+%3D%3E+onBlur%28%29%7D%0A++++++++++++onChange%3D%7B%28event%29+%3D%3E+setName%28event.target.value%29%7D%0A++++++++++%2F%3E%0A++++++++%3C%2F%3E%0A++++++%29%7D%0A++++++Hello%0A++++++%7BlowerCaseName%28%29%7D%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D).

I first discovered that when I was using cli, but I see the same issue on the playground :)

<sub>you can also see it here https://youtu.be/mitz2leHqoE?t=4284 at about 1:11:24</sub>

**Comment by sahilmob** [comment]
@steve8708 Looks like this needs to be changed to `inputRef.blur()` instead of `inputRef.current.blur()` for all frameworks/libraries other than React.

**Comment by steve8708** [comment]
ah, yes! looking deeper, it's actually the example code that is broken. mitosis refs don't expect you to use .current, and instead adds that for react specifically. I can send PR for this

currently refs are unhandled for HTML output, so will need to add support for that separately

**Comment by sahilmob** [comment]
If that's the case, we should consider adding an eslint rule for it.

**Comment by steve8708** [comment]
@sahilmob great idea!

**Comment by tomByrer** [comment]
I think I need to use refs for Web Animation API, since the plain HTML usage is via element method?

https://developer.mozilla.org/en-US/docs/Web/API/Element/animate#examples
