### ISSUE TITLE
Support reading generator options from `mitosis.config.js` in `mitosis compile`

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#199]
Similar to how `mitosis build` works: it imports `getMitosisConfig()` and then override defaults:

https://github.com/BuilderIO/mitosis/blob/76bcc9732e213b7e736ee05117e66b5c40c8e787/packages/cli/src/commands/build.ts#L9
https://github.com/BuilderIO/mitosis/blob/76bcc9732e213b7e736ee05117e66b5c40c8e787/packages/cli/src/build/build.ts#L28-L55

Place to apply changes for `mitosis compile`: 

https://github.com/BuilderIO/mitosis/blob/76bcc9732e213b7e736ee05117e66b5c40c8e787/packages/cli/src/commands/compile.ts#L24-L27

**Comment by alujs** [comment]
I'll take this.

**Comment by alujs** [comment]
Putting a temporary hold on this, I'll pick it back up if it still hasn't been taken.

**Comment by sahilmob** [comment]
I would love to work on this task if nobody is currently on it!

I noticed that `getMitosisConfig` returns:
```
type MitosisConfig = {
  type?: 'library'; // Only one type right now
  targets: Target[];
  dest?: string;
  files?: string | string[];
  overridesDir?: string;
  options: Partial<GeneratorOptions>;
};

```
however, the type of the command-line arguments object for the `compile` command is `GluegunParameters.options`.
How will we map/merge these two, and which one will take higher precedence?

**Comment by sahilmob** [comment]
To my understanding, this sounds like reading generator options from `mitosis.config.js` and then overriding `generatorOpts` (if they do exist). Am I right?

```js   
const mitosisConfig = getMitosisConfig();
const generatorOptions = mitosisConfig.options?.[to];

const generatorOpts: Partial<{ [K in AllGeneratorOptionKeys]: any }> = {
  prettier: opts.prettier ?? true,
  plugins: plugins,
  format: opts.format,
  prefix: opts.prefix,
  includeIds: opts.includeIds,
  stylesType: opts.styles,
  stateType: opts.state,
  type: opts.type,
  cssNamespace: opts.cssNamespace,
  ...generatorOptions
};
```

**Comment by samijaber** [comment]
@sahilmob correct. `...generatorOptions` would be the first line though, since you typically want anything passed as a command-line flag to override what's in a config file. Looks good otherwise 👍🏽
