### ISSUE TITLE
Custom Elements: disconnectedCallback doesn't appear

### ISSUE THREAD

**Issue by ja-rivas** [BuilderIO/mitosis#209]
**Describe the bug**
The custom element function `disconnectedCallback` doesn't appear in the generated file (custom element) even though the `onUnMount` hook is used.

**To Reproduce**
1. Create a mitosis file and add the onUnMount hook.
2. Compile it to customElement.
3. Note that the disconnectedCallback method is missing.

Fiddle link: https://mitosis.builder.io/?outputTab=webcomponents&code=import+%7B+useState+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+%5Bname%2C+setName%5D+%3D+useState%28%22Steve%22%29%3B%0A%0A++onUnMount%28%28%29+%3D%3E+%7B%0A++++alert%28%27I+have+been+removed%21%27%29%3B%0A++%7D%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3ETEST%3C%2Fdiv%3E%0A++%29%3B%0A%7D

**Expected behavior**
A `disconnectedCallback` function should be used in the generated customElement file and the code inside the onUnMount hook should appear inside it.

**Comment by steve8708** [comment]
great catch - looking at the code it looks right, I wonder if our fiddle is out of date. taking a look

**Comment by steve8708** [comment]
yeah confirmed fiddle was just out of date - just released the latest version which should be live in about 10 mins when cache clears that looks to be working as desired:

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/844291/158478407-04cf90a5-d6b3-4803-90e7-5269675caa55.png">
