### ISSUE TITLE
Custom Elements: Updating element class

### ISSUE THREAD

**Issue by ja-rivas** [BuilderIO/mitosis#215]
**Describe the bug**
The class of an element isn't updated correctly when generating a customElement. Inside the `update` method, the class is updated using the `el.class` property instead of `el.className`. For example:
```js
this.querySelectorAll("[data-name='div-1']").forEach((el) => {
  el.class = this.state.name === "Steve" ? "bg-success" : "bg-primary";
});
```

**To Reproduce**
1. Create a mitosis file in which an element class's value depends on a variable (e.g. `<div class={backgroundClass}>`).
2. Compile the file to a customElement.
3. Note that in the `update` method the class value is being set by `el.class = value`.

Fiddle link: https://mitosis.builder.io/?outputTab=webcomponents&code=import+%7B+useState+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+%5Bname%2C+setName%5D+%3D+useState%28%22Steve%22%29%3B%0A%0A++return+%28%0A++++%3Cdiv+class%3D%7Bname+%3D%3D%3D+%27Steve%27+%3F+%27bg-success%27+%3A+%27bg-primary%27%7D%3E%0A++++++Hello%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D

**Expected behavior**
The element class should be updated using: `el.className = newValue;`.

**Screenshots**
Generated file with the issue:
![image](https://user-images.githubusercontent.com/8509401/158478900-74c05545-8e39-4328-b6c3-f3fff2afd307.png)

**Comment by steve8708** [comment]
great catch, simplest fix is likely to update [this](https://github.com/BuilderIO/jsx-lite/blob/fix-unmount-hook/packages/core/src/generators/html.ts#L304:L304)

to be 

```ts
const useKey = key === 'class' ? 'className' : key;
...
: `;el.${key} = ${useValue}`,
```

**Comment by PatrickJS** [comment]
oh this is fixed for webcomponents
