### ISSUE TITLE
Conventional Logging + Semantic Release

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#229]
Setup conventional logging / semantic release so that:

- changelogs are automatically generated
- new NPM package versions are automatically published on each merge

**Comment by kingzez** [comment]
I also want to use changesets, but found that it does not not support  conventional changelog yet

https://github.com/changesets/changesets/issues/577
https://github.com/changesets/changesets/issues/727
https://github.com/changesets/changesets/pull/928

**Comment by samijaber** [comment]
I'm not very fixated on conventional changelog. Any kind of automated changelog + automated released system would be great honestly

**Comment by maximveksler** [comment]
I would love to see you push forward to using changesets and conventional commits.

However if you're looking for other tools and approaches, I've made a short list available here https://github.com/semantic-release-plus/semantic-release-plus/issues/249

**Comment by misstong** [comment]
> I'm not very fixated on conventional changelog. Any kind of automated changelog + automated released system would be great honestly

I am interested in setting up this.

**Comment by samijaber** [comment]
@misstong Would love your contribution! You're welcome to take a stab at it, and let me know if you need any help 🙏🏽

**Comment by TGTGamer** [comment]
@samijaber have you considered https://github.com/googleapis/release-please - I've can pull together a PR & Demo on a fork if you would like? It's a really powerful tool to automating github releases based on conventional commits. 

All you would need to do is maintain conventional commits in the repo, and it will automatically tag, version and release with the option to output version data to files (e.g. packages.json) and changelog,md files

**Comment by samijaber** [comment]
Oh, Closing this as we have already implemented https://github.com/changesets/changesets
