### ISSUE TITLE
Upgrade to yarn 3 + Node 16

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#239]
We are currently using Node v14, npm v7 and Lerna v3.

We've wanted to upgrade to yarn3 but encountered some issues.

Whoever grabs this needs to make sure all the following works:
- locally, running `yarn run build`/`yarn run start` in every sub-package should work without issues (we had problems running `yarn run build` in `packages/core`)
- CI should pass

This task might be related to #211 and #236.

**Comment by sachinraja** [comment]
Awesome, should definitely be possible. I'll take this up.
