### ISSUE TITLE
Components can only have 1 of each hook

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#241]
**Describe the bug**
If there are multiple `onUpdate` hooks, only the last one will be persisted. The rest are omitted 

**To Reproduce**
If possible, a link to a https://mitosis.builder.io/ fiddle containing the bug: [fiddle](https://mitosis.builder.io/?outputTab=react&code=import+%7B+useState%2C+onUpdate+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+%5Bname%2C+setName%5D+%3D+useState%28%22Steve%22%29%3B%0A++const+%5BanotherName%2C+setAnotherName%5D+%3D+useState%28%22Steve%22%29%3B%0A%0A%0A++onUpdate%28%28%29+%3D%3E+%7B%0A++++console.log%28name%29%0A++%7D%2C+%5Bname%5D%29%0A++%0A++onUpdate%28%28%29+%3D%3E+%7B%0A++++console.log%28anotherName%29%0A++%7D%2C+%5BanotherName%5D%29%0A%0A%0A%0A++return+%28%0A++++%3Cdiv%3E%3Cdiv%3E%0A++++++%3Cinput%0A++++++++css%3D%7B%7B%0A++++++++++color%3A+%22red%22%2C%0A++++++++%7D%7D%0A++++++++value%3D%7Bname%7D%0A++++++++onChange%3D%7B%28event%29+%3D%3E+setName%28event.target.value%29%7D%0A++++++%2F%3E%0A++++++Hello%0A++++++%7Bname%7D%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A+%3C%2Fdiv%3E%0A%3Cdiv%3E%0A++++++%3Cinput%0A++++++++css%3D%7B%7B%0A++++++++++color%3A+%22red%22%2C%0A++++++++%7D%7D%0A++++++++value%3D%7Bname%7D%0A++++++++onChange%3D%7B%28event%29+%3D%3E+setAnotherName%28event.target.value%29%7D%0A++++++%2F%3E%0A++++++Hello+%7BanotherName%7D%0A%3C%2Fdiv%3E%3C%2Fdiv%3E++%0A++%29%3B%0A%7D)

**Expected behavior**
all hooks end up in the generated code{

**Screenshots**
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/1393142/159800546-1b83278d-ffa9-484d-a1dd-9dec532082dd.png">

**Additional context**
To fix this:
- the code responsible for generating `json.hooks.*` out of the Mitosis components will need to be changed such that it is storing arrays of hooks instead of just 1 of each
- Each individual generator's code will need to be modified, such that it is now handling an array instead of a single value. In some cases, this might entail generating unique names to each

**Comment by sahilmob** [comment]
I'll take this one
