### ISSUE TITLE
webcomponent: Show/For span tags interfere with accessibility and styling

### ISSUE THREAD

**Issue by alujs** [BuilderIO/mitosis#255]
Here's a sample output of the span tags:

Add any other context about the problem here.](https://mitosis.builder.io/?outputTab=webcomponents&code=import+%7B+useState+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A%0A++const+state+%3D+useState%28%7B%0A++++myArray%3A+%5B1%2C+2%2C+3%5D%2C%0A++++name%3A+%22Steve%22%2C%0A++++updateName%28newName%29+%7B%0A++++++state.name+%3D+newName%3B%0A++++%7D%0A++%7D%29%3B%0A%0A++onUpdate%28function%28%29+%7B%0A++++this.name+%3D+%27something%27%0A++%7D%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3CShow+when%3D%7Btrue%7D%3E%0A++++++++%3Cdiv%3E%0A++++++++++%3Cinput%0A++++++++++++css%3D%7B%7B%0A++++++++++++++color%3A+%22red%22%2C%0A++++++++++++%7D%7D%0A++++++++++++value%3D%7Bstate.name%7D%0A++++++++++++onChange%3D%7B%28event%29+%3D%3E+updateName%28event.target.value%29%7D%0A++++++++++%2F%3E%0A++++++++++Hello%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++++++%3C%2Fdiv%3E%0A++++++%3C%2FShow%3E%0A++++++%3CShow+when%3D%7Bfalse%7D%3E%0A++++++++++Hello+x2%0A++++++++++%3Cdiv%3E+Hello+%3C%2Fdiv%3E%0A++++++%3C%2FShow%3E%0A++++++%3CFor+each%3D%7Bstate.myArray%7D%3E%0A++++++++%7B%28theArrayItem%2C+index%29+%3D%3E+%3Cdiv%3E%7BtheArrayItem%7D%3C%2Fdiv%3E%7D%0A++++++%3C%2FFor%3E%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D%0A)

**Comment by PatrickJS** [comment]
we're going to use template tags to solve this
```html
<ul>
  <template class="host-show1"><li>item</li></template>
  <li class="group-show1 show1-item1">item</li>
  <li>
    other item
  </li>
  <template class="host-show2"><li>item</li><li>item</li></template>
  <li class="group-show2 show2-item1">item</li>
  <li class="group-show2 show2-item2">item</li>
</ul>
```

the template approach is using the template to know where the element(s) should be. and creating class groups so its not limited to a single root.
```javascript
// remove
Array.from(
  show1templateId.parent.query(show1GroupClass)
).forEach(el => el.remove())

// add
show1templateId.after(…show1Elements)
```

**Comment by PatrickJS** [comment]
we're changing it to start/end template tags to support Text nodes
```html
<ul>
  <template id="template-show1-sart"><li>item</li></template>
  <li>item</li>
  <template id="template-show1-end"></template>
  <li>
    other item
  </li>
  <template id="template-show2-start"><li>item</li><li>item</li></template>
  <li>item</li>
  <li>item</li>
  <template id="template-show2-end"></template>
  <template id="template-show3-start"> random text node <li>item</li></template>
   random text node 
  <li>item</li>
  <template id="template-show2-end"></template>
</ul>
```

**Comment by PatrickJS** [comment]
Show span tags for webcomponents were removed in #304 but the For loop span tags are still there
