### ISSUE TITLE
Custom Elements: Using a list item in an event handler

### ISSUE THREAD

**Issue by ja-rivas** [BuilderIO/mitosis#268]
**Describe the bug**
An error happens at run time when using the Mitosis's For to iterate through a list and using its items in an event handler. This occurs when generating a Custom Element/Web component.

**To Reproduce**
1. Use a For to iterate a list.
2. Add an event handler inside the For that uses the list items (e.g. `onClick={(event) => onItemClick(event, item)}`)
3. Run it or check the compiled code to find the error (see screenshots). The event handler doesn't have the For context and it's items, so it produces an error.

If possible, a link to a https://mitosis.builder.io/ fiddle containing the bug:
https://mitosis.builder.io/?outputTab=webcomponents&code=import+%7B+useState%2C+For+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+state+%3D+useState%28%7B%0A++++list%3A+%5B%27a%27%2C+%27b%27%2C+%27c%27%2C+%27d%27%5D%2C%0A%0A++++onItemClick%28item%29+%7B%0A++++++console.log%28%60%24%7Bitem%7D+was+clicked%60%29%3B%0A++++%7D%0A++%7D%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3CFor+each%3D%7Bstate.list%7D%3E%0A++++++++%7B%28item%29+%3D%3E%0A++++++++++%3Cdiv+onClick%3D%7B%28%29+%3D%3E+state.onItemClick%28item%29%7D%3E%0A++++++++++++%7Bitem%7D%0A++++++++++%3C%2Fdiv%3E%0A++++++++%7D%0A++++++%3C%2FFor%3E%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D

**Expected behavior**
It should be possible to use a list item in an event handler when using a Mitosis For to iterate a list.

**Screenshots**
Mitosis code:
![image](https://user-images.githubusercontent.com/8509401/162013139-444afb70-9dd0-4172-b7ee-03e6045959d0.png)

When its run and the event is fired, the custom Element produces an error like this:
![image](https://user-images.githubusercontent.com/8509401/162004882-872138a4-a9dd-45a9-a747-974ed8897785.png)

The generated file has the following code to set up the event handler:
![image](https://user-images.githubusercontent.com/8509401/162005324-cec18e9a-fe66-4354-88cc-594405505fc0.png)
The issue is that the `el` object is not defined, so it's not possible to get the context and value of the item.

**Comment by samijaber** [comment]
Thanks for raising this. I think one approach to fix it might be to change the event handlers' signatures so it's:

```
element => event => void
```

Here is the code responsible for generating all this code:

https://github.com/BuilderIO/mitosis/blob/46f609b8d6298c7cbeea73a5420f86311978c129/packages/core/src/generators/html.ts#L291-L312

Changing Lines 295-296 so they're more like:

```
               ? `this.${fnName} = el => (event) => {` 
               : `function ${fnName} (el) { return fn(event) {` 
```

And then changing lines 308-309:

```
             ;el.removeEventListener('${event}', ${fnIdentifier}(el)); 
             ;el.addEventListener('${event}', ${fnIdentifier}(el)); 

```

This would hopefully fix this bug 🤞🏽

**Comment by PatrickJS** [comment]
this is fixed in https://github.com/BuilderIO/mitosis/commit/4671607b306e1a4403965a6feab2f84cd9f2f415
