### ISSUE TITLE
Mitosis {props.children} creates <ng-slot> on Angular which does not exist 

### ISSUE THREAD

**Issue by alujs** [BuilderIO/mitosis#272]
https://mitosis.builder.io/?outputTab=angular&code=import+%7B+useState+%7D+from+%27%40builder.io%2Fmitosis%27%3B%0A%0Aexport+default+function+Checkbox%28props%29+%7B%0A%0A++function+getValue%28%29+%7B%0A++++return+props.isChecked%3B%0A++%7D%0A%0A++function+setValue%28value%29+%7B%0A++++props.isChecked+%3D+value%3B%0A++++props.onChange%28value%29%3B%0A++++props.onTouched%28%29%3B%0A++%7D%0A%0A++function+writeValue%28value%29++%7B%0A++++if+%28value%29+%7B%0A++++++props.isChecked+%3D+value%3B%0A++++%7D%0A++%7D%0A%0A++function+etDisabledState%28isDisabled%29+%7B%0A++++props._isDisabled+%3D+isDisabled%3B%0A++%7D%0A%0A++function+onCheckboxChange%28%24event%29+%7B%0A++++const+target+%3D+%24event.target%3B%0A++++props.isChecked+%3D+target+%26%26+target.checked%3B%0A++++props.onChange%28props.isChecked%29%3B%0A++%7D%0A%0A++return+%28%0A++++%3Cdiv+className%3D%22exp-checkbox%22%3E%0A++++++%3Clink+href%3D%22.%2Fstyles.css%22+rel%3D%22stylesheet%22%3E%3C%2Flink%3E%0A++++++%3Clabel+className%3D%22exp-checkbox__label%22%3E%0A++++++++%3Cdiv+className%3D%22exp-checkbox__check%22%3E%0A++++++++++%3Cinput%0A++++++++++++type%3D%22checkbox%22%0A++++++++++++checked%3D%7Bprops.isChecked%7D%0A++++++++++++onChange%3D%7B%28event%29+%3D%3E+onCheckboxChange%28event%29%7D%0A++++++++++++onBlur%3D%7Bprops.onTouched%7D%0A++++++++++++disabled%3D%7Bprops.isDisabled%7D%0A++++++++++%2F%3E%0A++++++++%3C%2Fdiv%3E%0A++++++++%3Cdiv+className%3D%7B%60exp-checkbox__label-text+%24%7B%21props.isDisabled+%3F+%22cursor-pointer%22+%3A+%22%22%7D%60%7D%3E%0A++++++++++%7B%2F*+%3Cng-content+select%3D%22%5Blabel%5D%22%3E%3C%2Fng-content%3E%0A++++++++++++++%3Csub%3E%0A++++++++++++++++%3Cng-content+select%3D%22%5BsubText%5D%22%3E%3C%2Fng-content%3E%0A++++++++++++++%3C%2Fsub%3E+*%2F%7D%0A++++++++++%7B+props.children+%7D%0A++++++++%3C%2Fdiv%3E%0A++++++%3C%2Flabel%3E%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D%0A

**Comment by samijaber** [comment]
Fixed by #273
