### ISSUE TITLE
ESLint rules: shareable recommended config

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#279]
It would be great to have a "recommended" shareable config like how other popular ESLint rule plugins do. That would make it a lot easier to adopt the rules automatically (vs. enabling one by one).

https://eslint.org/docs/developer-guide/shareable-configs#creating-a-shareable-config

also, adding `recommended: true` to appropriate rules (which should be all of them in our case, since they are all needed to output valid Mitosis code 🤔 ) https://eslint.org/docs/developer-guide/working-with-rules#rule-basics

**Comment by akrabdev** [comment]
can I pick this one up?

**Comment by samijaber** [comment]
@akrabdev You most certainly can! I'll assign you. Let me know if you have any questions around how we've got it setup, but it's a fairly straightforward ESLint plugin codebase.

**Comment by akrabdev** [comment]
Thank you @samijaber!

Confirming that all our ESLint rules have `recommended: true`

Also for having shareable config, tell me more about your goal in mind is it for example  creating a  standalone npm package in `mitosis/packages/` ex: `eslint-config-mitosis` ?

**Comment by samijaber** [comment]
> Also for having shareable config, tell me more about your goal in mind is it for example creating a standalone npm package in `mitosis/packages/` ex: `eslint-config-mitosis` ?

I was hoping we'd be able to store the shareable config in the same package as the rules themselves, similar to how it's done in this typescript-eslint package: https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/eslint-plugin/src/configs

You will see that it is being exported here in the same eslint package: https://github.com/typescript-eslint/typescript-eslint/blob/18a81cb715d994e8527607c8ee3fe848a59922d8/packages/eslint-plugin/src/index.ts#L14-L15

**Comment by akrabdev** [comment]
Thank you for the clarification! Wanted to make sure we are on the same page. The example you provided should be extremely helpful too.

**Comment by akrabdev** [comment]
@samijaber I facing some difficulties w/ testing

Sorry for for the delay

**Comment by samijaber** [comment]
Closed by #313 🎉
