### ISSUE TITLE
Certain CSS properties are missing from output styles

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#281]
**Describe the bug**
`alignItems` is missing from all outputs.

**To Reproduce**

If possible, a link to a https://mitosis.builder.io/ fiddle containing the bug: [link](https://mitosis.builder.io/?outputTab=svelte&code=export+default+function+Component%28props%29+%7B%0A++return+%28%0A++++%3Cdiv%0A++++++css%3D%7B%7B%0A++++++++display%3A+%27flex%27%2C%0A++++++++alignItems%3A+%27stretch%27%2C%0A++++++++flexDirection%3A+%27column%27%2C%0A++++++%7D%7D%0A++++%2F%3E%0A++%29%3B%0A%7D)

**Additional context**
Not sure if any other CSS properties are impacted by this

**Comment by micmro** [comment]
This seems to be fixed:
<img width="1792" alt="Screen Shot 2022-08-21 at 9 02 05 PM" src="https://user-images.githubusercontent.com/1680390/185819874-2532e9ff-b837-48b8-80a8-54dfdade818f.png">
[Demo](https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFAT0AD0iw4bEjmRN4JZADsAxjG6a4AWQCeAYQqRN6TTAAUYcmFQBKRBLhxtETangBtTRwQdAAaOAwYADkg9ABdOABeFAxsPHRbKmx0ADd0KmdJdzgodBhkKANbIo8AHhZgbIA%2Bao84GuBNMGQYFtbPVFQEhARevs8IJmgALmoSlioQ0b761DAmHGMZqhImWQWl1pwmYABzTQBJfBBULe1rfCgqA8JCA%2Byj5HQhwODXsdbvKYABY4TQnL4IWw5e6uBKNcKlaLBKG5GwcXBQcEwDjvJifZx%2FMY8Zr%2FAAS6CYkwAhHBzp5QcUtHAOnAAEroHC6MIANU%2BYUwE2ALDC0DgABlgABHRgsKktGo8epNIoFCSEIA%3D)

**Comment by samijaber** [comment]
That is true! Thanks for pointing it out. Not sure how we fixed it 😄
