### ISSUE TITLE
Duplicate `class` attributes in output

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#282]
**Describe the bug**
In Vue, React, Svelte (& possible others), there are duplicate `className` attributes _if_ we provide a `class` value & a non-empty `css` prop.

**To Reproduce**
If possible, a link to a https://mitosis.builder.io/ fiddle containing the bug: [link](https://mitosis.builder.io/?outputTab=svelte&code=export+default+function+Component%28props%29+%7B%0A++return+%28%0A++++%3Cdiv%0A++++++className%3D%7B%22test%22%7D%0A++++++css%3D%7B%7B%0A++++++++flexDirection%3A+%27column%27%2C%0A++++++%7D%7D%0A++++%2F%3E%0A++%29%3B%0A%7D)

**Additional context**
Removing the `css` prop (or changing it to an empty object) removes the additional `className`/`class`.

Note that the additional class's string value is always equal to the name of the element itself, e.g. `<img class="img" />`

**Comment by decadef20** [comment]
Can I work on this issue?

**Comment by PatrickJS** [comment]
@decadef20 I'll assign it to you
