### ISSUE TITLE
React: innerHTML does not inject variables

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#286]
**Describe the bug**
`innerHTML={state.name}` is stringified as the HTML string "name" instead of referring to the variable:

```
<div className="div" dangerouslySetInnerHTML={{ __html: "name" }} />
```

**To Reproduce**
If possible, a link to a https://mitosis.builder.io/ fiddle containing the bug: [link](https://mitosis.builder.io/?outputTab=react&code=import+%7B+useState+%7D+from+%27%40builder.io%2Fmitosis%27%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+state+%3D+useState%28%7Bname%3A%27Steve%27%7D%29%3B%0A%0A++return+%28%0A++++%3Cdiv%0A++++++css%3D%7B%7B%0A++++++++color%3A+%27red%27%2C%0A++++++%7D%7D%0A++++++innerHTML%3D%7Bstate.name%7D%0A++++%3E%3C%2Fdiv%3E%0A++%29%3B%0A%7D%0A)

**Expected behavior**
```
<div className="div" dangerouslySetInnerHTML={{ __html: name }} />
```

**Comment by decadef20** [comment]
I am working on it

**Comment by PatrickJS** [comment]
fixed via https://github.com/BuilderIO/mitosis/pull/385
