### ISSUE TITLE
ESLint rule: no var assigned with the same name as a prop field

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#302]
We have a similar rule for `state` properties: https://github.com/BuilderIO/mitosis/blob/main/packages/eslint-plugin/docs/rules/no-var-name-same-as-state-property.md#L1

It turns out that naming a var the same as a prop is similarly a problem in frameworks like Svelte since properties are stored at the module scope. This can cause a crash in Svelte if the value is using the prop:

[mitosis fiddle](https://mitosis.builder.io/?outputTab=svelte&code=import+%7B+useState+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+state+%3D+useState%28%7B%0A++++getName%28%29+%7B%0A++++++const+name+%3D+props.name+%7C%7C+%27hello%27%0A++++++return+name+%2B+%27+world%27%0A++++%7D%0A++%7D%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%7Bstate.getName%28%29%7D%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D)

```svelte
<script>
  export let name;

  function getName() {
    const name = name || "hello"; // this causes a crash
    return name + " world";
  }

</script>

<div>{getName()}</div>
```

**Comment by samijaber** [comment]
cc @sahilmob this is an easy new ESlint rule we could use if you're up for it!

**Comment by sahilmob** [comment]
Sure. Please assign it to me.
