### ISSUE TITLE
Fix `vue-template-compiler` dependency

### ISSUE THREAD

**Issue by rhengles** [BuilderIO/mitosis#316]
## **Describe the bug**

In [my project](https://github.com/arijs/astro-mitosis), I'm using `"astro": "^1.0.0-beta.17"` and `"@builder.io/mitosis": "^0.0.49"`.

There are some errors when installing dependencies in my project and when running Mitosis code, as I'll explain below.

## First suggestion

<details>
<summary>
When running `npm install` (with npm >= v7), these errors are printed:
</summary>

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: mobx-react-lite@3.3.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   dev react@"^17.0.2 || ^18.0.0" from the root project
npm ERR!   peer react@"^17.0.2 || ^18.0.0" from @astrojs/react@0.1.1
npm ERR!   node_modules/@astrojs/react
npm ERR!     dev @astrojs/react@"^0.1.1" from the root project
npm ERR!   3 more (@emotion/core, @emotion/react, react-dom)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17" from mobx-react-lite@3.3.0
npm ERR! node_modules/mobx-react-lite
npm ERR!   dev mobx-react-lite@"^3.3.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.0 || ^17" from mobx-react-lite@3.3.0
npm ERR!   node_modules/mobx-react-lite
npm ERR!     dev mobx-react-lite@"^3.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/gaudel/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gaudel/.npm/_logs/2022-05-01T22_15_52_505Z-debug-0.log
```

</details>

The solution to the error above is to install with the following command:
```
npm install --legacy-peer-deps
```

It appears that this error is caused by `mobx-react-lite` not yet supporting React 18. It would be _very nice_ (for me at least, some might consider it slightly more complicated) if Mitosis could use `mobx-react-lite` as a _peer_ dependency, and require that the user of Mitosis that want to use Mobx, also install that library.

## Second suggestion

But after the dependencies are installed, there is another error that require manual intervention, because `vue-template-compiler` tries to detect if there is a `vue` package installed with a mismatching version, and if so, it immediately panics and prevents any code that uses it (like `mitosis`) to run.

<details>
<summary>
I have to manually make this change (monkey patch):
</summary>

`/node_modules/vue-template-compiler/index.js`:

```diff
 try {
   var vueVersion = require('vue').version
 } catch (e) {}

 var packageName = require('./package.json').name
 var packageVersion = require('./package.json').version
-if (vueVersion && vueVersion !== packageVersion) {
+if (false && vueVersion && vueVersion !== packageVersion) {
   var vuePath = require.resolve('vue')
   var packagePath = require.resolve('./package.json')
   throw new Error(
     '\n\nVue packages version mismatch:\n\n' +
     '- vue@' + vueVersion + ' (' + vuePath + ')\n' +
     '- ' + packageName + '@' + packageVersion + ' (' + packagePath + ')\n\n' +
     'This may cause things to work incorrectly. Make sure to use the same version for both.\n' +
     'If you are using vue-loader@>=10.0, simply update vue-template-compiler.\n' +
     'If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump ' + packageName + ' to the latest.\n'
   )
 }

 module.exports = require('./build')
```

</details>

Maybe we could make the same change as above and make `vue-template-compiler` a peer dependency ? So the user only installs it if he wants to compile Mitosis to Vue ? I clearly don't know enough of the repo to know if this is a good strategy.

~~I did a search in this repo, and it looks that the `vue-template-compiler` is only called in the `cli` package. But I'm only using the `core` package, not the `cli`, but still the `vue-template-compiler` package is a dependency of the `core` package. Can it be safely removed from the core ?~~ _EDIT:_ Now I see it, the _Liquid_ parser is using this package inside core.

I don't know what is a good solution here, I'm just trying to explain my thought process. Please enlighten me.

**Comment by steve8708** [comment]
ah yes! vue-template-compiler absolutely should be a peerDependency (we also, in most cases, are going more in the direction of not precompiling and just generating .vue templates that then get compiled by the build of whoever imports those components anyway)

pull requests more than welcome

**Comment by steve8708** [comment]
re: mobx-react-lite, that's strange it's a dependency, it should only be a dependency of our fiddle 🤔 

but yeah if anything depends on it it can absolutely be a peerDependency

**Comment by rhengles** [comment]
> (we also, in most cases, are going more in the direction of not precompiling and just generating .vue templates that then get compiled by the build of whoever imports those components anyway)

There's a thing I don't understand here. This vue compiler is being used by `parsers/liquid`. AFAICT, Liquid syntax has only one similarity with Vue templates, which is the mustache/handlebars-like braces syntax `{{ foo }}`. Vue has colon attribute bindings `<a :href="href">` and Liquid has tag statements `{% if foo %}`, so they look pretty incompatible to me.

So how can this vue compiler possibly work inside the parser for Liquid ? And I saw that this parser is imported in the Fiddle code, but this option is not shown on the mitosis fiddle website. I didn't find either some tests or examples of using this parser. Is it abandoned ?

**Comment by rhengles** [comment]
@samijaber Hmm, this is still not quite good.

I just tried it now, but npm >= v7 _installs peer deps by default_. I can use the argument `--legacy-peer-deps`, but having to remember to always include it is bad. [npm docs](https://docs.npmjs.com/cli/v8/using-npm/config#legacy-peer-deps) say its use is not recommended.

Maybe we should move `vue-template-compiler` to [optionalDependencies](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#optionaldependencies) instead ? Then I could use `npm install --omit=optional`. (It´s _still_ a param to remember, but at least it's not _not_ recommended.)

I just wish that npm would keep the behavior of v6 regarding peer deps, or introduce another field `ifYouMustDependencies` 😅 that would only check versions if you manually installed that dep.

Or maybe this whole liquid parser thing could be removed, or reworked to not use vue compiler...

**Comment by samijaber** [comment]
@rhengles surprising you're having so many issues. Our SDKs are build w mitosis and I was able to fix this issue by using `resolutions` in yarn v3. Maybe its a non-issue in yarn?


But yeah, we spoke about this internally and the whole liquid parser is super experimental. It's using the Vue compiler purely because it's the "closest thing" to a compiler for liquid, but clearly as you've noted not a perfect match.

So we're going to kill it off completely :)

**Comment by rhengles** [comment]
Yes, I'm using npm v8 in my project, but I appreciate your attention and patience 😁
