### ISSUE TITLE
cli: Output is not generated for Angular and SolidJS frameworks

### ISSUE THREAD

**Issue by vamseekrishna9** [BuilderIO/mitosis#350]
**Describe the bug**
I am trying to generate components for react, reactNative, Angular, Vue, solidJS and Svelte with the basic example available @ https://github.com/BuilderIO/mitosis/tree/main/examples/basic

But, when I run the command `yarn run build` I am not getting components output generated for Angular and SolidJS.

**To Reproduce**
1. Download the code from [BuilderIO Mitosis basic example](https://github.com/BuilderIO/mitosis/tree/main/examples/basic) and update the version of `@builder.io/mitosis-cli` to latest version i.e., 0.0.16
2. Add angular and solidjs to targets array in mitosis.config.js
3. Run `yarn run build` script in the basic example app
4. Check the output folder for angular and solidjs. I can see only index-helpers and index.js are getting generated for angular and solidjs. Where as for other frameworks such as react, reactNative, svelte and vue, blocks(folder having components) are also getting generated.

I don't see any errors during the build process.

If possible, a link to a https://mitosis.builder.io/ fiddle containing the bug: Issue is not reproducible in fiddle.

**Expected behavior**
Components should be generated for Angular and SolidJS frameworks as well.

**Screenshots**
<img width="273" alt="image" src="https://user-images.githubusercontent.com/74584317/168571908-8e5b4cfb-b104-4b58-b62e-426434458327.png">

<img width="657" alt="image" src="https://user-images.githubusercontent.com/74584317/168571999-79b5c18c-aae8-47cf-8e92-a62eeeb8a5d6.png">

**Comment by suresh-legato** [comment]
Hi @vamseekrishna9, use `solid` instead of `solidjs` for `solid` conversion.

**Comment by PatrickJS** [comment]
@samijaber we should probably validate the config file like what webpack does

**Comment by samijaber** [comment]
@vamseekrishna9 Make sure to use the `dev` version of both `@builder.io/mitosis` and `@builder.io/mitosis-cli` and not `latest`. As of today, that would be [0.0.17-8](https://www.npmjs.com/package/@builder.io/mitosis-cli/v/0.0.17-8). Are you able to reproduce using that version?
