### ISSUE TITLE
core: update MitosisComponent.bindings to include arguments 

### ISSUE THREAD

**Issue by PatrickJS** [BuilderIO/mitosis#351]
```
bindings: {
  [index: string]: {
    arguments: string[],
    code: string
  };
}
```
in order to allow devs to change the event name we need to get the arguments from jsx and rewrite the code in the generator.

This PR is an example of that without arguments 
https://github.com/BuilderIO/mitosis/pull/323

**Comment by decadef20** [comment]
I want to have a try

**Comment by PatrickJS** [comment]
@decadef20 if you look at my PR half the code is not needed because it's guarding against overloading props.   https://github.com/BuilderIO/mitosis/pull/323#discussion_r868124062

in the code here https://github.com/BuilderIO/mitosis/blob/ccb51aed001181d55030011379175f58c478fea7/packages/core/src/types/mitosis-component.ts#L34
add `arguments` which is a type `string[]`


once we get that PR merged we can do the rest of the PR which is storing the arguments then using it in the generated code

**Comment by alujs** [comment]
@decadef20 

他希望你先做 PR，然后他会 merge。

**Comment by decadef20** [comment]
@PatrickJS @alujs 
抱歉 我误解了@PatrickJS
Sorry I misunderstood @PatrickJS 
When I finish, I will make a PR

**Comment by PatrickJS** [comment]
done via https://github.com/BuilderIO/mitosis/pull/369
