### ISSUE TITLE
Is it possible to re-use components from material library for conversion from mitosis to other frameworks

### ISSUE THREAD

**Issue by vamseekrishna9** [BuilderIO/mitosis#352]
**Describe the bug**
I would like to add components from material ui and add some additional styling and logics to match our design system and these needs to be converted to other frameworks. Is this possible with mitosis ?

**To Reproduce**
1. Create a sample mitosis project
2. Add @mui/material as dependency and create a simple component(may be a Button imported from @mui/material library)
3. Convert the component to other frameworks(for example: React, solid, Angular, Vue)
4. I still see the usage of @mui/material imports in other frameworks as well

Fiddle containing the bug: [Click here](https://mitosis.builder.io/?outputTab=angular&code=import+React%2C+%7B+useState+%7D+from+%22react%22%3B%0Aimport+Button+from+%22%40mui%2Fmaterial%2FButton%22%3B%0A%0Aexport+default+function+MuiButton%28%29+%7B%0A++return+%28%0A++++%3CButton+variant%3D%22text%22%3EText%3C%2FButton%3E%0A++%29%3B%0A%7D%0A)

**Expected behavior**
Button component from material ui should be converted to equivalent button component on other frameworks by applying all the styles of material ui button component.

**Screenshots**
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/74584317/168796020-33b88adc-2dc4-4d68-86e4-f0b396bc19dd.png">

I would like to know if this is possible or only conversion of static component is possible.

Thank you.

**Comment by PatrickJS** [comment]
not at the moment and will be hard to support without help with the lib author. This can be supported once react supports webcomponents then you can use that in angular.

I'm going to close this since the project can't support this at this time
