### ISSUE TITLE
vue: trailing comma in Vue code generator

### ISSUE THREAD

**Issue by PatrickJS** [BuilderIO/mitosis#387]
We have an issue with the code generated for `data` that `prettier` doesn't format correctly.
 
It might be because of this [        .map((thisImport) => Object.keys(thisImport.imports).join(','))](https://github.com/BuilderIO/mitosis/blob/40437e911185fc6eaa6de60f737326ffd38cca11/packages/core/src/generators/vue.ts#L442)

Link to snap with the issue
https://github.com/BuilderIO/mitosis/pull/385#discussion_r879401643

**Comment by samijaber** [comment]
I think this was fixed, right @PatrickJS ?
