### ISSUE TITLE
separate generators from mitosis/core

### ISSUE THREAD

**Issue by PatrickJS** [BuilderIO/mitosis#392]
we should have a mitosis/generator package with deep imports for any framework

@builder.io/mitosis-generator/webcomponent
@builder.io/mitosis-generator/angular
@builder.io/mitosis-generator/react

@builder.io/mitosis

**Comment by samijaber** [comment]
This makes sense in the long run, but given how small the contributor team is and how little tooling we have, it is far easier at the moment to have everything in one place when it comes to testing, publishing, and linking all the pieces together.

Definitely something we can further explore once tooling matures a bit. 👍🏽

**Comment by PatrickJS** [comment]
yeah thats a good point 👍
