### ISSUE TITLE
create helper lib per framework

### ISSUE THREAD

**Issue by PatrickJS** [BuilderIO/mitosis#394]
similar to tslib we may need a helper lib, as an option, to add/remove some runtime boilerplate. 

For webcomponent this is becoming more of an issue (for our use-case it hasn't been a big deal)

the way I see this is @builder.io/mitosis-react and @builder.io/mitosis-webcomponent and the dev can replace it in mitosis.config.js and choose to include it or not

**Comment by samijaber** [comment]
Can you elaborate on what these helper libs contain exactly? It's not clear to me what this is meant to improve.
