### ISSUE TITLE
webcomponent:  Attributes aren't being converted to props on load

### ISSUE THREAD

**Issue by PatrickJS** [BuilderIO/mitosis#416]
https://github.com/BuilderIO/mitosis/issues/410#issuecomment-1139301115

Attributes aren't being converted to props on load

https://codesandbox.io/s/papanasi-webcomponents-27zsfr?file=/index.html:151-158

**Comment by PatrickJS** [comment]
fixed via https://github.com/BuilderIO/mitosis/pull/377/commits/83a82821b3431a59924790cb577fc24d3cc60378
https://stackblitz.com/edit/js-tk9tub?file=index.js

**Comment by CKGrafico** [comment]
I wait for some days to be sure but, how is this fixed? https://mitosis.builder.io/?outputTab=webcomponents&code=import+%7B+onMount%2C+useMetadata%2C+useState+%7D+from+%27%40builder.io%2Fmitosis%27%3B%0Aimport+%7B+classesToString+%7D+from+%27..%2F..%2F..%2Fhelpers%27%3B%0Aimport+%7B+Dynamic%2C+Intent%2C+SharedProps%2C+Variant+%7D+from+%27..%2F..%2F..%2Fmodels%27%3B%0Aimport+%27.%2Fbutton.css%27%3B%0A%0A%0AuseMetadata%28%7B+isAttachedToShadowDom%3A+true+%7D%29%3B%0Aexport+default+function+Button%28props%29+%7B%0A++const+state+%3D+useState%28%7B%0A++++classes%3A+%27%27%0A++%7D%29%3B%0A%0A++onMount%28%28%29+%3D%3E+%7B%0A++++const+setInitialProps+%3D+%28variant%2C+outline%2C+intent%2C+disabled%2C+className%29+%3D%3E+%7B%0A++++++state.classes+%3D+classesToString%28%5B%0A++++++++%27pa-button%27%2C%0A++++++++%5Bvariant%2C+%60pa-button--%24%7Bvariant%7D%60%5D%2C%0A++++++++%5Boutline%2C+%27pa-button--outline%27%5D%2C%0A++++++++%5Bintent%2C+%60is-%24%7Bintent%7D%60%5D%2C%0A++++++++%5Bdisabled%2C+%27is-disabled%27%5D%2C%0A++++++++className%0A++++++%5D%29%3B%0A++++%7D%3B%0A%0A++++setInitialProps%28props.variant%2C+props.outline%2C+props.intent%2C+props.disabled%2C+props.className%29%3B%0A++%7D%29%3B%0A%0A++return+%3Cbutton+className%3D%7Bstate.classes%7D%3E%7Bprops.children%7D%3C%2Fbutton%3E%3B%0A%7D%0A

**Comment by samijaber** [comment]
@CKGrafico Our build pipeline does not (yet) automatically deploy changes to the Fiddle. We're having some issues updating it at the moment, but will let you know when it is live with the latest Mitosis code.

**Comment by CKGrafico** [comment]
@samijaber sorry I've used as example, I'm having the same behaviour in my library with the version [0.0.17-13](https://www.npmjs.com/package/@builder.io/mitosis-cli/v/0.0.17-13)

**Comment by CKGrafico** [comment]
MAybe it helps to others meanwhile you update the builder, this is what the cli is generating with the code of my previous example, thanks team :)

```
//@ts-nocheck 
/**
 * Usage:
 *
 *  <button></button>
 *
 */
export default class Button extends HTMLElement {
  get _root() {
    return this.shadowRoot || this;
  }

  constructor() {
    super();
    const self = this;

    this.state = {};
    if (!this.props) {
      this.props = {};
    }

    this.componentProps = ["variant", "children"];

    // used to keep track of all nodes created by show/for
    this.nodesToDestroy = [];
    // batch updates
    this.pendingUpdate = false;

    if (true) {
      this.attachShadow({ mode: "open" });
    }
  }

  destroyAnyNodes() {
    // destroy current view template refs before rendering again
    this.nodesToDestroy.forEach((el) => el.remove());
    this.nodesToDestroy = [];
  }

  connectedCallback() {
    this.getAttributeNames().forEach((attr) => {
      const jsVar = attr.replace(/-/g, "");
      const regexp = new RegExp(jsVar, "i");
      this.componentProps.forEach((prop) => {
        if (regexp.test(prop)) {
          const attrValue = this.getAttribute(attr);
          if (this.props[prop] !== attrValue) {
            this.props[prop] = attrValue;
          }
        }
      });
    });

    this._root.innerHTML = `
      <button data-el="button-1"><slot></slot></button>`;
    this.pendingUpdate = true;

    this.render();
    this.onMount();
    this.pendingUpdate = false;
    this.update();
  }

  onMount() {}

  onUpdate() {}

  update() {
    if (this.pendingUpdate === true) {
      return;
    }
    this.pendingUpdate = true;
    this.render();
    this.onUpdate();
    this.pendingUpdate = false;
  }

  render() {
    // re-rendering needs to ensure that all nodes generated by for/show are refreshed
    this.destroyAnyNodes();
    this.updateBindings();
  }

  updateBindings() {
    this._root.querySelectorAll("[data-el='button-1']").forEach((el) => {
      el.className = this.props.variant;
    });
  }

  // Helper to render content
  renderTextNode(el, text) {
    const textNode = document.createTextNode(text);
    if (el?.scope) {
      textNode.scope = el.scope;
    }
    if (el?.context) {
      textNode.context = el.context;
    }
    el.after(textNode);
    this.nodesToDestroy.push(el.nextSibling);
  }
}

customElements.get("pa-button") || customElements.define("pa-button",  Button);

```

PS: The solution is in the connected callback as @PatrickJS  mentioned
