### ISSUE TITLE
question: Events and Form controlling

### ISSUE THREAD

**Issue by schirrel** [BuilderIO/mitosis#417]
Sorry if is not the place i haven't found were to ask.
But very often the problem with build component for multiple frameworks is the event handling and form controllers.
I am curring planning to make a single UI lib that can be used both by react and vue.
I've tested pure web-component and also some libraries (and lit) and there are two major problems:
- Event emit -> some events don't "goes up" to component layout to be listened to the framework, very common to be submit or input/event
- Form controlling is pretty hard to validating inputs and data, i also tried some approachs like using `attachInternals` but even adding the functions, when build the web components dont work 100% right at any of the framework.

I've talk with some friend and this seems to be a pretty common problem. Asure the events keep being triggered, no emuted, and the parent functions, originally called but the api, keeps being called for the component.

With mitoses you guys could fund a solution to these problem? or even some wait to understand better?

I am very excited about it

**Comment by PatrickJS** [comment]
Right now Mitosis makes sense for atomic components and anything more you have to use per-framework in the package. I have a few different approaches to work around these controlled components (Animation/Modal/Forms) that will be plugins

**Comment by samijaber** [comment]
@schirrel I don't see why those would be issues with Mitosis. Mitosis is not like web components: the components that it generates are _pure_ React and Vue components. There is no trace of Mitosis left in them. So something [like this](https://mitosis.builder.io/?outputTab=react&code=import+%7B+useState+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+state+%3D+useState%28%7B%0A++++name%3A+%22Steve%22%2C%0A++++onSubmit%28event%29+%7B%0A++++++fetch%28%27https%3A%2F%2Fsome-url.com%27%29.then%28%29%0A++++%7D%0A++++%7D%29%3B%0A%0A++return+%28%0A++++%3Cform+onSubmit%3D%7Bevent+%3D%3E+state.onSubmit%28event%29%7D%3E%0A++++++%3Cinput%0A++++++++css%3D%7B%7B%0A++++++++++color%3A+%22red%22%2C%0A++++++++%7D%7D%0A++++++++value%3D%7Bname%7D%0A++++++++onChange%3D%7B%28event%29+%3D%3E+setName%28event.target.value%29%7D%0A++++++%2F%3E%0A++++++Hello%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fform%3E%0A++%29%3B%0A%7D) for example should not have any problems emiting/listening to events, or controlling forms and validating inputs.

**Comment by schirrel** [comment]
Wooooooa @samijaber thats awesome, i havent understood that, maybe my english break me here.
But the fact that they convert mitoses in pure is awesome, a huge thank you for clarify ❤️
