### ISSUE TITLE
Using onInit throws useEffect not defined

### ISSUE THREAD

**Issue by chadalen** [BuilderIO/mitosis#428]
- [x] I am interested in helping provide a fix!

**Scope**
- [ ] This impacts ALL Mitosis outputs
- [x] This only impacts specific generators/outputs (please list them here):
React

**Describe the bug**
When using the `onInit` mitosis hook in @builder.io/mitosis v0.0.56-11 you also have to define another hook e.g onUpdate or else you'll get an error saying useEffect hook was not defined. (See image)

![Screen Shot 2022-06-02 at 11 43 22 AM](https://user-images.githubusercontent.com/12568665/171672605-dbfe6909-a28c-4d1c-86c8-44e0eead7cf7.png)

**To Reproduce**
1. Use onInit hook in a component without any other hooks
2. You should get the error in the picture above
3. If you import onUpdate and call an empty function inside the onUpdate hook the error will go away.
```
  onUpdate(() => {

  });
```

A link to a https://mitosis.builder.io/ fiddle containing the bug:
The fiddle seems to be outdated. This issue doesn't happen on fiddle but does happen on the latest dev version of @builder.io/mitosis

**Expected behavior**
We should be able to use onInit without needing another hook.

**Screenshots**

**Additional context**

**Comment by samijaber** [comment]
@chadalen Thanks for the bug, and the willingness to fix it! This one is _super_ easy, especially thanks to your useful debugging :) :

https://github.com/BuilderIO/mitosis/blob/c701c0009893df07d56f5eabdc8910d81561b1d5/packages/core/src/generators/react.ts#L560-L567

We're missing a check here for `json.hooks.onInit?.code`.

**Comment by PatrickJS** [comment]
fixed via https://github.com/BuilderIO/mitosis/pull/429
