### ISSUE TITLE
End-to-end testing

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#430]
## Problem

Our current snapshot testing in `packages/core` only does so much. It does not:

- always make sure that the generated code is even valid JS
- that the generated components are valid in regard to the rules of their frameworks
- that the generated components have the features they are meant to have (interactivity, state management, styling, lifecycle hooks logic, etc.)

Another big issue is that we do not have a good idea of what features are supported by which generators at any given point. We currently have about 12 generators, and they don't all support every single feature and edge case. It is unfeasible to manually gather that information and keep it up to date.

## Ideal process

The ideal process I have in mind to accomplish this type of code coverage is to have an end-to-end testing pipeline like so:

- write a Mitosis project containing many components in `packages/testing`
- run it through the Mitosis CLI to generate a directory for each framework we support
- render every generated version of every framework on some server (N servers for N frameworks)
- For each framework, run the same integration test suite on each of its generated components in Storybook using a tool like Playwright https://storybook.js.org/addons/storybook-addon-playwright

To solve the issue of identifying feature support, we would then add some logic that performs all of these tests against every output, but allows for certain failures. We then need to generate a matrix of feature support (e.g. each row is a feature, each column is a framework) that gets printed in a markdown file in the repo (where [this](https://github.com/BuilderIO/mitosis/blob/c701c0009893df07d56f5eabdc8910d81561b1d5/docs/feature-matrix-draft.md#L1) currently lives)

## Example
So, if we have a clickable button, say `packages/testing/src/button.lite.tsx`.

1 - We would run `mitosis build`, and end up with:
- `packages/testing/output/vue/button.vue`
- `packages/testing/output/svelte/button.svelte`
- `packages/testing/output/react/button.tsx`
- `packages/testing/output/solidjs/button.tsx`
- etc.

2- We would load all of those using parallel servers (each in its own Github Action)

3- We would then have a test, say `packages/testing/playwright/tests/button.ts`. This test would execute on each github action against a different server.

4- We would finally compile all of the results and generate a matrix based on what passed and what failed.

## Initial implementation

The quickest way to get an MVP of this idea is:
- Create a single, simple test (a div with text)
- Output it to just 1 framework (React to start would be good)
- import the generated components to a simple server that supports React 
- run a playwright test that checks that the div has the expected text
- do all of the above in a Github Action task

Once that baseline is there, next steps are to:
- add more frameworks support: Vue & Svelte
- update testing to handle multiple framework tests in parallel

Once we have multiple frameworks, we can then start to generate a ton more tests, and increase framework support gradually!

**Comment by samijaber** [comment]
@kylecordes I don't have much experience with Storybook, so you could be totally right here! Can you point to any well-known issues you're aware of, or have faced regarding this inconsistency? Are there certain outputs it struggles with more than others?

And yeah, my original vision included exactly what you described: a `sveltekit` server for svelte, a simple `solidjs+vite` template for solidjs, a `nextjs` server for React, `nuxtjs` for Vue (or whatever, I'm just listing the zero friction tools I know of). The bare-minimum, zero-config server for each tool and just import all of the generated code in one page or whatever.

Definitely open to doing that as well. Our hope was to leverage Storybook which would be great for its own non-testing reasons, but we can definitely get started with this parallelized approach first and get going. It'd be much faster to get the ball rolling, and if Storybook is useful, we can always migrate there and delete a bunch of server code :).

I will update the original ticket!

**Comment by kylecordes** [comment]
From discussions with @samijaber , here is some elaboration of goals for end to end testing. Two "axes".

1. A set of small programs which exercise each Mitosis feature. First exercising them in isolation, then in combination. Currently there is 1 such program, likely 10-20 will be needed. For each such program, have a Playwright test.
2. List of Mitosis targets. As I write this, 6 targets work.

For each combination of program/target, attempt:

1. Run Mitosis on the input, and get output without Mitosis erroring.
2. Build the output under the target framework, without erroring.
3. Execute the output, and verify it passes the Playwright test.

Output the results into a testing status table, which conveniently also serves as a feature support matrix.

**Comment by kylecordes** [comment]
Here are some of the obstacles to doing this today; I'm considering how many to work around, vs wait for, vs jump into the middle of Mitosis and fix.

All of these can be worked around... but that's not ideal because the workarounds are further from intended real Mitosis use.

#510 Currently, Mitosis fails if output for any target fails, I have an approach to work around this by running Mitosis separately for each target.

#509 Currently mitosis "build" doesn’t accept parameters; I can work around this by making the config file inspect process.argv.

#494 Currently Mitosis has an internal glob that expects source to under “src”, regardless of the config setting. I could work around this to have a set of test programs by running Mitosis from a different working directory for each.

**Comment by samijaber** [comment]
Closed by https://github.com/BuilderIO/mitosis/pull/445 a while back! 🎉
