### ISSUE TITLE
Setting state to a property on a ref throws "Object is possibly 'undefined'" for React output

### ISSUE THREAD

**Issue by chadalen** [BuilderIO/mitosis#432]
- [x] I am interested in helping provide a fix!

**Scope**
- [ ] This impacts ALL Mitosis outputs
- [x] This only impacts specific generators/outputs (please list them here):
React only

**Describe the bug**
If you set state to a property on a ref e.g
```ts
state.checked = !!inputRef?.checked;
```

React build fails with error (see below)

The React output should be using optional chaining to make sure `.current` is not `null` or `undefined` e.g
```ts
setChecked(!!inputRef?.current?.checked);
```

not
```ts
setChecked(!!inputRef.current?.checked);
```

**To Reproduce**
See fiddle

A link to a https://mitosis.builder.io/ fiddle containing the bug:
https://mitosis.builder.io/?outputTab=react&code=import+%7B+useState%2C+useRef+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+state+%3D+useState%28%7B%0A++++checked%3A+false%2C%0A++%7D%29%3B%0A%0A++const+inputRef+%3D+useRef%28%29%3B%0A%0A++function+handleOnChange%28%29+%7B%0A++++state.checked+%3D+%21%21inputRef%3F.checked%3B%0A++%7D%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3Cinput%0A++++++++ref%3D%7BinputRef%7D%0A++++++++type%3D%22radio%22%0A++++++++onChange%3D%7B%28%29+%3D%3E+handleOnChange%28%29%7D%0A++++++%2F%3E%0A++++++Hello%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D

**Expected behavior**
React output should be
```ts
setChecked(!!inputRef?.current?.checked);
```

not
```ts
setChecked(!!inputRef.current?.checked);
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12568665/171702633-eecee652-5cd9-4889-a758-b655f6d545c6.png)

**Additional context**

**Comment by PatrickJS** [comment]
@chadalen you can update code here

https://github.com/BuilderIO/mitosis/blob/5c40807e9ca6f1d3ca12e83af7780e3aa5deaaf5/packages/core/src/generators/react.ts#L524

**Comment by chadalen** [comment]
@PatrickJS Perfect thanks I'll create a PR real quick.

**Comment by PatrickJS** [comment]
fixed via https://github.com/BuilderIO/mitosis/pull/433
