### ISSUE TITLE
docs: update local developer docs to mention command yarn run fmt:prettier

### ISSUE THREAD

**Issue by chadalen** [BuilderIO/mitosis#435]
- [x] I am interested in helping provide a fix!

The local developer docs found [here](https://github.com/BuilderIO/mitosis/tree/main/developer) should mention after the developer makes their changes to run `yarn run fmt:prettier` in the root of the project to make sure their code is formatted so the linter doesn't fail.

For reference see [here](https://github.com/BuilderIO/mitosis/pull/429#issuecomment-1145154278)

**Comment by kylecordes** [comment]
In a recent change, I make that doc direct folks to run `yarn ci` before submitting; that include Prettier, tests, etc.

Maybe that chunk of text should explain what all checks `yarn ci` performs, i.e. Prettier and more?

**Comment by samijaber** [comment]
@chadalen Are you still interested in doing this? Should be a quick doc change. Otherwise I can unassign you

**Comment by chadalen** [comment]
@samijaber Here's the PR https://github.com/BuilderIO/mitosis/pull/528

**Comment by samijaber** [comment]
Closed by #528
