### ISSUE TITLE
React output can have JS files without TS source, hindering consumption from TS

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/mitosis#444]
- [X] I am interested in helping provide a fix!
- [X] ... though I am currently working on e2e testing likely to reveal more bugs instead...

**Scope**
- [ ] This impacts ALL Mitosis outputs
- [X] This only impacts specific generators/outputs (please list them here): React

**Describe the bug**

The react output includes TypeScript and JavaScript. The TypeScript is missing for non-component files, such as the state file in the file tree shown here. This file tree comes from the Todo example.

![Screen Shot 2022-06-03 at 8 58 45 PM](https://user-images.githubusercontent.com/8799/171972224-13d2e117-9847-47b0-8d49-ad1fe6c7cdf4.png)

**To Reproduce**

1. Look at the output from the Todo example

**Expected behavior**

TypeScript is all there, for consumption in TS React projects.

JS also there, 1:1 files, for consumption in JS projects... every JS file has a TS file from which it came.

**Comment by samijaber** [comment]
Created https://github.com/BuilderIO/mitosis/issues/450 as per my comment. Will close this issue for now!
