### ISSUE TITLE
BUG: Vue: add missing `.vue` extension to component imports

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/mitosis#446]
**Scope**
- [ ] This impacts ALL Mitosis outputs
- [X] This only impacts specific generators/outputs (please list them here): Vue

**Describe the bug**

When outputting 2 components to Vue, where one uses the other, the import is missing the .vue extension and does not work.

**To Reproduce**

Problem is visible in this example, on the selected file, on line 25.

https://stackblitz.com/edit/node-3nrn7m?file=output%2Fvue%2Fnuxt2%2Fsrc%2Fcomponents%2Fmy-component.vue

This is a StackBlitz, not a fiddle, because it needs 2 components to illustrate the problem.

The incorrect line of output is:

```
import ItemList from "./item-list";
```

**Expected behavior**

```
import ItemList from "./item-list.vue";
```

**Comment by samijaber** [comment]
@kylecordes Thanks for filing. 

How are you generating these components? `mitosis build`, `mitosis compile`, or directly importing generator fns from `@builder.io/mitosis`?

**Comment by samijaber** [comment]
> It looks like `compile` expects command line arguments, while `build` looks at the config file

Not quite. Added a PR to outline the diffs between the two CLI commands a little better https://github.com/BuilderIO/mitosis/pull/467/files

But yes, using `build` is the right thing in this case, and I see in our own Vue SDKs that the `.vue` extension is not there. However, our Mitosis-generated Vue SDK work fine. I think it might be an env-based thing (Webpack vs esbuild vs vite vs nuxt...etc)

And reading online, it seems like importing without `.vue` was accepted but some recent changes in the Vue world are getting rid of it? https://github.com/vuejs/vue-cli/issues/5549#issuecomment-638850440

**Comment by samijaber** [comment]
I guess it's best to include the explicit `.vue` extension to avoid problems though.

We have 2 functions that replace a `.lite` extension in an import statement: 

Once when a Mitosis component's code is generated


https://github.com/BuilderIO/mitosis/blob/a2a8a53ed100abc7a944110c59b2d622dd30016e/packages/core/src/helpers/render-imports.ts#L31-L42

Once in a general transpilation step in `mitosis build` that renames imports across the folder (including mitosis & non-mitosis files).

https://github.com/BuilderIO/mitosis/blob/a2a8a53ed100abc7a944110c59b2d622dd30016e/packages/cli/src/build/helpers/extensions.ts#L1-L17


My understanding of using both of these 2 together is that we'd end up with the `.vue` extension, but that doesn't seem to be the case. Should be as easy as adding a switch case to the function in `render-imports.ts` though

**Comment by kylecordes** [comment]
Great to see the doc improvement!

In terms of code gen, I think the "just works" path is to generate files that will work with whatever the most common downstream tools are. Not sure if I picked right, using Vite+Vue for the E2E; maybe that is pickier than Vue's own CLI. Of course it would be best to work with both.

Ideally the result is a "pit of success" -> no matter what you throw at Mitosis, you get back either an explanatory error, or output which compiles and runs on all targets. Obviously a lot of work to get there!

**Comment by samijaber** [comment]
Yeah 100%. Made the `.vue` extension always there now.
