### ISSUE TITLE
Svelte does not allow to use the same name from props/function in state

### ISSUE THREAD

**Issue by CKGrafico** [BuilderIO/mitosis#447]
**Scope**
- [ ] This impacts ALL Mitosis outputs
- [X] This only impacts specific generators/outputs (please list them here):
Svelte

**Describe the bug**
If you create a state with a key that has the same name than a prop or a hook, this is not allowed by svelte, is this by design? this is only happening with svelte.

A link to a https://mitosis.builder.io/ fiddle containing the bug:  https://mitosis.builder.io/?outputTab=svelte&code=import+%7B+useState%2C+onMount+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+state+%3D+useState%28%7B%0A++++example%3A+1%2C%0A++++onMount%28%29+%7B%0A++++++state.example+%3D+props.example%3B%0A++++%7D%0A++%7D%29%3B%0A%0A%0A++onMount%28%28%29+%3D%3E+state.onMount%28%29%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3Cinput%0A++++++++css%3D%7B%7B%0A++++++++++color%3A+%22red%22%2C%0A++++++++%7D%7D%0A++++++++value%3D%7Bname%7D%0A++++++++onChange%3D%7B%28event%29+%3D%3E+setName%28event.target.value%29%7D%0A++++++%2F%3E%0A++++++Hello%0A++++++%7Bname%7D%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D

**Expected behavior**
Don't have differences between frameworks, maybe you can change the names of the props or state in svelte example:

Instead of:
```
before:
prop.example = 1;
state.example = 2;

after:
export let example = 1;
let example = 2
``` 

do:
```
before:
prop.example = 1;
state.example = 2;

after:
export let example = 1;
let exampleProp = 2
```

**Possible solution if this is not fixed**
Dont use the same names in props and in states.

https://mitosis.builder.io/?outputTab=svelte&code=import+%7B+useState%2C+onMount+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+state+%3D+useState%28%7B%0A++++example%3A+1%2C%0A++++onMounted%28%29+%7B%0A++++++state.example+%3D+props.value%3B%0A++++%7D%0A++%7D%29%3B%0A%0A%0A++onMount%28%28%29+%3D%3E+state.onMounted%28%29%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3Cinput%0A++++++++css%3D%7B%7B%0A++++++++++color%3A+%22red%22%2C%0A++++++++%7D%7D%0A++++++++value%3D%7Bname%7D%0A++++++++onChange%3D%7B%28event%29+%3D%3E+setName%28event.target.value%29%7D%0A++++++%2F%3E%0A++++++Hello%0A++++++%7Bname%7D%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D

**Comment by samijaber** [comment]
@CKGrafico This is a well-known limitation in Mitosis in general: https://github.com/BuilderIO/mitosis/blob/main/packages/eslint-plugin/docs/rules/no-var-name-same-as-state-property.md

Since in Svelte, both `props` and `state` properties get hoisted to the module scope, this is bound to happen. We can potentially work around it in the future by adding more complex logic in our generators where we rename properties that collide to avoid issue, just like you suggested.


Closing this issue since it's already documented on our end and we have an ESLint rule to warn against it.

**Comment by CKGrafico** [comment]
Oh amazing I will use your eslint.. I was not using it.
Thanks for the info
