### ISSUE TITLE
useRef not exist in Solid after compilation

### ISSUE THREAD

**Issue by CKGrafico** [BuilderIO/mitosis#457]
**Scope**
- [ ] This impacts ALL Mitosis outputs
- [X] This only impacts specific generators/outputs (please list them here):
Solid

**Describe the bug**
```
 Cannot find name 'useRef'.
src/code.tsx (67:22)

67   const previewRef = useRef();
                        ~~~~~~
```

**To Reproduce**
1.  Copy oficial code using 'useRef' from mitosis examples https://github.com/BuilderIO/mitosis/blob/43179c29a11d48b5f51e9138630c1eac6b021d87/packages/core/src/__tests__/data/blocks/embed.raw.tsx
2. paste it in the fiddle https://mitosis.builder.io/?outputTab=solid&code=import+%7B+useState%2C+useRef%2C+onMount+%7D+from+%27%40builder.io%2Fmitosis%27%3B%0A%0Aexport+interface+EmbedProps+%7B%0A++content%3A+string%3B%0A%7D%0A%0Aexport+default+function+Embed%28props%3A+EmbedProps%29+%7B%0A++const+elem+%3D+useRef%28%29%3B%0A%0A++const+state+%3D+useState%28%7B%0A++++scriptsInserted%3A+%5B%5D+as+string%5B%5D%2C%0A++++scriptsRun%3A+%5B%5D+as+string%5B%5D%2C%0A%0A++++findAndRunScripts%28%29+%7B%0A++++++%2F%2F+TODO%3A+Move+this+function+to+standalone+one+in+%27%40builder.io%2Futils%27%0A++++++if+%28elem+%26%26+typeof+window+%21%3D%3D+%27undefined%27%29+%7B%0A++++++++%2F**+%40type+%7BHTMLScriptElement%5B%5D%7D+*%2F%0A++++++++const+scripts+%3D+elem.getElementsByTagName%28%27script%27%29%3B%0A++++++++for+%28let+i+%3D+0%3B+i+%3C+scripts.length%3B+i%2B%2B%29+%7B%0A++++++++++const+script+%3D+scripts%5Bi%5D%3B%0A++++++++++if+%28script.src%29+%7B%0A++++++++++++if+%28state.scriptsInserted.includes%28script.src%29%29+%7B%0A++++++++++++++continue%3B%0A++++++++++++%7D%0A++++++++++++state.scriptsInserted.push%28script.src%29%3B%0A++++++++++++const+newScript+%3D+document.createElement%28%27script%27%29%3B%0A++++++++++++newScript.async+%3D+true%3B%0A++++++++++++newScript.src+%3D+script.src%3B%0A++++++++++++document.head.appendChild%28newScript%29%3B%0A++++++++++%7D+else+if+%28%0A++++++++++++%21script.type+%7C%7C%0A++++++++++++%5B%0A++++++++++++++%27text%2Fjavascript%27%2C%0A++++++++++++++%27application%2Fjavascript%27%2C%0A++++++++++++++%27application%2Fecmascript%27%2C%0A++++++++++++%5D.includes%28script.type%29%0A++++++++++%29+%7B%0A++++++++++++if+%28state.scriptsRun.includes%28script.innerText%29%29+%7B%0A++++++++++++++continue%3B%0A++++++++++++%7D%0A++++++++++++try+%7B%0A++++++++++++++state.scriptsRun.push%28script.innerText%29%3B%0A++++++++++++++new+Function%28script.innerText%29%28%29%3B%0A++++++++++++%7D+catch+%28error%29+%7B%0A++++++++++++++console.warn%28%27%60Embed%60%3A+Error+running+script%3A%27%2C+error%29%3B%0A++++++++++++%7D%0A++++++++++%7D%0A++++++++%7D%0A++++++%7D%0A++++%7D%2C%0A++%7D%29%3B%0A%0A++onMount%28%28%29+%3D%3E+%7B%0A++++state.findAndRunScripts%28%29%3B%0A++%7D%29%3B%0A%0A++return+%3Cdiv+ref%3D%7Belem%7D+class%3D%22builder-embed%22+innerHTML%3D%7Bprops.content%7D%3E%3C%2Fdiv%3E%3B%0A%7D
3. Try to compile to solid
4. `useRef` is used but not imported or mocked.

A link to a https://mitosis.builder.io/ fiddle containing the bug:

**Comment by CKGrafico** [comment]
Happy to hear that is going to be easy to fix, thanks!

**Comment by PatrickJS** [comment]
here are the changes for it https://github.com/BuilderIO/mitosis/pull/439/commits/32d5ecf207d8a7edc4c283cbe361bc0a561813f3
