### ISSUE TITLE
react: transfer types forwardRef

### ISSUE THREAD

**Issue by PatrickJS** [BuilderIO/mitosis#462]
We need to parse the type in the Props and transfer the type to the forwardRef

mitosis input
```typescript
export interface Props {
  inputRef: MyType;
}

export default function MyComponent(props: Props) {
  return <input ref={props.inputRef} />
}
```

react output
```typescript
export interface Props {
  inputRef: MyType;
}

export default forwardRef<MyType>(function MyComponent(props: Props, inputRef) {
  return <input ref={inputRef} />
})
```

**Comment by PatrickJS** [comment]
@samijaber we need a parser to parse the types for local exports. We can't transfer types for Angular output either without that

**Comment by samijaber** [comment]
@PatrickJS The path of least resistance to get this working without any additional parsing is to simply access `Props["inputRef"]`. We know the name of the props type from `json.propsTypesRef`, and the name of the prop through the `getRefsString`.

Will put up a WIP PR for you to see what I mean
