### ISSUE TITLE
webcomponent output has TypeScript in a .js file

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/mitosis#473]
- [X] I am interested in helping provide a fix!

**Scope**

- [X] This only impacts specific generators/outputs (please list them here): webcomponent

**Describe the bug**

The webcomponent output has a ".js" file, which has TypeScript code in it. Downstream tools... are not expecting this.

**To Reproduce**

```
yarn
yarn build
```

look at `packages/e2e-app/output/webcomponent/src/components/my-component.js`

**Expected behavior**

Ideally: Emit TS, compile it to JS+d.ts for proper downstream consumption.

OK: Emit JS (in a .js file).

**Screenshots**

![Screen Shot 2022-06-10 at 9 31 12 PM](https://user-images.githubusercontent.com/8799/173169370-2afdfcbd-3051-4f38-aebd-394740b11f44.png)

**Comment by samijaber** [comment]
Good catch. 

Now that we are starting to add types to the Mitosis generators' output, we need to rename the default extension(s) that our `mitosis build` command uses to `.ts`/`.tsx` probably: https://github.com/BuilderIO/mitosis/blob/ab0708fd2c07a06a7a52ab7490cd8e716759a48a/packages/cli/src/build/helpers/extensions.ts#L3-L16




Also, we might want to add some logic to toggle TS output on/off in the CLI commands, and select `.ts`/`.js` (or `.jsx`/`.tsx`) based on that. To do that: 

- have the core generators always emit TS, and add a `MitosisConfig["outputs"]: ["typescript" | "javascript"]` flag to the CLI. 
  - If the `outputs` array contains `typescript`, we output the TS code as-is.
  - If the `outputs` array contains `javascript`, an additional transpilation step is executed that takes the TS code and transpiles it down to JS, and saves that to a file

The `outputs` array can contain 1 or both of those flags. If it's empty, we default to `typescript` 🤔.

PS: We can probably reuse this function for transpilation: https://github.com/BuilderIO/mitosis/blob/ab0708fd2c07a06a7a52ab7490cd8e716759a48a/packages/cli/src/build/helpers/transpile.ts#L17

**Comment by kylecordes** [comment]
An a PR coming soon I’m looking to address just the first part of this, getting the extensions right.

Once mitosis can emit valid TypeScript in all cases, there shouldn't be any need to have another code path to directly emit JavaScript.
