### ISSUE TITLE
HTML output is in a .js file

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/mitosis#476]
- [X] I am interested in helping provide a fix!

**Scope**
- [X] This only impacts specific generators/outputs (please list them here):

**Describe the bug**

The html output target lands in a file with .js extension.

**To Reproduce**

```
yarn
yarn ci:build
```

Then look at `packages/e2e-app/output/html/src/components/my-component.js`

**Expected behavior**

HTML output in a `.html` file, or perhaps consider some other extension indicating it is meant to be included in other HTML? (`.inc`?), But not `.js`.

**Comment by samijaber** [comment]
@PatrickJS Do you have any thoughts on this from your work on the HTML generator?

It _might_ be as simple as adding the right extension here for `mitosis build` 

https://github.com/BuilderIO/mitosis/blob/ab0708fd2c07a06a7a52ab7490cd8e716759a48a/packages/cli/src/build/helpers/extensions.ts#L3

**Comment by PatrickJS** [comment]
Ive been focusing on webcomponent only. Html output needs some work. It's a little bit confusing what html output should be. Become It's not webcomponent it does make sense to keep them .html files but they're not exactly components

**Comment by kylecordes** [comment]
Sure, my bug report was only at a initial, highly surface level. That the contents of the file should match the extension.

For the real question of what the output should be, does anyone know what the output looks like for existing, already popular component sets packaged as web components? I'm just catching up on email on the weekend as I write this, otherwise I would go research right now...

**Comment by PatrickJS** [comment]
@samijaber @steve8708 what is the expected html output? Is it the same thing as webcomponent just with no custom elements?

**Comment by steve8708** [comment]
yeah exactly, the initial thinking was this is useful for very simple things. so can support basic HTML output, event listeners, data bindings. so is useful for codegen for things like Builder. not necessarily sure how it could or ever would child components tho, that is the main known constraint right now
