### ISSUE TITLE
Add Vue 3 support

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#492]
- Fix Vue 3 output
- Setup CLI & mitosis.config.js to allow a user to generate both in one `mitosis build` run

**Comment by kylecordes** [comment]
Import difference between Vue 2 and 3 shown here. Vue 2 commented, Vue 3 uncommented.

![Screen Shot 2022-06-16 at 11 00 14 PM](https://user-images.githubusercontent.com/8799/174350317-0b344c11-312d-46a8-8a3b-cd0c00b385a6.png)

**Comment by samijaber** [comment]
closed by #495  and #497
