### ISSUE TITLE
Doc request: more about mitosis.config.ts

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/mitosis#493]
Currently the file `configuration.md` has a very brief description of the configuration, pointing to the type definition for details.

This is infinitely better than nothing; thank you.

Still... this issue is a documentation request that someone very familiar with this configuration file explain it more fully in human-oriented documentation. That should be helpful for people newly arriving to the project.

**Comment by bjankord** [comment]
Agreed, would love to see improved documentation for this project across the board.

**Comment by samijaber** [comment]
We would love external contributions on this! The types have quite a bit of documentation: all that's needed is to copy-paste that info from:

https://github.com/BuilderIO/mitosis/blob/801894b99aeefa12986185898cf310ed3376447e/packages/core/src/types/config.ts#L16-L56

into:

https://github.com/BuilderIO/mitosis/blob/801894b99aeefa12986185898cf310ed3376447e/docs/configuration.md

This is a very easy first contribution, so if anyone is interested, let me know! 😃

**Comment by hiteacheryouare** [comment]
I would like to help :)

**Comment by samijaber** [comment]
@hiteacheryouare Appreciate you offering to help! I would look at the latest version of the files I've linked to above as starting point. 

Let me know if you have any questions or issues. 🙏🏽

**Comment by hiteacheryouare** [comment]
Fixed in #1015

**Comment by amazonsingh** [comment]
this can be closed
