### ISSUE TITLE
Question: Why are you using Solid's createMutable?

### ISSUE THREAD

**Issue by orenelbaum** [BuilderIO/mitosis#498]
I wasn't sure if I should open an issue about this but I saw that you are using Solid' `createMutable` which is not recommended and is intended mostly for easier transition from libraries with similar APIs. Other than not having read and write segregation it also leads to over subscription. Maybe you guys are aware of that already, just wanted to make sure.

**Comment by trusktr** [comment]
`createMutable` is wonderful. I really love it. Sometimes the DX is more worth a negligible performance. The over subscription only happens in some cases, but Solid has been making progress on this (f.e. Array methods).

**Comment by trusktr** [comment]
Oh, if we're talking about build output though, we may as well use the most optimal output: plain signals whenever possible.

**Comment by orenelbaum** [comment]
Yeah we are talking about build output.

**Comment by samijaber** [comment]
Yeah, we're definitely open to producing the more idiomatic output!


However,  from reading SolidJS docs, it seems like the only other choice is `createStore` + `produce`, which does not map as well to our Mitosis `createStore`. See this Mitosis example:

```jsx
import { useStore } from '@builder.io/mitosis';

export default function MyComponent(_props) {
  const state = useStore({
    list: ['hello', 'world'],
    newItemName: 'New item',
    addItem() {
      state.list = [...state.list, state.newItemName];
    }
  });

  return (
    <div/>
  );
}
```

Which currently becomes this SolidJS code:

```jsx
import { createMutable } from "solid-js/store";

function MyComponent(props) {
  const state = createMutable({
    list: ["hello", "world"],
    newItemName: "New item",
    addItem() {
      state.list = [...state.list, state.newItemName];
    },
  });

  return <div></div>;
}

export default MyComponent;
```

I'm not super familiar with Solid's state management solutions, but it looks to me like far more complicated logic to convert this into a handful of `createStore` instances. 

How would this above example end up looking if it was idiomatic SolidJS?

**Comment by orenelbaum** [comment]
This is the most idiomatic way:

```js
import { createStore } from "solid-js/store";

const [state, setState] = createStore({
  list: ["hello", "world"],
  newItemName: "New item",
});

const addItem = () => setState("list", state.list.length, state.newItemName);
```

You can put `addItem` inside the store, I don't know if it's common among Solid users but I don't think there are any problems with that.

You can also do
```js
const addItem = () => setState('list', produce(l => l[l.length] = state.newItemName));
```

Or less optimally one of those:
```js
const addItem = () => setState('list', [...state.list, state.newItemName]);
const addItem = () => setState(produce(s => s.list = [...state.list, state.newItemName]));
```
Which will update the whole list instead of just a specific position in the array.

Maybe you guys should consider changing Mitosis' API to have read/write segregation and encourage granular mutations cause I feel like it's probably easier in this case to go from a Solid like API to something that is compatible with current API than vice versa, and also cause read/write segregation seems generally like a good practice.

**Comment by steve8708** [comment]
ah yes, alternatively we can also use signals too. what I like about createmutable is support for nested mutation, so similar to what we do for react, svelte, etc we could just have an output using signals (basically identical to our react hooks output except all access is a function call instead of a direct reference

```jsx
const [list, setList] = createSignal([...]);
const [newItemName, setNewItemName] = createSignal("New Item")

return <div><input value={newItemName()} ... />...</div>
```

**Comment by orenelbaum** [comment]
Yeah this is the easiest solution and I think that it's also slightly faster than stores although stores are more idiomatic.

**Comment by samijaber** [comment]
Asked questions in the SolidJS Discord, here's the thread https://discord.com/channels/722131463138705510/751355413701591120/1001192746301788180

We might want to try some of these options:
- find a way to `batch` code (while making sure that code does not access the updated values, which will cause stale content to be used)
- use his `createLiveMutable` implementation
- wrap `useMutable` with a Proxy (as per Fabio's suggestion)

**Comment by steve8708** [comment]
Should we not just use signals? What's the downside to the most simple/idiomatic approach used in solidjs's docs?

**Comment by trusktr** [comment]
It is totally conceivable people can write all their state using `createSignal` (the fastest option), so outputting that would be totally fine.
