### ISSUE TITLE
Angular output has TS code in a JS file

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/mitosis#499]
### To Reproduce

```
yarn
yarn build
```

look at `packages/e2e-app/output/angular/src/components/my-component.js`

```
import { Component } from "@angular/core";

export interface State {
  list: string[];
  newItemName: string;
}

@Component({
  selector: "my-component",
...
```

### Expected behavior

Either emit JS Angular (which is rarely used), or name the file `.ts`.

**Comment by PatrickJS** [comment]
Should be ts

**Comment by kylecordes** [comment]
@PatrickJS my PR in progress makes it so

**Comment by PatrickJS** [comment]
Yeah we use core directly so I think there's a slight disconnect with some changes and the CLI

**Comment by kylecordes** [comment]
When you use core directly, are you taking responsibility yourself for file naming etc.?

I have not dug into the code in core versus CLI, but hopefully there is not different, conflicting output file naming code between them :-) :-(

**Comment by PatrickJS** [comment]
Yeah core just outputs a string so this is more of an issue with the CLI. Mitosis should definitely output ts as the default or at least for angular. We need a way to detect what output we want (ts or js)
