### ISSUE TITLE
Angular component export should not be default

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/mitosis#502]
### Currently

Angular output looks like this:

```
export default class MyComponent {
  list = ["hello", "world"];
  newItemName = "New item";
}
```

Note the "export default". Although this **can** be used, it is very unusual / non-idiomatic in the Angular ecosystem.

### Expected

```
export class MyComponent {
  list = ["hello", "world"];
  newItemName = "New item";
}
```

**Comment by g-cheishvili** [comment]
If you are working on wrapping everything inside NX, it will complain that component is not exported from library, although it is, but because it is default export, it can not understand that

**Comment by alexonaci** [comment]
@kylecordes, @samijaber seems like this doesn't reproduce anymore
