### ISSUE TITLE
Angular component should not import child component

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/mitosis#508]
### Background

When you write a component in Mitosis or many other frameworks, you import a child component you will use.

In Angular, you generally do not do so; you get access to it via a module mechanism whose details aren't important to fix this incremental bug.

### Currently

Write a component that uses another component. In the Mitosis output, the first attempts to import the second (with an incorrect file name).

### Expected

Mitosis Angular output should not import this way, even though the source must.

Here’s an example in the fiddle:

https://mitosis.builder.io/?outputTab=angular&code=import+%7B+useStore+%7D+from+%27%40builder.io%2Fmitosis%27%3B%0A%0Aimport+ItemList+from+%27.%2Fitem-list.lite%27%3B%0A%0Aexport+interface+State+%7B%0A++list%3A+string%5B%5D%3B%0A++newItemName%3A+string%3B%0A++setItemName%3A+any%3B%0A++addItem%3A+any%3B%0A%7D%0A%0Aexport+default+function+MyComponent%28props%3A+any%29+%7B%0A++const+state+%3D+useStore%3CState%3E%28%7B%0A++++list%3A+%5B%27hello%27%2C+%27world%27%5D%2C%0A++++newItemName%3A+%27New+item%27%2C%0A%0A++++setItemName%28event%3A+Event%29+%7B%0A++++++state.newItemName+%3D+%28event.target+as+any%29.value%3B%0A++++%7D%2C%0A%0A++++addItem%28%29+%7B%0A++++++state.list+%3D+%5B...state.list%2C+state.newItemName%5D%3B%0A++++%7D%2C%0A++%7D%29%3B%0A%0A++return+%28%0A++++%3Cdiv%0A++++++css%3D%7B%7B%0A++++++++padding%3A+%2710px%27%2C%0A++++++%7D%7D%0A++++%3E%0A++++++%3Clink+href%3D%22https%3A%2F%2Funpkg.com%2Ftailwindcss%40%5E2%2Fdist%2Ftailwind.min.css%22+rel%3D%22stylesheet%22+%2F%3E%0A%0A++++++%3Cinput%0A++++++++class%3D%22shadow-md+rounded+w-full+px-4+py-2%22%0A++++++++value%3D%7Bstate.newItemName%7D%0A++++++++onChange%3D%7B%28event%29+%3D%3E+state.setItemName%28event%29%7D%0A++++++%2F%3E%0A%0A++++++%3Cbutton%0A++++++++class%3D%22bg-blue-500+rounded+w-full+text-white+font-bold+py-2+px-4%22%0A++++++++css%3D%7B%7B%0A++++++++++margin%3A+%2710px+0%27%2C%0A++++++++%7D%7D%0A++++++++onClick%3D%7B%28%29+%3D%3E+state.addItem%28%29%7D%0A++++++%3E%0A++++++++Add+list+item%0A++++++%3C%2Fbutton%3E%0A%0A++++++%3CItemList+list%3D%7Bstate.list%7D%3E%3C%2FItemList%3E%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D%0A

Visible like so:

![Screen Shot 2022-06-21 at 9 28 29 PM](https://user-images.githubusercontent.com/8799/174930811-69b63478-9660-4434-8620-53898cc6b8ef.png)

**Comment by steve8708** [comment]
oh this is easy, we just need to not forward the import for Angular. we can specifically strip imports ending in `.lite` for angular

**Comment by kylecordes** [comment]
Great !!
