### ISSUE TITLE
BUG: Getting "Variable declaration inside component is ignored during compilation" Lint error on useRef hook

### ISSUE THREAD

**Issue by chadalen** [BuilderIO/mitosis#522]
- [ ] I am interested in helping provide a fix!

**Scope**
- [ ] This impacts ALL Mitosis outputs
- [ ] This only impacts specific generators/outputs (please list them here):

**Describe the bug**
Upon using the `useRef` hook inside a component
e.g
```tsx
export default function SomeComponent(props: SomeComponentProps) {
  const inputRef = useRef();
  return (
          <input
            ref={inputRef}
          />
  );
```

I get lint error
"Variable declaration inside component is ignored during compilationeslint(@builder.io/mitosis/no-var-declaration-or-assignment-in-component)" on line
```tsx
 const inputRef = useRef();
```

**To Reproduce**
See above

**Expected behavior**
Should not be getting this lint error on `useRef` hook

**Screenshots**
![image](https://user-images.githubusercontent.com/12568665/175988566-3d291071-1b6e-4c08-850e-94e6c2ce9e07.png)

**Additional context**
None

**Comment by PatrickJS** [comment]
when we're using `useRef` not as a DOM reference we may also reassign the var. That means Mitosis also supports `let` for this case since Mitosis doesn't use `.current` like react
