### ISSUE TITLE
Feature: compress/shorten mitosis fiddle URLs

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#525]
It would be amazing if we can add some URL shortening capability to our https://mitosis.builder.io/ links. Right now, we just append a `code` query param containing the entire code block, which makes it really rough to share those links.

Any approach to compress the query param would be great

**Comment by puskuruk** [comment]
I searched string compression libraries and I found [lz-string](https://github.com/pieroxy/lz-string). You can find the draft implementation below. Implementation works but I don't have much idea about the string compression and I don't know if it's the best approach.

#578
