### ISSUE TITLE
Fiddle: add TS Support

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#529]
Our Fiddle still does not support TS, even though Mitosis itself knows how to handle it!

<img width="843" alt="image" src="https://user-images.githubusercontent.com/1393142/176569542-29269529-7459-4501-9dc2-41611cf7b489.png">

This is weird because we set `language="typescript"`:

https://github.com/BuilderIO/mitosis/blob/7bc921c4ef53fdaf1b902618aab34f8398c1ad93/packages/fiddle/src/components/Fiddle.tsx#L800
https://github.com/BuilderIO/mitosis/blob/7bc921c4ef53fdaf1b902618aab34f8398c1ad93/packages/fiddle/src/components/CodeEditor.tsx#L146

Not sure where the bug is, but would be neat to get  type coverage in the fiddle!

**Comment by samijaber** [comment]
Ideas from other issue: 

https://github.com/BuilderIO/mitosis/issues/183#issuecomment-1050129752

**Comment by raymondmuller** [comment]
Passing `path="mitosis-file.tsx"` as a prop to <MonacoEditor might bring us one step closer.
Getting other errors now though
<img width="499" alt="Screenshot 2022-08-19 at 15 42 26" src="https://user-images.githubusercontent.com/3808818/185635160-d8dc518c-bf41-4b60-b3c7-5e606bbef501.png">

<img width="517" alt="Screenshot 2022-08-19 at 15 41 28" src="https://user-images.githubusercontent.com/3808818/185635302-8d6cfa76-738b-4ce2-a908-e9da3098de1d.png">

<img width="517" alt="Screenshot 2022-08-19 at 16 01 02" src="https://user-images.githubusercontent.com/3808818/185635575-652cbeb7-810b-4ca4-8d11-e70fa2940de1.png">

.


Missing types.

**Comment by samijaber** [comment]
My thoughts:

- From my NextJS memories, we'd have to add the raw-loader config to nextjs's webpack config to extend it
and from there try to do the `raw-loader` import
- alternatively, looks like the string might be able to be a relative path to the node modules as well: https://stackoverflow.com/questions/43058191/how-to-use-addextralib-in-monaco-with-an-external-type-definition

- also since we have `@builder.io` imports 🤔, we might need to update to a new version of Monaco Editor if ours is before this fix was pushed https://github.com/microsoft/monaco-editor/issues/2295

**Comment by raymondmuller** [comment]
That seems to work :)

**Comment by samijaber** [comment]
Closed by #673!
