### ISSUE TITLE
run prettier CI at the top order during RP check

### ISSUE THREAD

**Issue by decadef20** [BuilderIO/mitosis#538]
- [ ] I am interested in helping provide a fix!

**Scope**
- [ ] This impacts ALL Mitosis outputs
- [ ] This only impacts specific generators/outputs (please list them here):

**Describe the bug**

**To Reproduce**
1.
2.
3.
4.

A link to a https://mitosis.builder.io/ fiddle containing the bug:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by samijaber** [comment]
@decadef20 Can you elaborate on this? What's the issue you're running into?

**Comment by decadef20** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/7866718/177357357-1acae691-b1c6-4d7c-85c1-773daaaaaf72.png">

Sometimes Build CI and test CI passed but lint not. If we put prettier in the first place,  we will find lint error earlier and reduce CI time.
