### ISSUE TITLE
uploading figma json

### ISSUE THREAD

**Issue by noho-glitch** [BuilderIO/mitosis#56]
It's currently not uploading.  I got html to figma extension, downloaded a sites json and then attempted to upload the "page.builder.json" to no avail.  

`react_devtools_backend.js:2430 Format error for file: export default function MyComponent(props) {
  
  

  

  

  return (
    
    )
} {
  "@type": "@jsx-lite/component",
  "imports": [],
  "meta": {},
  "state": {},
  "children": [],
  "hooks": {},
  "name": "MyComponent"
}
overrideMethod @ react_devtools_backend.js:2430
push.687.exports.componentToJsxLite @ main.36112113.chunk.js:7784
_callee2$ @ main.36112113.chunk.js:6668
tryCatch @ 4.d40dd466.chunk.js:266901
invoke @ 4.d40dd466.chunk.js:267131
(anonymous) @ 4.d40dd466.chunk.js:266956
asyncGeneratorStep @ 4.d40dd466.chunk.js:116118
_next @ 4.d40dd466.chunk.js:116140
Promise.then (async)
asyncGeneratorStep @ 4.d40dd466.chunk.js:116128
_next @ 4.d40dd466.chunk.js:116140
Promise.then (async)
asyncGeneratorStep @ 4.d40dd466.chunk.js:116128
_next @ 4.d40dd466.chunk.js:116140
(anonymous) @ 4.d40dd466.chunk.js:116147
(anonymous) @ 4.d40dd466.chunk.js:116136
Rb @ 4.d40dd466.chunk.js:266535
Xb @ 4.d40dd466.chunk.js:266535
Yb @ 4.d40dd466.chunk.js:266536
Ze @ 4.d40dd466.chunk.js:266583
se @ 4.d40dd466.chunk.js:266584
(anonymous) @ 4.d40dd466.chunk.js:266596
Jb @ 4.d40dd466.chunk.js:266775
Nb @ 4.d40dd466.chunk.js:266533
jd @ 4.d40dd466.chunk.js:266588
yc @ 4.d40dd466.chunk.js:266558
hd @ 4.d40dd466.chunk.js:266557
push.exports.unstable_runWithPriority @ 4.d40dd466.chunk.js:266817
gg @ 4.d40dd466.chunk.js:266605
Hb @ 4.d40dd466.chunk.js:266775
gd @ 4.d40dd466.chunk.js:266556
`

`Uncaught (in promise) SyntaxError: Expression expected. (11:5)
   9 |   return (
  10 |     
> 11 |     )
     |     ^
  12 | }
    at e (4.d40dd466.chunk.js:111868)
    at Object.parse (4.d40dd466.chunk.js:111881)
    at Object.parse (4.d40dd466.chunk.js:100463)
    at Xi (4.d40dd466.chunk.js:100463)
    at Yi (4.d40dd466.chunk.js:100463)
    at formatWithCursor (4.d40dd466.chunk.js:100463)
    at 4.d40dd466.chunk.js:100463
    at Object.format (4.d40dd466.chunk.js:100463)
    at push.687.exports.componentToJsxLite (main.36112113.chunk.js:7776)
    at _callee2$ (main.36112113.chunk.js:6668)`

**Comment by steve8708** [comment]
hey @noho-glitch - we just added a new option for the `get code` option in the figma plugin to skip the JSON download and upload altogether - try that out when you can and let us know if that works for you

**Comment by samijaber** [comment]
Closing this as it's stale. If something comes up, please create a new issue over at https://github.com/BuilderIO/figma-html!
