### ISSUE TITLE
Custom classes are rewritten

### ISSUE THREAD

**Issue by jsphs** [BuilderIO/mitosis#58]
I'm testing out the builder at builder.io/fiddle and tried the "Import from:" function.

I imported from: https://getbootstrap.com/docs/5.0/examples/album/

Looking at the HTML/CSS/JS in the "Get Code" viewer, builder.io seems to have replaced all the classes with random div names.

e.g. div class="container" has been changed to div class="div-2", and all the p class tags are also divs.

I also noticed this/a similiar problem with the HTML and CSS when dragging columns into the empty builder.
```<div class="div-1">
  <div class="builder-columns div-2">
    <div class="builder-column div-3">
      <div class="div-4">
        <div class="div-5">
```

I'm pretty new to HTML and CSS, but I'm used to seeing class names like 'container', 'column', etc., and seeing a few classes be reused on multiple divs, as opposed to what the Builder seems to be producing, which is multiple divs each with their own individual class.

**Comment by samijaber** [comment]
@jsphs Closing this issue as it's fairly stale. If it is still persisting, please create a new one with reproduction steps.
