### ISSUE TITLE
Vue: Generate Typescript code

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#582]
Spun out from https://github.com/BuilderIO/mitosis/issues/372

We would have to repeat step 3, but for Vue: https://github.com/BuilderIO/mitosis/issues/372#issuecomment-1133471614

**Comment by raymondmuller** [comment]
I have taken a look at this, but I think the Vue 3 code should first be adapted to the composition API as that will simply things a lot here.

Per the official docs:
> While Vue does support TypeScript usage with Options API, it is recommended to use Vue with TypeScript via Composition API as it offers simpler, more efficient and more robust type inference.

When using Typescript with the Options API

> the runtime props options only support using **constructor functions** as a prop's type - there is no way to specify complex types such as objects with nested properties or function call signatures.

```
props: {
    name: String,
    id: [Number, String],
    msg: { type: String, required: true },
    metadata: null 
}
```

While with the Composition API you get type based declarations
```
const props = defineProps<{
  foo: string
  bar?: number
}>()
```

and also allows you to  move the props types into a separate interface:
```
<script setup lang="ts">
interface Props {
  foo: string
  bar?: number
}

const props = defineProps<Props>()
</script>

```

**Comment by samijaber** [comment]
Hmm, I see @raymondmuller. Thanks for investigating!

Since Vue 2.7 landed recently with support for Composition API, we're open to updating the Vue generator to output Composition API code. We just need to make sure that:
- we support Vue v2 & v3
- we still support the Options API (even if we can't deliver types there, that's fine)

From taking a quick look at the Composition API, we should be able to reuse the vast majority of the code in the Vue generator. 

Created a ticket here https://github.com/BuilderIO/mitosis/issues/653 to track this task
