### ISSUE TITLE
E2E success matrix visible in the README

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/mitosis#606]
Currently, the E2E success is emitted in list/JSON form, to the console and to a file.

Make it appear as a table, with cases on one axis and target on the other.

Make this appear in the README and elsewhere.

The first step is to understand how other tools (like CI tools, coverage tools, etc.) provide the ability to show status on a README, and do something like that.

**Comment by samijaber** [comment]
One process that comes to mind is to write a `generate-matrix` script that:
- reads the JSON
- has a table markdown template that it uses to render a `feature-matrix.md`

And then, in `ci:e2e`, we'd add a final task that runs `generate-matrix` to generate a separate `feature-matrix2.md`, and compare the 2 files using https://nodejs.org/api/all.html#buffer_buf_equals_otherbuffer

So contributors would need to run `generate-matrix` locally to push matrix changes in their PR.

**Comment by kylecordes** [comment]
@samijaber Great idea, I will investigate this path once I have the matrix going.

Preview so far; next step is to list the target names rather than e2e names.

<img width="492" alt="Screen Shot 2022-08-06 at 12 15 01 PM" src="https://user-images.githubusercontent.com/8799/183259166-28e1c9fd-7982-4d9c-9930-6c153e8121cc.png">
