### ISSUE TITLE
[Question] Language mode in VS Code

### ISSUE THREAD

**Issue by CKGrafico** [BuilderIO/mitosis#616]
Hello,
I assume that you're using VS Code as editor, which language mode are you using? my VS Code detects the files a TypeScript React and is "suggesting" some changes related to react.

![image](https://user-images.githubusercontent.com/2048511/183283345-ef34ad8d-cd4b-418d-93a9-b1cc2899630c.png)

**Comment by samijaber** [comment]
You might wanna look here to setup your TS config properly: https://github.com/BuilderIO/mitosis/blob/3a49f94eee09b7396459116dff29f6ab0824d3f2/docs/configuration.md#L5

Otherwise, yeah my VSCode is using `TypeScript React` but it has not caused me any issues so far.

**Comment by CKGrafico** [comment]
Wow that was real helpful, sorry, I've skipped this md

**Comment by samijaber** [comment]
no worries, it's not well-surfaced. will improve docs to point to it
