### ISSUE TITLE
Qwik generator causes side effects to all subsequent generators

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#620]
If `qwik` is added as a target in `mitosis.config.js`, any _subsequent_ target in the array will have its generated code mangled up, with weird qwik-related code that should not be there at all.

Mostly: event handlers end up with `(props, state`  arguments appended to their signature even though they are non-sensical. This code in `svelte`:

```svelte
  <input
    class="shadow-md rounded w-full px-4 py-2"
    value={newItemName}
    on:change={(event) => {
      setItemName(event);
    }}
  />
```

Instead ends up as:

```svelte
  <input
    class="shadow-md rounded w-full px-4 py-2"
    value={newItemName}
    on:change={(event) => {
      setItemName(props, state, event);
    }}
  />
```

note `setItemName` args

**Comment by samijaber** [comment]
@kylecordes If you move `qwik` to the end of the targets array, or run it last, I think that should resolve this issue (which I believe you've seen in e2e tests)

**Comment by samijaber** [comment]
@mhevery Does the Qwik generator have any special `this` or side-effect logic that might cause this to happen?

**Comment by kylecordes** [comment]
@samijaber yes this must be the "if building them all at once, it breaks" I noticed.

I'm wondering if the E2E should randomize the target order each time - so as to surface any future bugs that depend on target order. I had assumed it was just an array because JS lacks a literal Set syntax... the idea that order matters in the config, ouch!

**Comment by samijaber** [comment]
Found the issue: it's a rare instance of forgetting to clone the JSONs before running side-effects on them in a generator.
I added extra safeguards to avoid this happening again in the CLI, so we should be good.

_Eventually_, all Mitosis generators will pre-execution & post-execution logic that is currently copy/pasted across all of them, like:
- cloning JSON
- running user JSON plugins
- collecting CSS
- running prettier
- running user string plugins

Once that skeleton is used we can mostly guarantee no similar issues :D
