### ISSUE TITLE
Angular slot content: invalid HTML

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#635]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=IYOw5grgNsBOQ%3D%3D%3D&code=JYWwDg9gTgLgBAbzgZQDYXgXzgMyhEOAcgAEAjAV2FQBMBTKAOmAgHoRgYIBnYbogNwAoUJFhwAwhAB2MOrLQYp9XPkJFGrAMYy5sgLTd0MfQCtuAD0ZQAhgHdBQp3Qtj49HDYqp4OCtK0YFmkUY2U6AAowfDBuAEpEITg4KDoYCigQiKTkuAAeGmAANwA%2BHNz8qVl5GEUYcLKKiry6uDluIOkAcwBeBALikoAJOlR0PNZC0swSibrGpomqvVqwiHoF5ImphbjhTCEgA

### Expected Behaviour

I think we want:

```angular
  template: `
    <div >
          
    <content-slot-code >
            
    <ng-content> 
      <div>Hello</div>
    </ng-content>
          </content-slot-code>

        </div>
  `,

```

### Actual Behaviour

```
  template: `
    <div >
          
    <content-slot-code >
            
    <ng-content <div>Hello</div>></ng-content>

          </content-slot-code>

        </div>
  `,
```

-> `<ng-content <div>Hello</div>>` is invalid HTML.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/1393142/184886098-9fbf9662-edeb-4f37-bdf9-fdc11f1ff174.png">

**Comment by samijaber** [comment]
cc @PatrickJS

**Comment by PatrickJS** [comment]
@alujs mention he can look into this next week. I'll assign him but if anyone else wants to take this on just mention it

**Comment by decadef20** [comment]
It seems no one works on this. Can I try it?

**Comment by samijaber** [comment]
@decadef20 for sure! go for it
