### ISSUE TITLE
project example basic build vue output with the keyword class

### ISSUE THREAD

**Issue by PengBoUESTC** [BuilderIO/mitosis#688]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgZQBYQO5wL5wGZQQhwDkAAgEYCuwANgCYCmUAdMBAPQjAwQDOwPiQDcAKFGMAHpFhxgAOxjM8AQwDGjOAEkQKgOaMACoTB9EouHDW0VfPgH4AXHD4woCvWMuh9jZ6%2Fd5TwsXYAAvRgd%2FNw8vOBswgE8nOAoICFpGFXk41EZgPVQYFPkqEApmOIxgehhUErKKqDiVWhgAFSli6MDgywp1AGs9Qip5emRwxhSA2JCBtWHR8cN%2BHnZ5GZiguL4oNT5GbpdtvrhbMEY1GAAlFRh2BvLKkLVUOnooRk3nbMS4vA8ADCEEU32OaQyWRyomw4ikMngTFUVDa%2BDG1w22l0BgAFGATHxnDpfMYIKYAJTmSxfGBUKDyOC4kKWAA89GAADcrHYALwIJCQAQPUHOEhfGwPTmMEg4bAAPhZljgrLAwGu9MYiuVOpVoD0St18QgKg5QV5ACIEokLYbda0YPyCeS%2BCwHZ1JDA4UadSp3CoALSETJOwlutoe%2BD2UgEyLg%2B4bWXOMbIhSMejen2WA58fkIO1G8nqHiJMUARhIABoC7q3NlhRsxUW1CW4AAGFgAJjMWUOAYUAYgVBgVZrOqF61FpBUFD4GWHMurWZ1eQKRXLbbbAFJR8vldVaqgN9vd3u4LwwGK22BJKe95k8DArze7z7sJms65EiGBWPlRAKAAKyuGBVgbKdnVMFgFiWIdxkmCI4AAHyQ0gNDBKBXyzADgOuAAxHhnHxMMYJGOCJimc4zD%2BKkULQiBpUwpdl3fP9rFsXMEBIdi7H7HEZTgABqJlINdHizGjWVZWE0SWHEuAxRICkPx9PY1FDF02H4lSjQ4Dg4HaAB5AARQznBARgQAgSjQTkfi4Fs6xgHBP81MOR0EFktyjh03UBAiTivKmPhfMsDhtR9Vk53pDQXH2ZAjg0qDvK9OBwrtVkODVDUvginVPLDC4QLuEU4AAMjKmtmT3dkuT%2FSwvx%2FfMz2VMBTTNPR2nJZxZKK64SvYOAACo4DLTchNIHdmL3ViWpzPN6v3Go6mPKbFssSAFCUKAAFFpUUIlSHkUFF3W%2FBQRgBC%2FFINssLfULlTy5cuNIB62Q4DlOSenVlPEI1WTQTA4AwPJ5H5ABCWTARgEEwUUBUa1qzk2L5X8Wo5PgwBsUtSDwTJb2m5c8akYzgC%2BTEp24%2BcQHkO6jVaAp5C0JQQEOkgAiON46d1CcRXkMUZznWgF25nULyvUXlQfJ8bslywDxW0gxpPQms1XQoZZIZW1pmh7vt1ArNLeD4vnkB7Ms%2B%2FXMsBjAnotrkIopMQ4SAA%3D%3D%3D

### Expected Behaviour

1. `class` is a keyword in js/ts, it should not be use as var or others
2. prop of `class` is not be compiled correctly

### Actual Behaviour

the compile result with    template `:class="_classStringToObject('class-image' + (class ? ' ' + class : '') + ' img')"` ; and without `class` props `  props: [
    "altText",
    "backgroundSize",
    "image",
    "srcset",
    "sizes",
    "aspectRatio",
    "fitContent",
  ],
`

**Comment by PengBoUESTC** [comment]
`let propsDefinition: PropsDefinition<DefaultProps> = Array.from(props).filter(
    (prop) => prop !== 'children' && prop !== 'class',
  );`
filter props class

**Comment by PengBoUESTC** [comment]
`stripStateAndPropsRefs` here just replace `props.` with '',  and doesn't handle keywords

**Comment by samijaber** [comment]
Closed by #698
