### ISSUE TITLE
Types: Mitosis Context missing `Provider` definition

### ISSUE THREAD

**Issue by thedanchez** [BuilderIO/mitosis#706]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [X] Angular
- [X] React
- [X] Solid
- [X] Svelte
- [X] Vue

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgYygUwIYzQYQgO2wA94BfOAMyghDgCIABAIwFdgAbAEzSgDpgIAehDAYEAM7BxdAFAzkBcfACyATzyE0JOAF4U6LLgLEYAHgBKaBVE6mlUYPgDmAGjgZ8qgHxwAPnHwWdnYvAAoEGTgUdmA0QgAuAKD2GVIASjktSFg4bgoMIPgKFnxkGAF8ODxwAjiYAHVRAAsNE1C0xEi4dBgWKErQrqjTNVatGF4ABWoAN2BuKDgZjHYWNB0EJAoICES6JgwoOjhSUi8hqLhTTmAZuEFzy6vBUeNxqdn5nke4DNIZIA%3D%3D

### Expected Behaviour

`Context.Provider` should be recognized

### Actual Behaviour

`Context.Provider` is not recognized.

### Additional Information

I followed the exact instructions outlined here https://github.com/BuilderIO/mitosis/blob/main/docs/context.md. No matter what I do, I cannot get the `Provider` property on the context object to be recognized. Is there a specific version of Mitosis that I need to install??

**Comment by samijaber** [comment]
@thedanchez are you on the `dev` or `latest` version of Mitosis? you want to use `dev`. We should actually start using `latest` because I know many folks get confused by this as well (the docs do not make that clear either)

**Comment by samijaber** [comment]
The types might be lacking for `Provider`, but the JSX parser does handle it correctly AFAIK. Looking at the code that you are sharing, I see the Vue, React, Svelte, Solid code all parses `Provider` properly and sets context. 

Is this just a types issue you are encountering?

**Comment by samijaber** [comment]
For context, for whoever is interested in fixing the types: it's here: https://github.com/BuilderIO/mitosis/blob/2c01f46fdddce0adbd2f3a214375d67da9c94c37/packages/core/src/index.ts#L3

The object is empty. I believe we'll want to add a definition like so:

```ts
function Provider<T>(props: {
  value: T;
  children: JSX.Element
}): any {
  return null;
}

export type Context<T> = {
  Provider: Provider<T>
};
```

This is very hand-wavy, not sure if it's the exact right syntax! Can be inspired by our For/Show/Slot component definitions here: https://github.com/BuilderIO/mitosis/blob/2c01f46fdddce0adbd2f3a214375d67da9c94c37/packages/core/src/flow.ts#L1-L35

**Comment by thedanchez** [comment]
> The types might be lacking for `Provider`, but the JSX parser does handle it correctly AFAIK. Looking at the code that you are sharing, I see the Vue, React, Svelte, Solid code all parses `Provider` properly and sets context.
> 
> Is this just a types issue you are encountering?

It's that and one other thing. I keep getting an error telling me that I'm in violation of https://github.com/BuilderIO/mitosis/blob/main/packages/eslint-plugin/docs/rules/no-var-declaration-or-assignment-in-component.md

This happens whenever I invoke `useStore`.

`const state = useStore({ foo: new CustomObject(props.url, props.apiKey) });`

**Comment by samijaber** [comment]
@thedanchez, ah the ESLint rule has been updated to reflect `useStore` but now published yet. Will do that soon: it's a false positive
