### ISSUE TITLE
Plugins do not receive options

### ISSUE THREAD

**Issue by g-cheishvili** [BuilderIO/mitosis#726]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

Can not

### Expected Behaviour

When you write custom plugins, judging from API of the plugin function, you should get options, but you do not, because all of the generators are just ignoring the third parameter.

Also, the whole point of having plugins that have some kind of order of execution, you should have a result of the previous execution.

My case is that I want to add `styleUrls` to the angular component decorator, but I can not know exactly what component file contents I am working on because I do not have access to the previous `json.post` result and in the `code.pre` I have to parse the content to understand what was the JSON for it.
I hope you get the idea 

### Actual Behaviour

I do not get options in plugins

**Comment by g-cheishvili** [comment]
@samijaber ?

**Comment by samijaber** [comment]
> I do not have access to the previous `json.post` result

You do! Every `json.pre` and `json.post` plugin will include the latest version of the JSON object as its first argument, which will be the result of the previous plugin's transformations.

As for adding an Angular component setting like the `stylesUrl`, one quick way you can modify the generator here: https://github.com/BuilderIO/mitosis/blob/897d6fd73b169fc983b3378b8f0829dd9b6aa518/packages/core/src/generators/angular.ts#L355-L377

to include something like:

```ts
  ${json.meta.angularConfig ?
    Object.entries(json.meta.angularConfig).map(([k, v]) => `${k}: ${v}`).join(',') 
    : ''
  }
```

and then in your plugin, you would set the config to whatever you need:

```ts
const myAngularConfig = {styleUrls: JSON.stringify(['./hero-app.component.css'])}

json.meta.angularConfig = myAngularConfig
```

I believe that would work to pass any additional angular config.

**Comment by g-cheishvili** [comment]
> You do! Every `json.pre` and `json.post` plugin will include the latest version of the JSON object as its first argument, which will be the result of the previous plugin's transformations.

First `json.pre` gets called, then `json.post`, of course, I have access to `json.pre` in `json.post`. The problem is when you need something from `json.post` in `code.pre`. I hope you get it now. 

Also thing about the plugin options, if you look in this file, you'll see that by design, you should get `options`(third param), but in reality it is not passed from anywhere
https://github.com/BuilderIO/mitosis/blob/54faf945c0e210930607298ee3f07867249026af/packages/core/src/modules/plugins.ts#L6

**Comment by g-cheishvili** [comment]
> The problem is when you need something from `json.post` in `code.pre`. I hope you get it now

You(maintainers of this library) will not be able to fulfill every edge case users might need. Since they can move configurations from components to plugins using `useMetadata` hook(can I call it hook by the way?), it is unfortunate that you do not have full access to that passed data in every step, or at least access to previous plugin function calls. Like I described above

**Comment by samijaber** [comment]
> the problem is when you need something from `json.post` in `code.pre`. I hope you get it now.

Ah yes, I get what you mean! Indeed, it would be useful to provide the latest `json` object in the `code.pre` and `code.post` functions. And that's fairly easy to do, we'll need to go here:
https://github.com/BuilderIO/mitosis/blob/54faf945c0e210930607298ee3f07867249026af/packages/core/src/generators/angular.ts#L494-L503

and provide `json` as an additional argument to `runPreCodePlugins` and `runPostCodePlugins`, that is then given to the plugins.
