### ISSUE TITLE
Vue composition API: missing `useRef<T>` generic types 

### ISSUE THREAD

**Issue by findlay-best-wishes** [BuilderIO/mitosis#734]
mitosis component:
```
import { useState } from "@builder.io/mitosis";

interface Props {
  name: string
  age: number
}
export default function MyComponent(props: Props) {
  const [name, setName] = useState("Steve");

  return (
    <div>
      { props.name }
      <input
        css={{
          color: "red",
        }}
        value={name}
        onChange={(event) => setName(event.target.value)}
      />
      Hello! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}
```

the vue-compsition result:
```
<template>
  <div>
    {{ age }}
    {{ name }}
    <input class="input" :value="name" @input="name = $event.target.value" />
    Hello
    {{ name }}! I can run in React, Vue, Solid, or Liquid!
  </div>
</template>

<script setup>
import { ref } from "vue";

const props = defineProps(["age", "name"]);
const name = ref("Steve");
</script>

<style scoped>
.input {
  color: red;
}
</style>

```
Hope to support vue3-composition-types feature. Such as `defineProps<T>`, `ref<T>`and so on. I am also interesting to implement the feature.

**Comment by samijaber** [comment]
Thank you for offering to help implement this!

We actually recently implemented this for `defineProps`: https://github.com/BuilderIO/mitosis/blob/54faf945c0e210930607298ee3f07867249026af/packages/core/src/generators/vue.ts#L826-L846

It does work, but you need to enable the config `typescript: true`. We just added support for it in our fiddle https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFATgAO3xQSOAMYEACuTCpEEuHBk4Q6AFxxUMKLIDmOuDkvG9yEHXYTCE9AA9IsOG0XITPAkyDJKMNwycACyAJ4AwhSQMuhyABRgGqgm6hCaAJTaukoQMmZwANr6hgA0pugwAHIG6AC6cAC8KBjYeOhpVNjoAG7oVPmSNlANyFBRaTa6ADwswMMAfIu6iHCZeagc1QTu29tLsmDIMFunSqioHQgIN6dwJUzQJlTTLFQ1L7pCCdXrphjgmMh0I8jsCQaV4gALHAyeyPNIjVIwQoddb1JotdGjOQcXBQewwDhgiHofKw7Y8TYggAS6CYHwAhHAAJJvZFwKChOCyOAAJXQyhgdQAapC6pgIExgCw6tA4AAZYAAR0YLHZWyWPFWGxsEzcQA%3D%3D%3D


However, we still don't have types for refs. To add them:
- we set the `useRef()` call here https://github.com/BuilderIO/mitosis/blob/54faf945c0e210930607298ee3f07867249026af/packages/core/src/generators/vue.ts#L883
- You can see how we find the stored type parameter, and add it in the React generator here: https://github.com/BuilderIO/mitosis/blob/54faf945c0e210930607298ee3f07867249026af/packages/core/src/generators/react/generator.ts#L262-L272

So you will want to imitate this logic for the Vue generator. Make sure to also add a `options.typescript` check: we do not want to set the generic if `typescript === false`

**Comment by findlay-best-wishes** [comment]
> 

Ok，i will try it

**Comment by decadef20** [comment]
It seems it's already been done but the fiddle doesn't keep up to date.

**Comment by samijaber** [comment]
@decadef20 not quite: we still have not added support to the generic for `useRef<T>`. The fiddle is always up to date with our generators.

**Comment by decadef20** [comment]
I'll try it later.
