### ISSUE TITLE
Angular generated code misses default imports

### ISSUE THREAD

**Issue by ocombe** [BuilderIO/mitosis#746]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFChIsRHDYkcyJvByo4AIWQxBAOyKlylKhx4MdEXeIkSAxpdQQm6DkwgBzABRaLugJQ26AAeMvAKSiqkyLq2MNz6ALIAngDCFJC66LownmDkYKh%2BiBJwcPa6qPAA2ro4IOgANHAYMABydegAunAAvCgY2HjonlTY6ABu6FR%2BkiVwUOgwyFD6nnOlADw%2BegB866VwABLoTG4AhHAAkmU4%2BlDRcMD6AEroOLFNAGrIjXCYTsAWE1oHAADLAACOjBYZ32Gx420se1KMwkhCAA

### Expected Behaviour

Import default from another file should work with the Angular generator

### Actual Behaviour

Whenever I add a default import from another file, it generates the code just fine in react but not in Angular. The following imports will be removed in Angular:
```ts
import { default as Button } from "./button";
import Button from "./button";
import * as Button from "./button";
```

Whereas the following import works just fine and is present in the generated code:
```ts
import { Button } from "./button";
```

It seems to work on mitosis.builder.io but it doesn't work for me with the latest version of mitosis.
If I set "standalone" to true in the generator options then the import it correctly retained in the generated file.

### Additional Information

This is particularly annoying because Mitosis requires default exports, which means that if I want one mitosis file to import from another mitosis file it will not work and I will have to create a non default export in an intermediate file (that imports default from the first and re-exports it as a named export).

**Comment by ocombe** [comment]
After looking at the code, it seems that mitosis does this on purpose: https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/generators/angular.ts#L352
But I'm manually generating the module file, and I don't want mitosis to remove those imports (and I don't want to use standalone components either as I might be using v12 of Angular as well). I think this should be optional at least until you provide an option to generate the modules.

**Comment by samijaber** [comment]
@ocombe I'm no Angular expert, so not familiar with the nuances of this bug. Would it work for you if we were to add a `preserveImports: boolean` config that defaults to `false`, which you can then set to `true` in your `mitosis.config.js`?

If so, here's how to go about adding it:
- add it here: https://github.com/BuilderIO/mitosis/blob/237826192dfbb1bbfb224db0373b81082b4df8c8/packages/core/src/generators/angular.ts#L36
- add a `DEFAULT_OPTIONS` object and add it to the user-provided options here: https://github.com/BuilderIO/mitosis/blob/237826192dfbb1bbfb224db0373b81082b4df8c8/packages/core/src/generators/angular.ts#L225-L229

```ts
const DEFAULT_OPTIONS = { preserveImports: false }
const options = { ...userOptions, ...DEFAULT_OPTIONS}
```
 
- change `excludeMitosisComponents: !options.standalone` to `excludeMitosisComponents: !options.standalone && !options.preserveImports`

**Comment by ocombe** [comment]
yes, that sounds great
