### ISSUE TITLE
Angular external component selectors are not converted

### ISSUE THREAD

**Issue by ocombe** [BuilderIO/mitosis#747]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=IYOw5grgNsBOQ%3D%3D%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFChIsRHACSAYwgA7IqXKUA5DRABPZeBwq9PYMpVbJE9AA8Z8NiRzIm8EshWKY3NQFk9AGEKSBV0FRgACjByMFQASkQJODgLVHgAbRUcEHQAGjgMGAA5HPQAXTgAXhQMbDx0SKpsdAA3dCp46xSodBhkKDVI5JS4AB4WYFaAPhHR8aVVHln5sZ5JmZGuiUIgA%3D

### Expected Behaviour

Mitosis should convert the components names into the correct angular selectors when importing from external modules

### Actual Behaviour

I import from an external mitosis module, but it doesn't convert the components into their correct angular selectors.

The mitosis code:
```tsx
export default function Icon(props: IconProps) {
  return (
    <i
      data-testid="icon"
  ></i>
  );
}
```
gets turned into this angular code
```ts
@Component({
    selector: "icon",
    template: `
    <i data-testid="icon"></i>
  `,
})
class Icon {
}
```

and the mitosis button code that imports Icon:
```tsx
export default function Button(props: ButtonProps) {
  return (
    <button
      data-testid="button"
    >
        <Icon />
    </button>
  );
}
```

is transformed into this angular code:
```
@Component({
    selector: "button",
    template: `
    <button
      data-testid="button"
    >
          <Icon></Icon>
    </button>
  `,
})
class Button {
}
```

Notice that in the last angular template it's using `Icon` instead of `icon` (lowercase) which is the correct selector.
Whereas when I'm importing from a local mitosis file, it does use the selectors correctly (probably thanks to https://github.com/BuilderIO/mitosis/pull/357)

### Additional Information

Angular generates the following error because even if I'm correctly importing the Icon module, it doesn't know any angular component with the selector `Icon` since the correct selector is `icon`:
```
index.js:1 NG0304: 'Icon' is not a known element:
1. If 'Icon' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

The solution could be to generate an additional selector with the exact class name on top of the regular kebab-case selector here https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/generators/angular.ts#L365 which would give something like that (I tested and it works fine for me with this change):
```ts
@Component({
    selector: "my-cmp, MyCmp",
    template: `
    <i data-testid="icon"></i>
  `,
})
class MyCmp {
}
```

**Comment by samijaber** [comment]
@ocombe I'm open to the selector solution you suggested! You already pointed to the right part of the code, feel free to put up a PR adding a `json.name` 👍🏽

**Comment by ocombe** [comment]
Sounds good, @PatrickJS do you see any reason why we shouldn't do that ?

**Comment by PatrickJS** [comment]
this might be a problem of detecting which imports are components in the template and correctly transforming the component name

**Comment by samijaber** [comment]
This should've been closed by @alujs 's PR, so I'm doing so now. Feel free to repoen if there's still something missing?
