### ISSUE TITLE
`<path>` in Svelte is improperly transpiled

### ISSUE THREAD

**Issue by rootEnginear** [BuilderIO/mitosis#753]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [X] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=M4NwpgNgLmQ%3D&code=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnALICeAwhALaR7B4wAUAlHAN4BQccKMBjoo5NvwFwAPAGcAbgHM4IepjyyAvACIAFjBhgAXAHoTAd0sA6cwGYr0RSYBMABncmFi7XGTFMmDp4ZMA%2B8sTA5gBCECA6rnAJzgAscCk%2BsjBQEADWwAC05sQIMLo6AIxWAKwZWbnAOgSiQqx0mNDaAHySUjJgqKVwmdl5%2BZjEzASoYDrZ%2BAi1IwXjzABWEBOzEPM%2BCDoUzuVwABxWzlUErvnOVsnHVddWrgCcz%2FnJ1e9WAGzHx18PSrPWxVRL5exVZ4AdjglXKzm%2BX1s8LSVihtls%2BTR5UBP1cUMetihBJu6MxH2RmNJGJoVSsR3sUNBtjgdKh32ZJzOFwSULOzjgz1hAqF8Nkbw%2BUOOgvy8IAXj4TN1etJPEplXAOABuXgAXyAA%3D%3D%3D

### Expected Behaviour

The output of `<path>` element should be:
```html
<path
  stroke-linecap="round"
  stroke-linejoin="round"
  d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
/>
```

### Actual Behaviour

Mitosis outputted `<path>` element as `<svelte:component this={path}>`.
```html
<svelte:component
  this={path}
  stroke-linecap="round"
  stroke-linejoin="round"
  d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
/>
```

**Comment by samijaber** [comment]
Ah, we are checking against a list of valid HTML tags here: https://github.com/BuilderIO/mitosis/blob/2ec674ade37d0e1db19df5ebd4130c9d78fb4fc2/packages/core/src/generators/svelte.ts#L160

However, this list does not include SVG tags! We need to add a hardcoded list of SVG tags (you can get the complete list of SVG tags from here: https://developer.mozilla.org/en-US/docs/Web/SVG/Element#svg_elements_a_to_z), and then add a check that the list does not include the `json.name`
