### ISSUE TITLE
Build with config typescript react file extensions still .js

### ISSUE THREAD

**Issue by kingzez** [BuilderIO/mitosis#763]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [X] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://github.com/BuilderIO/mitosis/blob/main/e2e/e2e-app/mitosis.config.js#L46

### Expected Behaviour

add `typescript: true` to mitosis.config.js the part of react

```js
/**
 * @type {import('@builder.io/mitosis'.MitosisConfig)}
 */
module.exports = {
  files: 'src/**',
  targets,
  // Each run needs a separate output dest, as Mitosis clears it first.
  dest: [outputDir],
  options: {
    react: { transpiler: { format: 'esm' }, typescript: true },
    solid: { transpiler: { languages: ['ts'] } },
    vue2: vueConfig,
    vue3: { ...vueConfig, api: 'composition' },
  },
};

```

Expected Behaviour：the output file extension should be .tsx

### Actual Behaviour

the output file extension is .js

**Comment by samijaber** [comment]
Closed by #764
