### ISSUE TITLE
Vue: (Options API) functions refs missing this. prefix

### ISSUE THREAD

**Issue by CKGrafico** [BuilderIO/mitosis#780]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=M4NwpgNgLmQ%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNroDQoYBK6AZnhAHYCyEyl8AvnKVBCHAEQACARssAA2AE3RQAdMAgB6EMBypgqTgG4AUGvQAPSLDijSAQ2SD4pegGMYUynGoBPAMLtIldAwAUYNmFQBKRDU4OAsqVHhgSjBkGBJSOABeQnQ4jz91IJCw%2BHDDGHRE5OxcDwRM4MpDEHQALi5sdAA3dE48crgqACFBZCg0wODBuEjo2LJxUggLNDT2xjahgHN0eEEIAHcxR0MMADkq9H6yoeCoFd7bXPzxSurxHAAZDa2dw%2FS5zMZ3tXNKKxs4IYjplDIIxDAPAAmd6MDQdGh0Tz9BIAPgGwVB4I8AEZ3kMgXi4F8MnC4GcYBc4B52gAeYTARpwFHtYIIbwQXziVAACw2AEkojE4AAyYVUlmDGkjGISoZnUgJBDSsakWEnE4WVCoRXHdUaiBrKB1ThnYStWWDRhqvXBRqg5DoRVXdA3A7Wm1dHpQRUeJruGABVFwZ3iT29NLuvVURzcwyUZY%2Bv0MQNopAh24FJJJmD3QxQZY5u09ApWi3SZnqvyR4IACXQgjWEoQIbWmyg2z2boAhHA%2BSE42T6MNbCRDFYCAA1B0ETAG4DCAjQOAPYAARwEwi7tOk9MaFbgMKAA%3D%3D

### Expected Behaviour

If I call a function from `onMount` hook I expect to be called.

### Actual Behaviour

is not calling it

**Comment by raymondmuller** [comment]
If you declare the functions in useStore, it works as expected.

See: https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNroDQoYBK6AZnhAHYCyEyl8AvnKVBCHAEQACARssAA2AE3RQAdMAgB6EMBypgqTgG4AUGvQAPSLDijSAQ2SD4pegGMYUynGoBPAMLtIldAwAUYNmFQBKRDU4OAsqVHhgSjBkGBJSOABeQnQ4jz91IJCw%2BHDDGHRE5OxcDwRM4MpDEHQALi5sdAA3dE48crgqACFBZCg0wODBuEjo2LJxUggLNDT2xjahw36yoeDDQTEYDwAmdLmFwYBzdHhBCAB3MUdDDAA5KvRl9uCoE97bXPzxSurxHAAZC5XG6PPZDRiZRh7DQdGh0Tz9BIAPgGcHWmw8AEYwXBPuhxEs9lCMjC4K8YO84B52gAeYTARpwJHPRDeCC%2BcSoAAWFwAklEYnAAGRCqks4I0kYxcWDV6kBIIKVjUgQ1arCyoVAKlZq9UQM5QOqcV7CVoy4KMVW64KNdbIdAKvHfB5W61dHpQBUeJruGABZG4mB5fHu3ppV26qiOLmGSjHL0%2Bhj%2BlFIJ0%2FApJRMwP6GKDHbO2noFS0y6TMtV%2BCPBAAS6EEZxZCCdZ0uUGudxdAEI4LyQrGyfRhrYSIYrAQAGr2giYfXAYQEaBwf7AACOAmEndp0npjXLcCJQA
<img width="1330" alt="Screenshot 2022-10-06 at 22 05 31" src="https://user-images.githubusercontent.com/3808818/194408179-52ba9e2b-7b31-477e-9c52-ade53b0f2a6e.png">

**Comment by samijaber** [comment]
The shared example works for Vue's Composition API.

The current issue is that Vue's Options API will place all methods in its `methods` property, so we need to prefix the function calls with `this.` prefixes.

The place to do this is `processBinding` https://github.com/BuilderIO/mitosis/blob/a762948e6014450d5b8b80c961b771df4568f847/packages/core/src/generators/vue/helpers.ts#L116

We'll want to add a step to the effect of:


```ts
(code) => {
  const allMethodNames = Object.entries(json.state).filter(
    ([key, value]) => value?.type === 'function' || value?.type === 'method',
  ).map(([key]) => key);

  if (options.api === 'composition') {
    return replaceIdentifiers({ code, from: allMethodNames, to: name => `this.${name}` })
  } else {
    return code
  }
}
```

This will identify all functions & methods described in the component, and if any of them are referenced directly within a code block, those references will get a `this.` prefix added to them.
