### ISSUE TITLE
Wondering about a `stable` release timeline? 🙂 

### ISSUE THREAD

**Issue by theiliad** [BuilderIO/mitosis#786]
Hi, thank you for all your efforts!
Just wondering what the timelines/plans for this are, and how close you are to a stable release? 🙂

**Comment by samijaber** [comment]
We're in the thick of it right now improving our generators and core abilities. I haven't had time to think about what a `stable` release would look like in terms of feature coverage yet 😄. Definitely something we need to think about for the community to track though! We have a V1 Github project but it's not super up-to-date https://github.com/orgs/BuilderIO/projects/4

**Comment by theiliad** [comment]
> We're in the thick of it right now improving our generators and core abilities. I haven't had time to think about what a `stable` release would look like in terms of feature coverage yet 😄. Definitely something we need to think about for the community to track though! We have a V1 Github project but it's not super up-to-date https://github.com/orgs/BuilderIO/projects/4

Thanks for the context!

**Comment by theiliad** [comment]
@steve8708 @samijaber Hello 👋🏻 
Just doing another check-in here

You're doing a lot of great work! And I'm wondering how far we now are from a stable release 🙂

**Comment by samijaber** [comment]
Still no timeline on a stable release, so wouldn't be able to give you a concrete answer at this time.

Going to go ahead and close this issue since there isn't more information I can provide for now, but keep an eye out for progress as we announce it on Twitter/Discord. 😄
