### ISSUE TITLE
Context files are imported as js files even when using typescript output

### ISSUE THREAD

**Issue by cmgriffing** [BuilderIO/mitosis#792]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [X] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [X] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://github.com/cmgriffing/mitosis-issue-examples/tree/main/apps/context

### Expected Behaviour

I linked the above repo since it requires multiple files and I could not figure out how to do that with mitosis.builder.io.

The mitosis config in that file shows typescript enabled for all outputs.

It should show be:
```
import Context from "./custom.context";
```

### Actual Behaviour

All of the files importing the context have:
```
import Context from "./custom.context.js";
```

**Comment by samijaber** [comment]
That's actually a non-issue, and (I know this is going to be shocking), but it is the _DESIRED_ behaviour by the ESM spec.

If you have a TS file called `custom.context.ts`, then:

- you CANNOT import it by providing `.ts` extension: `import Context from "./custom.context.ts"` will not work. See https://bobbyhadz.com/blog/typescript-import-path-cannot-end-with-ts-extension
- you CAN import it by providing ` .js` extension `import Context from "./custom.context.js"` will work even though the file is called `custom.context.ts`
- the ESM spec [requires that you provide extensions for every relative import](https://nodejs.org/api/esm.html#mandatory-file-extensions). Therefore, it is more error-proof to provide the `.js` extension for your TS extensions than not.

😄

**Comment by cmgriffing** [comment]
Interesting. Sorry about that. I am less familiar with ESM.
