### ISSUE TITLE
Svelte props should be $$props

### ISSUE THREAD

**Issue by cmgriffing** [BuilderIO/mitosis#793]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [X] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=M4NwpgNgLmQ%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFAT0AD0iw4bEjmRN4JZADsAxjG6a4AWQCeAYQqRN6TTAAUYcmFQBKRBLhxtETangBtTRwQdAAaOAwYADkg9ABdOABeFAxsPHRbKmx0ADd0KmdJdzgodBhkKANbIo8AHhZgbIA%2Bao84GuBNMGQYFtbPVFQEhARevs8IJmgALmoSlioQ0Y9CQiW4bJwmZHQhwODVsdbvUwALHE0Acx2EWxzrGFcExvDS6ODb3JsOXCgrmA4Nlt0M4DodEBwIQ4IE5QX0eM1DgAJdBMSYAQjgAElPOdilo4B04AAldA4XRhABq2zCmAmwBYYWgcAAMsAAI6MFholo1Hj1JpFAoSQhAA%3D

### Expected Behaviour

Svelte should pass props as `{...$$props}`. It is unrecommended by the Svelte team, but it is the only option for generic props spreading.

### Actual Behaviour

Svelte is passing props as `{...props}`

**Comment by cmgriffing** [comment]
I am told that `$$restProps` might be a better option for the output.

**Comment by samijaber** [comment]
This can be fixed by adjusting this logic here: https://github.com/BuilderIO/mitosis/blob/3cdd4899d0bd0ca7afaee886a6216de4052cd89c/packages/core/src/generators/svelte.ts#L226-L228

so that, `if (_spread.code === 'props')`, we instead return `$$props`

**Comment by cmgriffing** [comment]
Cool. I should have some time to get to it this weekend if you haven't started on it yet.

**Comment by raymondmuller** [comment]
https://github.com/BuilderIO/mitosis/pull/797 here you go
