### ISSUE TITLE
useLocalObservable needs an Observer wrapper in the jsx

### ISSUE THREAD

**Issue by cmgriffing** [BuilderIO/mitosis#794]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [X] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN0A0KG206cAvnAGZQQhwBEAAgEbLAA2AJulAHTAIAehDAYEVMFSMA3ACh56AB6RYcXtRzJO8asgB2AYxhCDcALIBPAML1IB9AZgAKMHTCoAlInlw4RhAGqPAheOQAvMRYElDoLgh%2B%2FjQQEABcTKw4UIxJFF6K%2FnEwyFDmLkn%2BADzcwABuAHyVyVXABmDIMM3JAaioEQiJPcMBEJzQGYxx3IwE3ckUFPPCTSMAEuic4wCEcACSATjmUIZwbXAASug4JkQAasiEcJhjwNxE0HAAMsAAjhzcbbNKrCWqNJJeBQUIA%3D%3D

### Expected Behaviour

The component should be wrapped in an `observer` or the jsx content should be wrapped in an `Observer` .

```
const MyComponent = observer(() => (props: any) {
  const state = useLocalObservable(() => ({ foo: "bar" }));

  return (
    <>
      <div>
        <input className="input" />
        Hello! I can run in React, Vue, Solid, or Liquid!
      </div>
    </>
  );
});

export default MyComponent;
```

OR

```
  return (
    <Observer>
      {() => (
        <div>
          <input className="input" />
          Hello! I can run in React, Vue, Solid, or Liquid!
        </div>
      )}
    </Observer>
  );
```

### Actual Behaviour

There is no `observer` or `Observer`. This means that the component does not rerender when the `localObservableState` changes

**Comment by samijaber** [comment]
Thanks for catching this! I would prefer if we wrap the whole component in `observer`, as the `Observer` component is being deprecated by the `mobx` lib

To do so, we would need to go here: https://github.com/BuilderIO/mitosis/blob/3cdd4899d0bd0ca7afaee886a6216de4052cd89c/packages/core/src/generators/react/generator.ts#L522-L604

and add an optional `observer(` and `)` before and after this code if `stateType === 'mobx'`. Also, we'll want to add `observer` as an import on https://github.com/BuilderIO/mitosis/blob/3cdd4899d0bd0ca7afaee886a6216de4052cd89c/packages/core/src/generators/react/generator.ts#L512-L513

**Comment by cmgriffing** [comment]
Cool, I will look into this over the weekend.
