### ISSUE TITLE
Builder.io in Fiddle is not working

### ISSUE THREAD

**Issue by raymondmuller** [BuilderIO/mitosis#802]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

Anywhere

### Expected Behaviour

It should load 

### Actual Behaviour

It doesn't load

### Additional Information

I keep seeing this in the fiddle

<img width="1361" alt="Screenshot 2022-10-07 at 18 47 59" src="https://user-images.githubusercontent.com/3808818/194606111-7534b97b-3cb6-4b64-9061-eb7fcf2be055.png">

<img width="767" alt="Screenshot 2022-10-07 at 18 48 18" src="https://user-images.githubusercontent.com/3808818/194606182-f9b6a6ce-6c7d-48eb-ad6c-72222ecab7a5.png">

**Comment by steve8708** [comment]
doh, thanks for reporting @raymondmuller! just fixed locally, we'll get the fix deployed on our next working day (this upcoming tuesday)

**Comment by raymondmuller** [comment]
Seems to work again. Closing this :)
