### ISSUE TITLE
Wrong import on generated file

### ISSUE THREAD

**Issue by fbovo** [BuilderIO/mitosis#809]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [X] Qwik
- [X] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://codesandbox.io/s/dazzling-panka-9d6jm2?file=/output/qwik/src/20221010-1/index.ts

### Expected Behaviour

Importing a component file (.lite) on a **non-component** file, generates a file which contains a wrong extension (.jsx).

source index.ts

```
import ChildComponent from "./ChildComponent.lite";
import ParentComponent from "./ParentComponent.lite";

export { ChildComponent, ParentComponent };
```

What is supposed to be generated is an index.ts file like:

```
import ChildComponent from "./ChildComponent";
import ParentComponent from "./ParentComponent";

export { ChildComponent, ParentComponent };
```

### Notes:

This won't happen inside a component file, where the import is as expected.

Prerequisite: Mitosis with TS output:

```
module.exports = {
  files: "src/**/*",
  options: {
    qwik: {
      typescript: true
    },
    react: {
      typescript: true
    }
  },
  targets: ["react", "qwik"]
};
```

### Actual Behaviour

generated index.ts
```
import ChildComponent from "./ChildComponent.jsx";
import ParentComponent from "./ParentComponent.jsx";

export { ChildComponent, ParentComponent };
```

### Additional Information

I believe the problem is genereted by the logic on [extensions helper](https://github.com/BuilderIO/mitosis/blob/ad117b1ef745bf470eb1b5a7b7f3120b64ba6073/packages/cli/src/build/helpers/extensions.ts#L34)

**Comment by R-Bower** [comment]
Wrote a simple script as a stopgap for the time being.  I run it after every `mitosis build`.  

```
// see: https://github.com/BuilderIO/mitosis/issues/809
import {readdir, readFile, writeFile} from "fs/promises"
import path from "path"

async function resolveExports(dir: string): Promise<any> {
  const files = await readdir(dir, {withFileTypes: true})
  return Promise.all(
    files.map(async (file) => {
      if (file.isDirectory()) {
        return resolveExports(path.join(dir, file.name))
      } else if (file.name === "index.ts") {
        const filePath = path.join(dir, file.name)
        const contents = await readFile(filePath, {
          encoding: "utf-8",
        })
        return writeFile(filePath, contents.replaceAll('.lite"', '"'), {
          encoding: "utf-8",
        })
      }
    }),
  )
}

resolveExports(path.resolve(__dirname, "../packages/react/src/generated/src"))
```

**Comment by samijaber** [comment]
I don't see the bug when I go to https://codesandbox.io/s/dazzling-panka-9d6jm2?file=/output/qwik/src/20221010-1/index.ts

The output in Qwik's and React's `index.ts` is:

```ts
import ChildComponent from "./ChildComponent.jsx";
import ParentComponent from "./ParentComponent.jsx";

export { ChildComponent, ParentComponent };
```

Providing an explicit `.jsx` extension when the file is `.tsx` is valid, and in fact _recommended_ for your code to be ESM compliant:
- ESM spec requires explicit extensions: https://nodejs.org/api/esm.html#mandatory-file-extensions
- TypeScript requires that you use `.jsx` when pointing to a `.tsx` file, and `.js` when pointing to a `.ts` file. TS does not accept `.ts` and `.tsx` extensions in paths by default. 
  - https://www.typescriptlang.org/docs/handbook/esm-node.html#type-in-packagejson-and-new-extensions
  - https://bobbyhadz.com/blog/typescript-import-path-cannot-end-with-ts-extension

Combining the above two facts means that generating an import pointing to `ChildComponent.jsx` is the correct thing to do.
