### ISSUE TITLE
onUnMount is not defined

### ISSUE THREAD

**Issue by jobizzness** [BuilderIO/mitosis#81]
When using `Edit content JS + CSS` in builder, onMount work well but getting an onUnMount error when trying to do clean-ups.

```
let sub;
let categoriesSub;

onMount(() => {

    if (typeof Sellox === 'undefined') return;
    Sellox.loadFirestore().then((_) => {
        // get data
        sub = Sellox
            .Shop
            .getProducts()
            .subscribe(products => {
                state.products = products.map(item => {
                    item.image = getThumbnail(item)
                    return item;
                });
            });

        categoriesSub = Sellox
            .Shop
            .getCategories()
            .subscribe(
                categories => state.categories = categories
            )
    })
})
onUnMount(() => {
    sub && sub.unsubscribe();
    categoriesSub && categoriesSub.unsubscribe()
})
```

![1](https://user-images.githubusercontent.com/14133399/111854570-bb074100-8917-11eb-9054-b5a7064b0388.PNG)

**Comment by PatrickJS** [comment]
this is supported

https://mitosis.builder.io/?outputTab=react&code=import+%7B+useState%2C+onUnMount%2C+onMount+%7D+from+%22%40builder.io%2Fmitosis%22%3B%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++const+%5Bname%2C+setName%5D+%3D+useState%28%22Steve%22%29%3B%0A%0A++onMount%28%28%29+%3D%3E+%7B%0A++++console.log%28%27onMount%27%29%3B%0A++%7D%29%3B%0A%0A++onUnMount%28%28%29+%3D%3E+%7B%0A++++console.log%28%27onUnMount%27%29%3B%0A++%7D%29%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3Cinput%0A++++++++css%3D%7B%7B%0A++++++++++color%3A+%22red%22%2C%0A++++++++%7D%7D%0A++++++++value%3D%7Bname%7D%0A++++++++onChange%3D%7B%28event%29+%3D%3E+setName%28event.target.value%29%7D%0A++++++%2F%3E%0A++++++Hello%21+I+can+run+in+React%2C+Vue%2C+Solid%2C+or+Liquid%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D
