### ISSUE TITLE
ESLint Rule: no ternaries in JSX render body

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#811]
We want to encourage folks to use the `<Show>` component instead of ternaries (`foo ? <bar /> : <baz />`). The latter doesn't always work across all generators, especially once they start getting nested inside of each other in complex ways.

**Comment by samijaber** [comment]
cc @sahilmob would you be interested in looking into this one? 👀

**Comment by sahilmob** [comment]
Sure. Please assign to me.
