### ISSUE TITLE
Vue: duplicate v-bind when spreading multiple attributes

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#816]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnALICeAwhALaR7B4wAUYUEYAzgJRwA3gCg4cKMBjoo5NmPlwAPMTxh08QQDptnbj03IIEAL5Dtm3b00AjVFFMB6AHxw%2BAbmHGgA

### Expected Behaviour

We need to combine the `v-bind` objects. Something like this: https://sfc.vuejs.org/#eNo9j82OwyAMhF/F8iWXBtRrlFba2z4El/zQJg1ghEm3q4h3X7N/F+TxMJ/GB77FqJ67xQ57ntIaM7DNe7yaMFHgDC+4wAGcP53tZGjGYdruifYwtxM5Sk0HTbJzU8pfYvtOrLMYN6IGxOj1D1uoIrL10Q3ZigLolzM823EN88XgoZR6nUDerRi8vlvnqNfLWX72+j+GJ1x9pJRbP0T1YArS/qgw82uwQSlbN3Un51VtcMk5cqc136Z684MVpbuWSaU95NVbZdm3Y6IPtknABitC+hcsX7KiZJw=

```vue
<script setup>
const x = { style: { 'background-color': 'red'}}
const k = { id: 'foo' }
</script>

<template>
  <h1 v-bind="{...x, ...k}">Hello</h1>
</template>
```

### Actual Behaviour

https://sfc.vuejs.org/#eNpFj82OwyAMhF8F+ZLLBtRrRCvtbR+CS0JoQwMYYdLtKsq7r9nfm8fj+eTZ4TVn+dgcDKDJFp+rIFe3fDHJYqIqnuIsdkH1I7iBh24a7XoruKW5txiwdIPoipu74/hNrF8JP7NxRewEG1p9s5nKorqYw1gdKyH0chKPfvJpPht4GvgXq4HLmwsBtVpOfKvVXxBewMeMpfZxzPJOmPj/veHMj0EG+N22aTsu2LSBpdZMg1J0ta31nSSWm+JJli1VH510FPup4Du5wmADDcENDjg+AdTaZd0=

We get an error:
`(7:18) Duplicate attribute`

```vue
<template>
  <input v-bind="foo" v-bind="bar" />
</template>

<script>
export default {
  name: "my-component",

  props: ["foo", "bar"],
};
</script>
```

**Comment by samijaber** [comment]
cc @raymondmuller

**Comment by raymondmuller** [comment]
https://github.com/BuilderIO/mitosis/pull/817 < fix
