### ISSUE TITLE
CallExpressions in useStore don't work

### ISSUE THREAD

**Issue by raymondmuller** [BuilderIO/mitosis#834]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNrrgXzgDMoIQ4AiAAQCNlgAbAE3SgDpgIB6EYHVYKgoBuAFCj0AD0iw4LIgENkDeEWQA7AMYxO6uAFkAngGEykdenUwAFGFJhUASkSi4cTRHWp43hTDwAvCgY2LjWCK5ucDog6ABccBYA7nAAIn7o1o5sOAAyEJoKDOgAKqBYMFDA6gDmWZH4jmJukVDoMMhQetaRbgA8TMAAbgB8vVElABZ4MXiCiL7%2BOeX4431cg6ORTaL4QA

### Expected Behaviour

We should check for this and handle it.

### Actual Behaviour

It breaks

**Comment by decadef20** [comment]
I'll look into it later.

**Comment by samijaber** [comment]
That's actually (at least partially) by design. I need to chat w/ @steve8708 about why we have this limitation, and whether there are certain web frameworks that make this a hard requirement or not.

**Comment by raymondmuller** [comment]
Works now! closing :)
