### ISSUE TITLE
Types: missing `fill` properties in SVGAttributes

### ISSUE THREAD

**Issue by R-Bower** [BuilderIO/mitosis#838]
I'm coming over from Stencil and really like how simple this library is in comparison.  That said, I've a few questions on how to do certain things and could use some guidance.  If there's a better place for these questions, please let me know and I'll move them there.

Please pardon the contrived examples.  They're merely intended to illustrate scenarios.  

1. Variables in render

Coming from React, I often find myself creating variables in functional components to simplify the code.  Here's an example:

```
interface Props {
  some: {
    deeply: {
      nested: {
        prop: {
          values?: string[]
        }
      }
    }
  }
}

export default function Component(props: Props) {
  // this prop is now much easier to work with
  const valueArr = props.some.deeply.nested.prop.values ?? []
  return (
    <div>
      <div>
        {valueArr.map((value) => {
          return <div key={value}></div>
        })}
      </div>
    </div>
  )
}
```

What's the best way to do this with mitosis?  I combed the docs and couldn't find anything.

2. SVGs

While my knowledge of SVGs is limited, I noticed that some attributes that work properly in React/Stencil are giving me type errors in mitosis.  Consider the following:

```
export default function Component() {
  return (
    <svg>
      <g fill={"#000000"} id={"Shape"}>
        <use fill={"#000000"} filter={`url(#filter-1)`} xlinkHref={`#path-1`} />
      </g>
    </svg>
  )
}
```
errors:
```
// Property 'fill' does not exist on type 'GSVGAttributes<SVGGElement>'
// Property 'fill' does not exist on type 'UseSVGAttributes<SVGUseElement>'
```

Are there any gotchas, re: using SVGs in mitosis?

**Comment by samijaber** [comment]
There are absolutely zero gotchas with using SVGs in mitosis! This is just a bug with our JSX types: I found the issue with `GSVGAttributes`, but not sure what the best way is to fix this for `UseSVGAttributes` yet

**Comment by R-Bower** [comment]
Awesome, thanks @samijaber 

I just realized that there's a discord.  I'll put all future questions there.

**Comment by samijaber** [comment]
I'm going to keep this open, since it does point to a bug in the types :)

**Comment by moaoa** [comment]
hello @samijaber 
I'm interested in helping. Could you please guide me on how to fix the typing of UseSVGAttributes?
