### ISSUE TITLE
allow `useMetaData` hook to be used within component scope

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#851]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=FYZw9gdkA%3D%3D%3D&code=JYWwDg9gTgLgBAbzgVwM4FMCy6YEMAmuecAvnAGZQQhwBEAAgEbLAA2%2B6UAdMBAPQhgMCKmCpaAbgBQUtFhwEiuABQIpcChAgAuOAHJGuAF56pJAJQy52PITyr1cQ1F0HjpizPQAPSLDgc5LjIrPDkyAB2AMYwvBFwmACeAMLUkBHoETDKYFRgqOaIjtYKdipqGhqGRq64jFGmGp6OUDjIUPHKjhoAPPjAAG4AfN2VABLorKwQAIRwAJJwUbjxUJFwwPEASui4MQA0cABqyOiHAMoQrMD4h9BwADLAAI4s%2BDOjPXz9w47m0iQgA%3D

### Expected Behaviour

the `useMetadata` hook inside of the component should be parsed into the JSON

### Actual Behaviour

the `useMetadata` hook inside of the component is not parsed into the JSON

**Comment by samijaber** [comment]
We need to handle this in this if statement: https://github.com/BuilderIO/mitosis/blob/2e549a415342bd7ccbd461a8b10cb0f0c05c341c/packages/core/src/parsers/jsx/function-parser.ts#L205

This is how we handle it in the module scope: https://github.com/BuilderIO/mitosis/blob/2e549a415342bd7ccbd461a8b10cb0f0c05c341c/packages/core/src/parsers/jsx/metadata.ts#L44-L52

need to copy the 2nd piece of logic into the 1st

**Comment by hamatoyogi** [comment]
Worth closing this issue @samijaber.
