### ISSUE TITLE
allow `useMetaData` hook to be used multiple times in same component

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#852]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=FYZw9gdkA%3D%3D%3D&code=JYWwDg9gTgLgBAbzgVwM4FMCy6YEMAmuecAvnAGZQQhwBEAAgEbLAA2%2B6UAdMBAPQhgMCKmCpaAbgBQUtFhwEiuABQIpcChAgAuOAHJGuAF56pJAJQy52PITyr1cQ1F0HjpizPQAPSLDgc5LjIrPDkyAB2AMYwvBFwmACeAMLUkBHoETDKYFRgqOaIjtYKdipqGhqGRq64jFGmGp6OUDjIUPHKjhoAPPjAAG4AfN2VABLorKwQAIRwAJJwUbjxUJFwwPEASui4MQA0cABqyOiHAMoQrMD4h9BwADLAAI4s%2BDOjPXz9w47m0iQgA%3D

### Expected Behaviour

`useMetadata` hook content is merged together

### Actual Behaviour

the last `useMetadata` hook is the only one that applies

### Additional Information

This code needs to merge with the existing content instead of overwritings

https://github.com/BuilderIO/mitosis/blob/2e549a415342bd7ccbd461a8b10cb0f0c05c341c/packages/core/src/parsers/jsx/metadata.ts#L46

**Comment by decadef20** [comment]
Can I work on it ?

**Comment by samijaber** [comment]
@decadef20 100%!
