### ISSUE TITLE
vue props spread should be $props 

### ISSUE THREAD

**Issue by kingzez** [BuilderIO/mitosis#869]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFAT0AD0iw4bEjmRN4JZADsAxjG6a4AWQCeAYQqRN6TTAAUYcmFQBKRBLhxtETangBtTRwQdAAaOAwYADkg9ABdOABeFAxsPHRbKmx0ADd0KmdJdzgodBhkKANbIo8AHhZgbIA%2Bao84GoBxCAgWABkRGBbWxA4RhwgnQkG4HmahjwAJdCYmCABCOABJTxwDKC04YAMAJXQcXTCANWRQuEwIJmAWMOg4PoBHRhZVlpqeeqaigUJIQgA

### Expected Behaviour

Vue should pass props as  `v-bind="$props"`

### Actual Behaviour

Vue is passing props  as  `v-bind="props"`

**Comment by samijaber** [comment]
Thanks for catching this. 

The logic is here: https://github.com/BuilderIO/mitosis/blob/345852b71e77e604ab87e2d27c2ba51a0cf16e8a/packages/core/src/generators/vue/blocks.ts#L369-L381

We'd want to add a check where, if `value?.code === 'props'`, then it gets prefixed with `$`.

**Comment by kingzez** [comment]
Closed by https://github.com/BuilderIO/mitosis/issues/869
