### ISSUE TITLE
Fiddle: Eslint cannot parse TS code

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#882]
<img width="638" alt="CleanShot 2022-11-07 at 09 12 27@2x" src="https://user-images.githubusercontent.com/1393142/200319146-b03170d0-f408-4f0b-9ec5-ef6ebde303ac.png">

ESLint is throwing errors due to TS code. We need to configure the eslint instance in MonacoEditor to use the typescript-eslint parser https://typescript-eslint.io/docs/

https://github.com/BuilderIO/mitosis/blob/323af7949ec12902e3df095342a213d2c619fd49/packages/fiddle/src/components/CodeEditor.tsx#L20-L38

**Comment by decadef20** [comment]
Once I load and use `@typescript-eslint/parser` in component file , it occurs error.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/7866718/201150782-21904a43-2fe2-46c2-aefa-fa9ee3686576.png">

here is [`constants.js`](https://splibanais.org/node_modules/%40nodelib/fs.scandir/out/constants.js)

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/7866718/201151276-d779f0ed-a428-46d4-8c19-b6c277d95de9.png">

I guess it doesn't support browser environment.

**Comment by samijaber** [comment]
Agh, that seems messy...

**Comment by decadef20** [comment]
> I wonder if there's some way to hack around this, or if there's some other TS parser out there that can do the job in the browser. 😕

I'll try find a new way

**Comment by decadef20** [comment]
[ts eslint playground](https://typescript-eslint.io/play/) is a good case to learn from. I'll figure it out later
