### ISSUE TITLE
[eslint-plugin-mitosis]:  ref-no-current fails when useRef has generic type

### ISSUE THREAD

**Issue by decadef20** [BuilderIO/mitosis#885]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

no

### Expected Behaviour

should work well 

### Actual Behaviour

failed

**Comment by samijaber** [comment]
@decadef20 can you share a code snippet of the failure?

**Comment by decadef20** [comment]
I tested it again. I got it wrong. It works well.  

I  close the issue.
