### ISSUE TITLE
Angular: function calls missing "this." prefix

### ISSUE THREAD

**Issue by chadalen** [BuilderIO/mitosis#888]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=IYOw5grgNsBOQ%3D%3D%3D&code=JYWwDg9gTgLgBAbzhAdgVTAEwIYwKZwC%2BcAZlBCHAEQACARgK7AA2meUAdMBAPQjAwIAZ2BCqAbgBQoSLESkGKAMYxuKAIxFS5SgHIhFPAFow2JQGtsAczy6pkvAA9Z8NiWwNm8EopVq4ALIAngDCFJAoeCgwABRg5GBCAJSIknBwacjoWLh4MTEpALwAfKnp6Tw8cJgQeEJwKBDwAO7Q5nDNABZRcFB4JOxRSsAoVnDYCsqqqHAjImzjcJ0QEOaZ6T5TauoxCOvlBiB4APJg0ygAXJN%2BqABM%2B4RJmY%2F2G77n1%2Be3BanPkpmbG4oT5qADMPz25TglQ6bXqXR6fQGfWUIzGE0BHwgDBg8wIEBIi2Wq32SlQQnghxOdAAVnBCmUoXAlNhmMw6GZzFdMWp7lDCH9Mn0YAwoMCYvsADyYYAAN2K%2B3SHGVUp4MvlmSSUkIQA%3D

### Expected Behaviour

Output should be
```ts
  ngAfterContentChecked() {
    // does not work when referencing a function inside a hook
    function1({
      someOption: this.function2,
    });
  }
```

### Actual Behaviour

Output is currently missing "this" (so angular will throw an error saying can't find "function2") 
```ts
  ngAfterContentChecked() {
    // does not work when referencing a function inside a hook
    function1({
      someOption: function2,
    });
  }
```

### Additional Information

See stackblitz showing the error
[see here](https://stackblitz.com/edit/angular-ivy-9bpr2s?file=src%2Fapp%2Fsome-component%2Fsome-component.component.ts,src%2Fapp%2Fapp.module.ts)

Why would we want to do this?
See [this](https://mitosis.builder.io/?outputTab=IYOw5grgNsBOQ%3D%3D%3D&code=JYWwDg9gTgLgBAbzhAdgVTAEwIYwKYA0cArgM54BKeAZnAL5zVQQhwDkAAgEbHAA2mPFAB0wCAHoQwGBFLBSbANwAoUJFiI4AYyh5ceAAoQwYIfUbNWAIg6QTQgFalxW6HisrleAB7r4g6mxiPnhqYhQtGDEUOABZAE8AYRZIFDwUGAAKMGYwUgBKRGU4bVRSeBkIEOAwKloAXhJyOoAebBR4gD5MlGC%2BfJUS1xRyuBgoYABzSaE6uEaySho2ju7evn7B0pH4bChmAHc5hebl9q6evoHlYuR0LH1MzML6zqKSod19I3soTPGpjMoHUiJVqrUaEQELcPnAwHxsFo8CB0jAAFxw3KkYTwxHI1EEGEfcpQfSTeIYtjYLikKrEfBsQmwkogCCYYDUYBCUgYgDaRNh0OZzJQ2BRlOofBqjIFzOMUTKGKFwuZgQ2XERAGsDAikSiMjy4DMYDq8fqYAAxbDqrUAeTACpG2SxON1%2BIy%2BSZKpKdC9wt9spKyu9ovF7Ag1Go5BgMu9JXl0UNwbjEajeHRRvTABUIFUomBbZHo36VQHvWWVUhQ3hKTk8AA3VG2xtQSUQA6M5AOxNKuHYTDslCTDEARgAbOYK8Lk8Lq5S9odYynu4rNHg%2BO6Mwv2yC%2BwPgEPe1wIDAZCAMQBmABMoOMGIADJOS7Cpx8ALolujXH1EXlg%2FO7gC0yzJCcDbkcoE5MY2K4nqqJvtctxhBEjqZiabrmlaNpaJq9qOqQ2QYaihTJhycCEWaqIAPyiBEfDEIIBFsMep4sGw%2BQkbKugwMQUAxLyzEnmenZsBMkwABYxkQbAbtQUnsDIYBsG%2BWw%2BkSZEUXBGQ0QeWj0YxmRsIp7GccK3G8fxRnGCJYmSSJsnyYJrEgMpqn0OptCaZuOl0QxeBMQ5JnvMy5l8XAAmBdJxnSSxwnSbZMYqUSdAeeRsHebRel%2BUxCVBTOcChZZuVRdZMVCWx0mBUlL43LChXhVZSmVTQjnFewsVsdV7lIeEkTRGhOZ5jUhZplkqbRgAIrg2CmR8wyjFIKCgMQIB1EI6RIgAysAABeeDzHAV5Xp4sIabKmTjemU0wNgwi6NQ60RHgwgHMAmAwOJcBvIty2rTQj1bbt%2B0AGTA4G5GXTA123el5qZfp%2FmGR1LmFAAPqj4PxkWV3Ta6lEZPD2WGcZHFoxjwoXdjUO4%2FdAPPeJeBTJJX1wD9IArWtuhPdte1wKD4OU6N0N41pMCEwZolMzGZOY8gVPC7DqLi4jMktSZ%2BRErNdXphZ4X3kQV73l1alEuI4hwFmDMFf9XNInA66bnA8hjLmcCkCA1p8EQtJgTEkNO6QYEDngmCpYLk244rBO6QjTHlHs0tax89W8gAtOOBtG25DDruQTueZDCtEdHvkS%2BkmB5VxOthbyGeHVnyVEin%2Bv111KW3PVLTsvWnTCH3LTiN3nQqClQA) mitosis fiddle which shows a real world example (doesn't contain all the code just a snippet to show the problem)

**Comment by samijaber** [comment]
This is the same bug as Vue's API here: https://github.com/BuilderIO/mitosis/issues/780#issuecomment-1307489930

the solution should be the same here too: improve the code processor plugin here https://github.com/BuilderIO/mitosis/blob/a762948e6014450d5b8b80c961b771df4568f847/packages/core/src/generators/angular.ts#L250-L276


to include an additional transformation that prefixes the necessary method calls with `this.`. It should look something like this:

```ts

code => {
  const allMethodNames = Object.entries(json.state).filter(
    ([key, value]) => value?.type === 'function' || value?.type === 'method',
  ).map(([key]) => key);

  return replaceIdentifiers({ code, from: allMethodNames, to: name => `this.${name}` })
}
```

**Comment by decadef20** [comment]
Any progress here? I'll try it later
