### ISSUE TITLE
Mitosis angular output accessing nativeElement when undefined

### ISSUE THREAD

**Issue by chadalen** [BuilderIO/mitosis#889]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=IYOw5grgNsBOQ%3D%3D%3D&code=JYWwDg9gTgLgBAbzhAdgVTAEwIYwKYA0cArgM54BKeAZnAL5zVQQhwBEAAgEbHAA2mPFAB0wCAHoQwGBFLBSbANwAoZXgAekWHEHVsxPvGrEUAYxhiUcALIBPAMItIKPChgAKAJSJlcOKdRSeFIWSho4AF4ScipqAB5sFFsAPncUAz5PFT9UDBx8dy9I5J8%2FP2BadwBCEJAw6m8EXzK%2FKDwYYigUbLK6VT86IgBtWvqAXSz%2BuDaOrrh3Zr84zGAAN0WytuoIhFHYvpbkjb9hU4248RXVo79JvqA%3D

### Expected Behaviour

Angular output
```ts
    if (!this.someRef?.nativeElement) {
      return;
    }
```

### Actual Behaviour

Angular output
```ts
    if (!this.someRef.nativeElement) {
      return;
    }
```

### Additional Information

Shows errors in the console
"ERROR TypeError: Cannot read properties of undefined (reading 'nativeElement')"
[see stackblitz](https://stackblitz.com/edit/angular-ivy-cqu8se?file=src%2Fapp%2Fmy-component%2Fmy-component.component.ts)

Also causes other issues where classes inside "classNames" function do not appear in the dom when they should.

**Comment by samijaber** [comment]
1 liner here: add `?`  https://github.com/BuilderIO/mitosis/blob/3ca7e8cb0f9b0b7d1134d2a0de692a0a0d306d03/packages/core/src/generators/angular.ts#L342

**Comment by PatrickJS** [comment]
the real issue is that angular doesn't use dependency array for onUpdate so the correct solution is being smart on what is happening in the onUpdate code and move that code to the correct angular lifecycle hook. so right now we have to manually run checks for things which is why this might be undefined at one point.

**Comment by PatrickJS** [comment]
<img width="549" alt="Screen Shot 2022-11-09 at 11 50 44 AM" src="https://user-images.githubusercontent.com/1016365/200927422-a13333a5-1ea3-4eab-a91d-ab6ebda4eab7.png">
^ mitosis needs to determine the type of code in onUpdate and determine which lifecycle it should live based on the deps array.

**Comment by samijaber** [comment]
That sounds like a separate issue though? We can open a separate ticket for it. But it looks like we might need to build a special boilerplate for Angular to support tracking changes in an array of dependencies, by having a special version of `ngDoCheck`, storing references to everything that's tracked, and comparing new & old values https://angular.io/guide/lifecycle-hooks#defining-custom-change-detection

**Comment by chadalen** [comment]
> 

I tried moving the code inside `onUpdate` mitosis hook to the `onMount` mitosis hook and seeing the same issue.

mitosis code
```jsx
  onMount(() => {
    // handle closing tooltip upon clicking outside of tooltip
    document.addEventListener("mousedown", handleClickOutside);
  });

  onUnMount(() => {
    document.removeEventListener("mousedown", handleClickOutside);
  });
```

converts into
```ts
    ngOnInit() {
        document.addEventListener("mousedown", this.handleClickOutside);
    }
    ngOnDestroy() {
        document.removeEventListener("mousedown", this.handleClickOutside);
    }
```

but still seeing lifecycle issues because `handleClickOutside` `nativeElement` is still undefined when it should not be.
```ts
    handleClickOutside = function handleClickOutside(event) {
        if (!this.tooltipRef.nativeElement?.contains(event.target) &&
            !this.triggerRef.nativeElement?.contains(event.target)) {
           console.log('do something...');
        }
    };
```

Here's a stackblitz
[see here](https://stackblitz.com/edit/angular-ivy-luc5g8?file=src%2Fapp%2Fecs-atlas-tooltip%2Fecs-atlas-tooltip.component.ts)

**Comment by PatrickJS** [comment]
the `undefined` error is because the function is pass by reference without binding `this`

**Comment by chadalen** [comment]
> 

Alright so basically if there's mitosis code like this

```
  onMount(() => {
    document.addEventListener("mousedown", handleClickOutside);
  });

  onUnMount(() => {
    document.removeEventListener("mousedown", handleClickOutside);
  });
```

then angular output should be

```
  ngOnInit() {
    document.addEventListener("mousedown", this.handleClickOutside.bind(this));
  }

  ngOnDestroy() {
    document.removeEventListener("mousedown", this.handleClickOutside.bind(this));
  }
```

**Comment by PatrickJS** [comment]
the mitosis code can be updated to
```javascript
document.removeEventListener("mousedown", () => this.handleClickOutside());
```
https://mitosis.builder.io/?outputTab=IYOw5grgNsBOQ%3D%3D%3D&code=JYWwDg9gTgLgBAbzhAdgWQgVxTANMlAVXSx30wGcBTAJSoDM4BfOeqCEOAIgAEAjTMAA2AEypQAdMAgB6EMBgQKwClwDcAKA1UAHpFhwx9AIaYh8etgDGMaSjhoAngGEOkFFRwAKMOzAUASkQNODgrVAp4Cg5aBjgAXjhKWPovFDMhAM0Q1mtbVDgAC2MUESEqZyFgKwBrAHlMGGUxLyCEHNDwlGjyiSEIAHMvaJAUgJymLVDUDGwYL1aEgD5g0NCRCCtMUZwJYxERAFEAN08YABkVGE9xLy4QLGoNgHcULnxF%2BJXi0vLK6vqjWaVFaWQmYJyqGIs28nxW7TWhk22zOEigVAepxOZ0ukRuUDuD2SLzeHyCXyKJTKFSqtQaTWALQCYNCTAhoXRMEwUHsXg6cAAPCJgMd%2BRyGPEECMUpNEUsxXAJEr%2BQKZMLjvLQmCmEA%3D

so it works in react but it wont unsubscribe so you have to workaround everything with this
https://mitosis.builder.io/?outputTab=IYOw5grgNsBOQ%3D%3D%3D&code=JYWwDg9gTgLgBAbzhAdgWQgVxTANMlAVXSx30wGcBTAJSoDM4BfOeqCEOAIgAEAjTMAA2AEypQAdMAgB6EMBgQKwClwDcAKA1UAHpFhwx9AIaYh8etgDGMaSjhoAngGEOkFFRwAKMOzAUASkQNODgrVAp4Cg5aBjgAXjhKWPovFDMhAM1Q8JRI1ntE5LpUryD4gD44AAtjFBEhKmchYCsAawB5TBhlMTKsrVDLFBs7GrqGppb2rp7gPqCEENCwiIhGiSEIAHMvaJAUgOWmQYIMbBgvMoSqpZXDCCtMA5wJYxERAFEAN08YABkVDBPOIvFwQFhqCIIAB3FBcfD0FADUJMAbLVDEc7ea6VYL3aFPF4wCRQKgQ34%2FP6AyIgqBgiHJaFwhEFFHMdGhMkwTBQexeZahAA8ImA30FKzJ9HiCH2KRO9wqEtCElVEqFMlF3yVoQGTCAA

**Comment by chadalen** [comment]
Dang that's very unfriendly though. How does the event object get passed in when you do this?
```
const fn = useRef(() => handleClickOutside());
```

can you do this?
```
const fn = useRef((evt) => handleClickOutside(evt));
```

**Comment by PatrickJS** [comment]
yeah you do `const fn = useRef((evt) => handleClickOutside(evt));` so the mitosis angular output would need to be updated later

**Comment by chadalen** [comment]
Closing this ticket since with Patrick's solution the `nativeElement` is no longer `undefined`.
