### ISSUE TITLE
ESLint: no-var-name-same-as-state-property does not check functions

### ISSUE THREAD

**Issue by chadalen** [BuilderIO/mitosis#891]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [x] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNrrgXzgDMoIQ4AiAAQCNlgAbAE3SgDpgIB6EYHVYKgoBuAFCj0AD0iw4LIgENkDeEWQA7AMYxO6uAFkAngGEykdenUwAFGFJhUASkSi4cTRHWp43hTDwAvCgY2LjWCK5ucABuCgzI6ABccADkKZH4jmKRalo6nnAghgBiGtq61s4RUe6e3jFxCXBBKahkeLHx6CliNb7%2BbJ1NQUPovQTiblDoMMhQetaRbgA8TMDRAHxLUWy728tca5uRWaL4QA

### Expected Behaviour

This should be valid mitosis code. This is misleading because `state.value` should be scoped since it's inside an object.
However we can't define a local variable with the same name or else mitosis will fail to parse it.

fails to parse
```tsx
  const state = useStore({
    value: ''
  });

  function myFunction() {
    const value = 'some value';
    state.value = value;
  }

  return (
    <div>
      ...
    </div>
  );
```

workaround
```tsx
  const state = useStore({
    value: ''
  });

  function myFunction() {
    const tempValue = 'some value';
    state.value = tempValue;
  }

  return (
    <div>
      ...
    </div>
  );
```

### Actual Behaviour

Mitosis fails to parse due to variable named the same (although the variables in mitosis look like they are in different scopes)

**Comment by sahilmob** [comment]
@samijaber Sure thing. will take a look ASAP
