### ISSUE TITLE
Repo Request: Enable GitHub Discussions

### ISSUE THREAD

**Issue by wesrice** [BuilderIO/mitosis#903]
👋 Greetings!

I've been working with Mitosis for the past week as part of a hackathon project. Mitosis is a cool concept and I've had a great experience using it. I think you are on to something!

I'm interested in following the evolution of Mitosis. I'm wondering if the GitHub discussions panel can be enabled as a spot for API discussions, feature requests, and design proposals. I think it'd be cool to monitor the evolution of this project without having to read through various bugs within issues.

**Comment by samijaber** [comment]
Sure. Done!
