### ISSUE TITLE
Default props can't be `undefined` or `null`

### ISSUE THREAD

**Issue by rootEnginear** [BuilderIO/mitosis#913]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [X] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=M4NwpgNgLmQ%3D&code=JYWwDg9gTgLgBAbzgVwM4FMAi6BmBDZAGxgAUoIxU4BfOHckOAcgAEAjZYQgE3SgDpgEAPQhgMCKmComAbgBQ89AA9IsOL3xF4OZADsAxjCF64AWQCeAYQjgIe9HpgAKMOUoBKRPLgoM2LWIyClRnBB9fOD08EHQALhQ9TWAHbgAaCOoPBQiodBhkKFNnCN8AHm5gADcAPgQ3EP5o2Ooy4UraiOz5aiA

### Expected Behaviour

The output should be:
```svelte
<script>
  export let name = undefined;
</script>

<div>{name}</div>
```

### Actual Behaviour

```svelte
<script>
  export let name;
</script>

<div>{name}</div>
```

### Additional Information

In Svelte, props without an assigned value are considered as a _required_ prop. The example above might work as well since it's in JavaScript. However, consider the next example in Typescript.

```tsx
import { useDefaultProps } from '@builder.io/mitosis';

interface MyComponentProps {
  name?: string;
}

export default function MyComponent(props: MyComponentProps) {
  useDefaultProps<MyComponentProps>({
    name: undefined,
  });

  return (
    <div>{props.name}</div>
  );
}
```

which yields:

```svelte
<script context="module" lang="ts">
  interface MyComponentProps {
    name?: string;
  }
</script>

<script lang="ts">
  export let name: MyComponentProps["name"];
</script>

<div>{name}</div>
```

Which apparently is not enough for TypeScript (and/or Svelte?). It needs explicit `undefined` (as follow) so that it will stop saying that "Property 'name' is missing".

```svelte
<script context="module" lang="ts">
  interface MyComponentProps {
    name?: string;
  }
</script>

<script lang="ts">
  export let name: MyComponentProps["name"] = undefined;
</script>

<div>{name}</div>
```

This issue might need additional check for other frameworks since I'm not familiar with them.

**Comment by samijaber** [comment]
This is a general problem: we need to improve the JSX Parser's logic that handles `useDefaultProps` to not ignore `undefined`/`null` values. PR at https://github.com/BuilderIO/mitosis/pull/896 is making improvements to it, and it looks to be fixed there!
