### ISSUE TITLE
prettier is runtime dependency

### ISSUE THREAD

**Issue by milahu** [BuilderIO/mitosis#931]
when i install mitosis with pnpm

```
pnpm i -D @builder.io/mitosis-cli @builder.io/mitosis
```

mitosis throws

```
npx mitosis build 
node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: Cannot find module 'prettier/standalone'
```

workaround

```
pnpm i -D prettier
```

fix

move prettier from devDependencies to dependencies

https://github.com/BuilderIO/mitosis/blob/8eea6e048450ddbf882acc9e4e58104822cacc7d/packages/cli/package.json#L55-L63

**Comment by samuelOsborne** [comment]
@samijaber Thanks, this helped me !
