### ISSUE TITLE
mitosis.config.cjs is not found

### ISSUE THREAD

**Issue by milahu** [BuilderIO/mitosis#932]
mitosis.config.cjs is not found

```
npx mitosis build

TypeError: Cannot read properties of null (reading 'targets')
```

error in line 15: mitosisConfig is null

https://github.com/BuilderIO/mitosis/blob/8eea6e048450ddbf882acc9e4e58104822cacc7d/packages/cli/src/commands/build.ts#L6-L19

getMitosisConfig returns null

https://github.com/BuilderIO/mitosis/blob/8eea6e048450ddbf882acc9e4e58104822cacc7d/packages/cli/src/commands/build.ts#L28-L29

by default only `mitosis.config.js` is found

https://github.com/BuilderIO/mitosis/blob/f2cd9b377c7f7d66728d5bb071363062081a1674/packages/cli/src/helpers/get-mitosis-config.ts#L9

workaround

```
npx mitosis build -c mitosis.config.cjs
```

**Comment by samijaber** [comment]
Yeah, a slight improvement would be to check the path to `.js`, and if that doesn't exist then try the `.cjs` extension instead as a fallback.

**Comment by codyebberson** [comment]
Looks like this was fixed here: https://github.com/BuilderIO/mitosis/commit/88e2321f4eab2e63d9f63640975bf6eea3961fce#diff-01aa8383ec0a2609afe64aaf46a7b85433d46656ce6384c7ef218a78496afe52

**Comment by milahu** [comment]
yes

https://github.com/BuilderIO/mitosis/blob/170ce0109733bd3034a48ef3604e2b7f39513cf0/packages/cli/src/helpers/get-mitosis-config.ts#L13
