### ISSUE TITLE
Error: CLI does not yet support target: mitosis

### ISSUE THREAD

**Issue by milahu** [BuilderIO/mitosis#935]
im trying to convert svelte to mitosis components

mitosis.config.js

```js
module.exports = {
  files: 'src/**',
  targets: [
    'mitosis',
  ],
};
```

this should work since #898

**Comment by samijaber** [comment]
We are missing the `componentToMitosis` in this `switch` statement: https://github.com/BuilderIO/mitosis/blob/8eea6e048450ddbf882acc9e4e58104822cacc7d/packages/cli/src/build/build.ts#L268-L272

Adding `case 'mitosis': return componentToMitosis` should fix the CLI
