### ISSUE TITLE
Angular Component Module Should not import BrowserModule

### ISSUE THREAD

**Issue by rub-sky** [BuilderIO/mitosis#938]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

[Reproduction in Builder](https://mitosis.builder.io/?outputTab=IYOw5grgNsBOQ%3D%3D%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFAT0AD0iw4bEjmRN4JZADsAxjG6a4AWQCeAYQqRN6TTAAUYcmFQBKRBLhxtETangBtTRwQdAAaOAwYADkg9ABdOABeFAxsPHRbKmx0ADd0KmdJdzgodBhkKANbIo8AHhZgbIA%2Bao84GuBNMGQYFtbPVFQEhARevs8IJmgALmoSlioQ0Y9CQiW4bJwmZHQhwODVsdbvUwALHE0Acx2EWxzrGFcExvDS6ODb3JsOXCgrmA4Nlt0M4DmMeM1DgBJADklE0EHgqGQYEgGBYcEEcDOuTgODgACFyAB3DBQQwQFiqAigeQ9Po1Hj1JpFAoSQhAA)

### Expected Behaviour

When generating a new Angular component with module using the Angular CLI, the only item in the `imports` array should be the `CommonModule`.

For example, here is a bare bones module for `apple.component.ts`:
```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {AppleComponent} from "./apple.component";

@NgModule({
  declarations: [AppleComponent],
  imports: [
    CommonModule
  ],
  exports: [AppleComponent]
})
export class AppleModule { }
```

### Actual Behaviour

The Angular output from Mitosis TSX outputs a module with `BrowserModule` as the only item in the `imports` array.

```typescript
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";  // <<<<< HERE

import { Component } from "@angular/core";

@Component({
  selector: "my-component, MyComponent",
  template: `
    <div>
      <input
        class="input"
        [attr.value]="name"
        (input)="name = $event.target.value"
      />

      I'm not supposed to have a BrowserModule import
    </div>
  `,
  styles: [
    `
      .input {
        color: red;
      }
    `,
  ],
})
export class MyComponent {
  name = "Steve";
}

@NgModule({
  declarations: [MyComponent],
  imports: [BrowserModule],  // <<<<< HERE
  exports: [MyComponent],
})
export class MyComponentModule {}
```

### Additional Information

As additional supporting evidence, official [Angular documentation](https://angular.io/guide/ngmodule-faq#should-i-import-browsermodule-or-commonmodule) outlines what module import should be placed where:

> Do not import [BrowserModule](https://angular.io/api/platform-browser/BrowserModule) in any other module. Feature modules and lazy-loaded modules should import [CommonModule](https://angular.io/api/common/CommonModule) instead. They need the common directives. They don't need to re-install the app-wide providers.

**Comment by samijaber** [comment]
It sounds like we need to remove it from this line then:

https://github.com/BuilderIO/mitosis/blob/9d88319e902712b13aaedb82a2c0b54971b14166/packages/core/src/generators/angular.ts#L96

cc @PatrickJS @alujs who worked on this generator a lot

**Comment by rub-sky** [comment]
`BrowserModule` needs to be replaced with `CommonModule`.

**Comment by jacquant** [comment]
Hi,
I think that this issue can be closed as it has been implemented thanks to this [commit](https://github.com/BuilderIO/mitosis/commit/1fe19074ec99bfb012af0d5e1cb37060de75db32).
