### ISSUE TITLE
`props.children` should support transforming children?

### ISSUE THREAD

**Issue by kingzez** [BuilderIO/mitosis#945]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [X] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

none

### Expected Behaviour

In UI component development, space component need transforming children and each child need add specific class, React recommended to use [exposing-multiple-components](https://beta.reactjs.org/apis/react/Children#exposing-multiple-components), but I think use multiple-components is not good DX for UI component user. Any good idea?

https://github.com/ant-design/ant-design-mobile/blob/56675ff887016ebec115666b2a7021d247d3a671/src/components/space/space.tsx#L44-L51

https://github.com/youzan/vant/blob/7c35b143dd7493c9e1ffad64285673f3881d194a/packages/vant/src/space/Space.tsx#L96-L117

### Actual Behaviour

none

**Comment by kingzez** [comment]
@samijaber Sorry, I didn't describe it clearly. I asking for a new feature and I am interested in.

### children API

The children helper is for complicated interactions with props.children, when you're not just passing children on to another component using {props.children} once in JSX.

React 
`React.Children` -  https://reactjs.org/docs/react-api.html#reactchildren

Solid 
`children` - https://www.solidjs.com/docs/latest/api#children

Vue
but it is jsx not template.
`slots.default()` - https://vuejs.org/guide/components/slots.html#scoped-slots

**Comment by samijaber** [comment]
This pattern of having a `Children` API to dynamically manipulate the children a parent receives is generally a brittle approach and should be avoided in React. See their latest beta docs: https://beta.reactjs.org/reference/react/Children

For this reason, and the fact that most other frameworks do not have a similar approach, I don't think we'll be building this out in Mitosis anytime soon. 

Exposing multiple components is now a fairly standard approach to better handle parent/child relationships, and works with all web frameworks so I suggest you go with that instead.
