### ISSUE TITLE
SlotModule generated in Angular output target

### ISSUE THREAD

**Issue by R-Bower** [BuilderIO/mitosis#953]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=IYOw5grgNsBOQ%3D%3D%3D&code=JYWwDg9gTgLgBAbzgZQDYXgXzgMyhEOAIgAEAjAV2FQBMBTKAOmAgHoRgYIBnYbogNwAoIXQAekWHHo4AhhVTwcFAHYBjGCxVwAsgE8AwgUgq6KmAAow%2BMNwCUiIXDhQ6MClG0WnzuAB4aYAA3AD4fXzgACTpUdABCOABJODVZbShVOGBtACU6WQ0AGjgANQo6YuQIVGAaYug4ABlgAEcqGjjw3z80DDgVWRA6AF4ibhhZWES1CBUiOFYwiL9WQNCfO2FMIA

### Expected Behaviour

The `<Slot />` component shouldn't generate an undefined dependency in the Angular output target.

### Actual Behaviour

When the `<Slot />` component is used, mitosis seems to think that it's a separate mitosis component.  It's included as a dependency in the generated Angular output target.  The generated dependency is called `SlotModule` and doesn't exist.

### Additional Information

It seems that this change was introduced in version `0.0.35` of the `@builder-io/mitosis-cli`.

**Comment by samijaber** [comment]
Thanks for catching this.

We are missing `Slot` in this `Set`: https://github.com/BuilderIO/mitosis/blob/44af1f538256eb66127a43516d4223aecd7957ae/packages/core/src/generators/angular.ts#L42
