### ISSUE TITLE
Running the tests for core on a fresh pull of main fails with snapshot differences in the "style 1" test.

### ISSUE THREAD

**Issue by cmgriffing** [BuilderIO/mitosis#956]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

No case

### Expected Behaviour

Tests pass on an unmodified branch.

### Actual Behaviour

The snapshot fails looking like this. Seems like a prettier issue. Maybe a change in config?

```
  +   "hooks": {},
  +   "imports": [],
  +   "inputs": [],
  +   "meta": {},
  +   "name": "MyComponent",
  +   "refs": {},
  +   "state": {},
  +   "style": "
  +   input {
  +     color: red;
  +     font-size: 12px;
  +   }
    
  - .form-input:focus {
  -   outline: 1px solid blue;
  - }
  +   .form-input:focus {
  +     outline: 1px solid blue;
  +   }
  + 
    ",
  - "subComponents": [],
  +   "subComponents": [],
    }
```

**Comment by cmgriffing** [comment]
After more fiddling, this must be an issue on my end, but I'm not sure how. I will dig into it. It seems like some kind of Prettier version inconsistency.

**Comment by cmgriffing** [comment]
I am reopening this, because I still have this issue and it is making it difficult to make PRs.

Does anybody else experience this issue? If it is ONLY me, then we can close this again, but I wanted to get a feel for how common the problem was.

**Comment by martwz** [comment]
Worked for me too, reacted with a 👍 to your [comment](https://github.com/BuilderIO/mitosis/issues/956#issuecomment-1356915171).

Versions:
```
/mitosis # git show --oneline -s
1249794e (HEAD -> main, origin/main, origin/HEAD) release (#948)
/mitosis # node -v
v19.3.0
/mitosis # yarn -v
3.2.0
```

Full logs: https://gist.github.com/martwz/b32eae4dc169735c482c1501efbc6f8a

**Comment by cmgriffing** [comment]
Yeah, I am not certain, but we have definitely narrowed it down to being just in my local.

A fully isolated VM works fine. So I will revert the snapshots and update the PR that I have hanging.

Interesting thing is that using Docker had the same issues as my local. Very confusing there. I will continue to look into it. Closing this for now until then.
