### ISSUE TITLE
Angular standalone output still generates NgModule

### ISSUE THREAD

**Issue by R-Bower** [BuilderIO/mitosis#960]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

N/A

### Expected Behaviour

The `standalone` option for the Angular output target should prevent an NgModule from being generated.

### Actual Behaviour

When the `standalone` option is provided to the Angular output target, the Angular code still generates an NgModule.  

As per the [Angular docs](https://angular.io/guide/standalone-components#the-standalone-flag-and-component-imports):
> Components, directives, and pipes can now be marked as standalone: true. Angular classes marked as standalone do not need to be declared in an [NgModule](https://angular.io/api/core/NgModule) (the Angular compiler will report an error if you try).

**Comment by samijaber** [comment]
Thanks for filing. We want to only run the following line if `options.standalone !== true`: https://github.com/BuilderIO/mitosis/blob/637ecbddf6d8082c1fbde34a8ba0c245a32874b7/packages/core/src/generators/angular.ts#L571

**Comment by harshilparmar** [comment]
I am on it!!
