### ISSUE TITLE
ESLint: no-var-same-name-as-state-property missing de-structures

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#963]
De-structures should still error, as they are declaring a variable with the same name:

```tsx
import { useStore } from '@builder.io/mitosis';

export default function MyComponent(props) {
  const state = useStore({
    foo: 'bar',
  });


  function myFunction() {
    const { foo } = props.obj
    // ^ this de-structure should not be allowed

    const { foo: foo1 } = props.obj
    // ^ this de-structure should be allowed since we are renaming the variable

    state.foo = foo;
  }


  return <div />;
}
```

[MItosis fiddle](https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNrrgXzgDMoIQ4ByAAQCNlgAbAE3SgDpgIB6EYHVYKgoBuAFCj0AD0iw4LIgENkDeEWQA7AMYxO6uAFkAngGEykdenUwAFGFJhUASkSi4cTRHWp43hTDwAvCgY2LjWCK5uxBAQAFyUNApQFAA0kfiOYuJualo6nnAghgBiGtq61s4RUe6e3ojREARwQXYQDmwQNABWkW5cXHAAenAwABaCcugAtN5QyNrIUHioYxDKTHDqEPA0eAoMDBAA7uhMfXC%2B%2FmxEMS2NYm744pHLMEt6ADxMwABucFwAHxifBAA%3D%3D%3D)

cc @sahilmob interested in grabbing this one? :)

**Comment by sahilmob** [comment]
Sure. Please assign to me
