### ISSUE TITLE
Error: Vue 2 template should have a single root element when <Context.Provider> as root

### ISSUE THREAD

**Issue by kingzez** [BuilderIO/mitosis#969]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMAi6BmBDZAGxgAUoIxU4BfOHckOAcgAEAjZYQgE3SgDpgEAPQhgMCKmComAKFCRYcAOJRg3AMIQAdjHQAPePQiMm%2FYQHM13fgGMdew%2F0Lj0c2QcXxe%2BIkeTatjBC2irWABRg5JQAlIiycCgY2L7EZBSo4QgJiXD2hMgg2gBccACsADQ5iRbIMHpQpQAMVYnUMbKdiVDoMMhQoeHVcAA8qupaugYw%2FOkAbup8cHN4BegAvAhI%2BYUlcFEZdhAFRRVwtfV8pQeU%2FBcNNNQAfMOJI9zAc08IN6h2ABZcbg9bTUEbCD5fODDcHjTQOaazcgLXhQF6JDrUWRAA%3D%3D

### Expected Behaviour

```tsx
import { useDefaultProps } from '@builder.io/mitosis'
import GridContext from './grid.context.lite'

export default function Grid(props) {
  useDefaultProps({
    column: 5,
    gutter: 0,
  })


  return (
    <GridContext.Provider value={{ column: props.column, gutter: props.gutter }}>
      <div>{props.children}</div> 
    </GridContext.Provider>
  )
}
```

above the code, `<GridContext.Provider>` as root, mitosis build  target (vue2), compiler work, both command line and fiddle

### Actual Behaviour

above the code, `<GridContext.Provider>` as root, mitosis build  target (vue2), compiler error, both command line and fiddle

```
react_devtools_backend.js:4012 Error: Vue 2 template should have a single root element
    at Fragment (574.fd986b20c812e7c0.js:1:141304)
    at e (574.fd986b20c812e7c0.js:1:145164)
    at 574.fd986b20c812e7c0.js:1:153067
    at Array.map (<anonymous>)
    at 574.fd986b20c812e7c0.js:1:153043
    at 574.fd986b20c812e7c0.js:1:371561
    at s (main-79e130091ee21132.js:1:86890)
    at Generator._invoke (main-79e130091ee21132.js:1:86678)
    at forEach.e.<computed> [as next] (main-79e130091ee21132.js:1:87313)
    at r (105.417418edac50b8fd.js:2008:3776629)
    at s (105.417418edac50b8fd.js:2008:3776832)
```

### Additional Information

add  div to `<GridContext.Provider>` should avoid this error，but I think it still a problem。

[work link](https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMAi6BmBDZAGxgAUoIxU4BfOHckOAcgAEAjZYQgE3SgDpgEAPQhgMCKmComAKFCRYcAOJRg3AMIQAdjHQAPePQiMm%2FYQHM13fgGMdew%2F0Lj0c2QcXxe%2BIkeTatjBC2irWABRg5JQAlIiycCgY2L7EZBSo4QgJiXD2hMgg2gBccACsADQ5iRbIMHpQpQAMVYnUMbKdiVDoMMhQoeHVcAA83MAAbgB8w4kjqupaugYw%2FOkT6nxwE3gF6AC8CEj5hSVwURl2EAVFFXC19XylF5T8Dw001DO5P6Pj0wgXqg7AALLjcHraagjYT%2FKZwWajYQLTQOFZrcgbXhQb65GFwnIdaiyIA%3D)

**Comment by samijaber** [comment]
This issue is somewhat related to #310. What happens is:
- our JSX parser adds empty whitespace siblings to the `<div>` element: 1 before, 1 after
- since the `Provider` is compiled away, we now have 3 elements at the root
- the JSX parser automatically wraps all of them with a `Fragment`
- the Vue 2 generator throws, due to receiving a root node that is a fragment: https://github.com/BuilderIO/mitosis/blob/8ce86e6f35587ab20f12f2d41ef67eb04a515e4a/packages/core/src/generators/vue/blocks.ts#L40-L45

What we should do is edit the code above so that:

```ts
const children = json.children.filter(filterEmptyTextNodes)

if (options.vueVersion === 2 && scope?.isRootNode && children.length > 1) {
  throw new Error('Vue 2 template should have a single root element');
}
return children.map((item) => blockToVue(item, options)).join('\n');
```

That should fix the issue
