### ISSUE TITLE
(https://mitosis.builder.io): Blank page in Safari

### ISSUE THREAD

**Issue by daniel-hritcu** [BuilderIO/mitosis#988]
### Reproduction case

https://mitosis.builder.io - Open using Safari (desktop or mobile)

### Expected Behaviour

Show fiddle or show browser incompatibility message.

### Actual Behaviour

Blank white page.
The page is not hydrated.

### Additional Information

Os: MacOs 13.1 (22C65)
Safari Version 16.2 (18614.3.7.1.5)

**Comment by samijaber** [comment]
I have zero clue why this doesn't work with Safari...this is very confusing. The Safari console logs don't really help much in this regard

**Comment by DanielHritcu** [comment]
It's a shot in the dark, but maybe it has to do something with regex if used?

https://github.com/knex/knex/issues/5221

**Comment by DanielHritcu** [comment]
It's a regex issue.

Running the fiddle locally, we get this:

```
Invalid regular expression: invalid group specifier name
eval@[native code] ../core/src/generators/alpine/generate.ts@http://localhost:3000/_next/static/chunks/src_components_App_tsx.js:23770:5 @http://localhost:3000/_next/static/chunks/webpack.js?ts=1674059638226:713:35 __webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1674059638226:37:37 eval code@ eval@[native code] ../core/src/generators/alpine/index.ts@http://localhost:3000/_next/static/chunks/src_components_App_tsx.js:23781:5 @http://localhost:3000/_next/static/chunks/webpack.js?ts=1674059638226:713:35 __webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1674059638226:37:37 eval code@ eval@[native code] ../core/src/index.ts@http://localhost:3000/_next/static/chunks/src_components_App_tsx.js:25295:5 @http://localhost:3000/_next/static/chunks/webpack.js?ts=1674059638226:713:35 __webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1674059638226:37:37 eval code@ eval@[native code] ./src/components/Talk.tsx@http://localhost:3000/_next/static/chunks/src_components_App_tsx.js:26321:5 @http://localhost:3000/_next/static/chunks/webpack.js?ts=1674059638226:713:35 __webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1674059638226:37:37 eval code@ eval@[native code] ./src/components/App.tsx@http://localhost:3000/_next/static/chunks/src_components_App_tsx.js:26244:5 @http://localhost:3000/_next/static/chunks/webpack.js?ts=1674059638226:713:35 __webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1674059638226:37:37 fn@[native code] promiseReactionJob@[native code]
```

**Comment by DanielHritcu** [comment]
The offending line is this:
https://github.com/BuilderIO/mitosis/blob/c6b09461f530cdbc71af036914c9899b02fe95eb/packages/core/src/generators/alpine/generate.ts#L63

When removing the lookahead, 
```const prefixEvent = (str: string) => str.replace(/event/gm, '$event');``` 
the fiddle works as expected.

**Comment by samijaber** [comment]
Very helpful, thank you @DanielHritcu 🙏

**Comment by adhrinae** [comment]
I'm still having a same issue. Have the new website been published yet?

**Comment by samijaber** [comment]
@adhrinae it has, but there seems to be a separate part of the codebase causing the same issue.
